window.LANSA.addSrc("labl",function(e,c,a,b){a.Aob={rLd:0,Eob:16};a.rW={EIc:1,Q$a:1,P$a:2,VOb:240};a.M$a={vLa:0,kYb:1};c.kr=function(){k.v.call(this);this.wu=a.Um.s7;this.AP=a.rW.EIc;this.Fda=a.M$a.vLa;this.ez=this.tz=this.pz=this.Az=0;this.Gj=null;this.hL=a.zj.uS;this.za=null;this.Ct=0;this.HT=a.Gg.vO;this.XZ=new c.ga;this.QF=new c.ga;this.Kc=this.Kc|a.Tb.N9|a.Tb.bva|a.Tb.O9a|a.Tb.mC|a.Tb.XR|a.Tb.P9a|a.Tb.lC;this.Vg=this.Vg|a.Jh.Gia|a.Jh.NN|a.Jh.mW;this.Ze(!1);this.mla(!1)};var k=c.u(c.kr,c.Qs);
k.R=function(){this.Gj&&(this.Gj.wa(this,this.v0a),this.Gj=null);k.j.R.call(this);this.Vc(null)};k.Ag=function(){return c.Ucb};k.Py=function(c){this.Gj!=c&&(this.Gj&&this.Gj.wa(this,this.v0a),this.Gj=c,null==this.Gj?this.mla(!1):(this.mla(!0),this.Gj.ya(this,this.v0a)),this.m(a.a.h),b.cb().sd(this,!1))};k.QB=function(){return this.Gj};k.dg=function(){return 0!=(this.AP&a.rW.Q$a)?!0:!1};k.Wu=function(){return!this.Mn()&&this.dg()};k.Eh=function(c){c=this.AP&~a.rW.Q$a|(c?a.rW.Q$a:0);this.AP!=c&&(this.AP=
c,this.Bd(),b.cb().sd(this,!1),this.ha(a.a.h))};k.eIa=function(){return 0!=(this.AP&a.rW.P$a)?!0:!1};k.f4b=function(b){b=this.AP&~a.rW.P$a|(b?a.rW.P$a:0);this.AP!=b&&(this.AP=b,this.Jg(),this.ha(a.a.h))};k.HHd=function(c){this.EIa()!=c&&(this.AP=this.AP&~a.rW.VOb|c,this.Bd(),b.cb().sd(this,!1),this.ha(a.a.h))};k.EIa=function(){return this.AP&a.rW.VOb};k.Yj=function(c){this.wu!=c&&(this.wu=c,b.cb().sd(this,!1),this.ha(a.a.h))};k.Ij=function(){return this.wu};k.Re=function(){return this.Az};k.Be=function(c){this.Az!=
c&&(this.Az=c,this.Bd(),b.cb().sd(this,!1),this.ha(a.a.h))};k.Ue=function(){return this.pz};k.Ge=function(c){this.pz!=c&&(this.pz=c,this.Bd(),b.cb().sd(this,!1),this.ha(a.a.h))};k.Of=function(){return this.tz};k.se=function(c){this.tz!=c&&(this.tz=c,this.Bd(),b.cb().sd(this,!1),this.ha(a.a.h))};k.cg=function(){return this.ez};k.of=function(c){this.ez!=c&&(this.ez=c,this.Bd(),b.cb().sd(this,!1),this.ha(a.a.h))};k.sr=function(c){this.hL!=c&&(this.hL=c,b.cb().sd(this),this.m(a.a.h))};k.zc=function(){return this.za};
k.Vc=function(c){this.za!=c&&(null!=this.za&&(this.za.wa(this,this.Dl),this.za.sb()),this.za=c,null!=this.za&&(this.za.va(),this.za.ya(this,this.Dl)),this.Bd(),b.cb().sd(this),this.m(a.a.h))};k.Ms=function(){return this.hL};k.Qu=function(){return this.Ct};k.Ws=function(c){c!=this.Ct&&(this.Ct=c,this.Bd(),this.ha(a.a.h),b.cb().sd(this))};k.eJ=function(){return this.HT};k.pH=function(b){this.HT!=b&&(this.HT=b,this.Bd(),this.m(a.a.h))};k.jl=function(){var b=a.Xd.uC;switch(this.sg()){case a.yg.Fz:switch(this.SV()){case a.Ug.Xp:b=
a.Xd.uC;break;case a.Ug.HO:b=a.Xd.hMa;break;default:b=a.Xd.jMa}break;case a.yg.CI:switch(this.SV()){case a.Ug.Xp:b=a.Xd.iMa;break;case a.Ug.HO:b=a.Xd.RZb;break;default:b=a.Xd.TZb}break;default:switch(this.SV()){case a.Ug.Xp:b=a.Xd.RW;break;case a.Ug.HO:b=a.Xd.QZb;break;default:b=a.Xd.SW}}return b};k.lA=function(){return 0!=(this.Fda&a.M$a.kYb)};k.$vd=function(a){this.Fda|=a};k.PFc=function(a){this.Fda&=~a};k.awd=function(a,b){this.Fda=this.Fda&~a|(b?a:0)};k.Cd=function(a,b,c){k.j.Cd.call(this,a,b,
c);this.Uo(!1)};k.O2=function(a){k.j.O2.call(this,a);this.Uo(a)};k.Uo=function(a){k.j.Uo.call(this,a);a=this.we();this.PBb(a,!1)};k.Pi=function(){k.j.Pi.call(this);this.yd(a.W.Fx);this.yd(a.W.kva)};k.Uc=function(){this.TF(a.Tb.DJ,this.yJ());k.j.Uc.call(this)};k.Jp=function(a){null!=this.Gj?this.Gj.Je():k.j.Jp.call(this,a)};k.Ti=function(){this.VW();b.cb().Jz(this)};k.vA=function(){this.pQ()};k.wC=function(a){var b=!1,b=a.Qd().TMa(this,this.ea.Mh,this.q9a(),this.s9a(),this.r9a(),a);!1==b&&k.j.wC.call(this,
a)};k.Yd=function(b){""==b[1]&&(b[1]=a.hOb);k.j.Yd.call(this,b)};k.PBb=function(a,e){var f=b.Ac(a),g=b.Ac(f),n=null,l=0<this.Ct?this.Ct:-1;this.za&&(n=this.za.exb(f.ba()-4,f.ba()-4));f.Ua(f.L()+this.Az);f.Sa(f.O()+this.pz);f.Oa(f.pa-this.tz);f.xa(f.na-this.ez);var d=this.Db(),q=new c.ga,v=new c.ga,k=[],h="";k[0]=q;k[1]=g;k[2]=v;k[3]=l;k[4]=l;k[5]=0;this.Gxa(null,n,d,this.Sd(),f,k);q=k[0];g=k[1];f=k[5];this.za&&this.za instanceof c.JJ&&(h=this.za.Qg());this.XZ=q;this.QF=g;e||(n=this.Na().gb(),l=this.Wu(),
b.Fd[n].ng(n,g,h,q,l,this.eIa(),f))};k.Gxa=function(e,k,f,g,n,l){e=l[0];var d=l[1],q=l[2],v=l[3],C=l[4],h=l[5],d=b.Ac(n);if(null!=k&&this.td()){var y=a.sf.Tya;this.QB()||(y|=a.sf.bQa);h=y;if(this.Wu())switch(this.EIa()){case a.Aob.Eob:y|=a.sf.KA;break;default:y|=a.sf.KA,h|=a.sf.KA}else h|=this.wu;switch(this.sg()){case a.yg.Fz:h|=a.sf.eba;break;case a.yg.CI:h|=a.sf.Vya;break;default:h|=a.sf.tlb}b.Gva(k,f,g,n,0,this.jl(),this.jl(),this.Ms(),e,d,q,0,this.td()?0:2,v,C,y)}else if(h=this.kwb(d),0<f.length){d.$()>
n.$()&&(this.Wu()?this.EIa()==a.Aob.Eob&&(d=new c.ga(0,0,n.$(),d.ba())):d=new c.ga(0,0,n.$(),d.ba()));switch(this.sg()){case a.yg.Fz:d=new c.ga(n.O()+(n.$()-d.$())/2,1,d.$(),d.ba());h|=a.sf.eba;break;case a.yg.CI:d=new c.ga(n.pa-d.$(),1,d.$(),d.ba());h|=a.sf.Vya;break;default:d=new c.ga(n.O(),1,d.$()+1,d.ba()),h|=a.sf.tlb}switch(this.SV()){case a.Ug.Xp:d=new c.ga(d.O(),n.L()+(n.ba()-d.ba())/2,d.$(),d.ba());break;case a.Ug.HO:d=new c.ga(d.O(),n.na-1-d.ba(),d.$(),d.ba())}}l[0]=e;l[1]=d;l[2]=q;l[3]=
v;l[4]=C;l[5]=h};k.kwb=function(c){var e=this.Sd(),f=a.sf.Tya,g=this.Db();if(0<g.length)if(this.QB()||(f|=a.sf.bQa),this.Rx=b.UJ(g,e,this.Wu(),c.$(),c.ba()),this.Wu())switch(this.EIa()){case a.Aob.Eob:b.nA(g,c,f|a.sf.KA,e);break;default:b.nA(g,c,f|a.sf.KA,e),f|=a.sf.KA}else b.nA(g,c,f,e),f|=this.wu;return f};k.Ohc=function(){var a=b.RN();this.zk(!1,!0);this.kwb(a);this.Yb(a.$())};k.wA=function(c){if(this.eIa())switch(b.Bq(c)){case a.U.wNa:case a.U.R1b:case a.U.$1b:case a.U.Qka:case a.U.a2b:case a.U.BRc:case a.U.fTc:case a.U.V1b:case a.U.mTc:case a.U.Qgb:c.Zj(!0);
return}k.j.wA.call(this)};k.xA=function(a){var b=this.Mn(),c=this.Fp();(b||c)&&this.R_b(a,b,c)};k.R_b=function(a,e,f){var g=new c.ga,n=new c.ga(0,0,1E4,1E4);this.Wu()&&n.Oa(n.O()+a.$()-(this.ea.uj()+this.ea.rk()));this.PBb(n,!0);""==this.Db()&&this.XZ.Rf()||(""==this.Db()?g=this.XZ:(g=b.Ac(this.QF),g.xa(g.na+(0<this.QF.ba()?1:0)),g=g.QY(this.XZ)));e&&a.Oa(a.O()+this.ea.uj()+this.pz+g.$()+this.tz+this.ea.rk());f&&a.xa(a.L()+this.ea.Kk()+this.Az+g.ba()+this.ez+this.ea.dm())};k.$wa=function(a,b){k.j.$wa(a,
b);b[0]&&this.eIa()&&(b[0]=!1)};k.Mf=function(a){b.Gbb();return k.j.Mf.call(this,a)};k.Dl=function(c,e){switch(e.Za){case a.a.qb:case a.a.Rb:e.Th==this.za&&this.Vc(null);break;case a.a.h:e.Th==this.za&&(b.cb().sd(this),this.Bd())}};k.v0a=function(b,c){c.Za==a.a.Rb&&this.Py(null)};k.Is=k[a.W.AE]=function(a){k.j.Is.call(this,a);b.cb().sd(this,!1)};k.Lfd=k[a.W.kva]=function(){b.cb().sd(this,!1)};k.dE=k[a.W.Fx]=function(){b.cb().sd(this,!1)};k.iga=k[a.W.uva]=function(a){this.Ax()?this.Ze(!1):k.j.iga.call(this,
a)};k.JM=k[a.W.GJ]=function(){this.Gj&&this.Gj.Je()};k.mx=k[a.W.Fy]=function(b){this.lA()&&(this.Qn(),this.PFc(a.M$a.kYb));k.j.mx.call(this,b)};e.$c(c.kr,"PRIM_LABL",{Va:{Ellipses:{f:function(){return e.Ja(this.Ij(),a.Um.H)},i:function(b){this.Yj(e.Ba(b,a.Um.H))}},Caption:{f:k.Db,i:function(a){this.Wb(e.ra(a))}},Alignment:{f:function(){return e.Ja(this.sg(),a.yg.H)},i:function(b){this.Jb(e.Ba(b,a.yg.H))}},VerticalAlignment:{f:function(){return e.Ja(this.SV(),a.Ug.H)},i:function(b){this.Im(e.Ba(b,
a.Ug.H))}},FocusControl:{f:k.QB,i:k.Py},WordWrap:{f:k.dg,i:function(a){this.Eh(e.Fa(a))}},Selectable:{f:k.eIa,i:function(a){this.f4b(e.Fa(a))}},MarginLeft:{f:k.Ue,i:function(a){this.Ge(e.aa(a))}},MarginTop:{f:k.Re,i:function(a){this.Be(e.aa(a))}},MarginBottom:{f:k.cg,i:function(a){this.of(e.aa(a))}},MarginRight:{f:k.Of,i:function(a){this.se(e.aa(a))}},Image:{f:k.zc,i:k.Vc},ImagePosition:{f:function(){return e.Ja(this.Ms(),a.zj.H)},i:function(b){this.sr(e.Ba(b,a.zj.H))}},ImageHeight:{f:k.Qu,i:function(a){this.Ws(e.aa(a))}},
ImageSizing:{f:function(){return e.Ja(this.eJ(),a.Gg.H)},i:function(b){this.pH(e.Ba(b,a.Gg.H))}}},Jf:{Ef:"Caption"}});c.Ucb=function(a){s.v.call(this,a);this.YSa=this.Ct=this.PBa=this.Orb=this.Nrb=this.za=this.KD=this.Cea=this.nB=this.$tb=this.Ztb=this.Ytb=this.ib=null};var s=c.u(c.Ucb,c.Pl);s.Db=function(){return this.ib.textContent};s.Wb=function(a){this.ib.textContent=a};s.I8=function(){return this.ib};s.iR=function(){return this.ib};s.ng=function(b,c,f,g,n,l,d){null==this.za.parentElement&&this.w.appendChild(this.za);
if(null==this.YSa||this.YSa!=l)this.YSa=l,this.ib.spellcheck=!1,this.ib.setAttribute("contenteditable",l);this.za.style.backgroundImage=e.Gu(f);switch(this.la.eJ()){case a.Gg.vO:this.za.style.backgroundSize="contain";break;case a.Gg.FPa:this.za.style.backgroundSize="cover";break;case a.Gg.pf:this.za.style.backgroundSize="100% 100%";break;case a.Gg.Rd:this.za.style.backgroundSize="auto"}if(null==this.KD||this.KD!=n)this.KD=n,this.ib.style.whiteSpace=n?"pre-wrap":"pre";if(null==this.Cea||this.Cea!=
d)this.Cea=d,this.ib.style.textAlign=0!=(d&a.sf.Vya)?"right":0!=(d&a.sf.eba)?"center":"",0!=(d&a.sf.Sya)||0!=(d&a.sf.Uya)||0!=(d&a.sf.Xya)?(this.ib.style.textOverflow="ellipsis",this.ib.style.overflow="hidden"):(this.ib.style.textOverflow="clip",this.ib.style.overflow="visible");if(null==this.Ytb||this.Ytb!=c.O())this.Ytb=c.O(),this.ib.style.left=c.O()+"px";if(null==this.Ztb||this.Ztb!=c.L())this.Ztb=c.L(),this.ib.style.top=c.L()+"px";if(null==this.nB||this.nB!=c.ba())this.nB=c.ba(),this.ib.style.height=
c.ba()+"px";if(null==this.$tb||this.$tb!=c.$())this.$tb=c.$(),this.ib.style.width=c.$()+"px";if(null==this.Nrb||this.Nrb!=g.O())this.Nrb=g.O(),this.za.style.left=g.O()+"px";if(null==this.Orb||this.Orb!=g.L())this.Orb=g.L(),this.za.style.top=g.L()+"px";if(null==this.Ct||this.Ct!=g.ba())this.Ct=g.ba(),this.za.style.height=g.ba()+"px";if(null==this.PBa||this.PBa!=g.$())this.PBa=g.$(),this.za.style.width=g.$()+"px"};s.Ve=function(a,b){this.w=document.createElement("div");this.w.setAttribute("LANSAHandle",
this.$b);this.ib=document.createElement("div");var c=this.ib.style;c.position="absolute";c.outline="none";c.overflowX="hidden";c.overflowY="hidden";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.borderLeftWidth="0px";c.borderTopWidth="0px";c.borderRightWidth="0px";c.borderBottomWidth="0px";c.cursor="inherit";c.textDecoration="inherit";this.za=document.createElement("div");c=this.za.style;c.position="absolute";c.backgroundSize="contain";
c.backgroundPosition="center center";c.backgroundRepeat="no-repeat";this.w.appendChild(this.ib);this.w.appendChild(this.za);return s.j.Ve.call(this,a,b)};s.zU=function(){var a=this;this.U_();a.ib.addEventListener("paste",function(b){a.M$(b);b.preventDefault()},!1)};s.Lnb=function(){var a="";s.j.Lnb.call(this);"rgba(0,0,0,0)"==this.wSa&&""!=this.w.style.boxShadow&&(a=this.w.style.boxShadow);this.ib.style.textShadow=a};s.VJ=function(a){s.j.VJ.call(this,a);return!this.YSa};s.M$=function(){}});
