window.LANSA.addSrc("coll",function(e,c,a,b,k){a.DJa={fic:0,h2a:1};var s=0;c.Yia=function(){p.v.call(this)};var p=c.u(c.Yia,c.ed);p.evb=function(){return!1};p.YLb=function(){return!1};p.lc=function(){return 0};p.Rf=function(){return 0==this.lc()};p.yU=function(a){a&&(a.va(),a.cec(this))};p.QU=function(a){a&&(a.sb(),a.iPc(this))};p.WW=function(a,b){this.vMa(b);null!=this.GP&&this.GP.WW(a,b)};p.H2=function(a,b){this.wMa(b);null!=this.GP&&this.GP.H2(a,b)};e.$c(c.Yia,"PRIM_COLL",{Va:{AllowsDuplicates:{f:function(){return this.evb()}},
IsEmpty:{f:function(){return this.Rf()}},IsOrdered:{f:function(){return this.YLb()}},ItemCount:{f:function(){return this.lc()}}}});c.yKa=function(){t.v.call(this);this.$a=[];this.GP=null};var t=c.u(c.yKa,c.Yia);t.R=function(){this.jj();t.j.R.call(this)};t.evb=function(){return!0};t.YLb=function(){return!0};t.lc=function(){return this.$a.length};t.Vd=function(a){if(0>a||a>=this.$a.length)throw e.yC(a,this.$a.length);return this.$a[a]};t.fs=function(a,b){if(0>a||a>this.$a.length)throw e.yC(a,this.$a.length);
a==this.$a.length?this.xq(b):this.kgb(b,a)};t.f4a=function(a,b){return b===k?this.$a.indexOf(a):this.$a.indexOf(a,b)};t.aHb=function(a){return this.$a.lastIndexOf(a)+1};t.W3a=function(){return 0<this.$a.length?this.$a[0]:null};t.q4a=function(){return 0<this.$a.length?this.$a[this.$a.length-1]:null};t.qkd=function(){return this.Dca};t.rX=function(a){this.Dca=a};t.WDa=function(a){this.rX(a.v0b())};t.Ud=function(a){return-1!=this.$a.indexOf(a)};t.xq=t.WKb=function(a){this.yU(a);this.$a.push(a);this.WW(a,
this.lc()-1)};t.VKb=function(a){this.yU(a);this.$a.unshift(a);this.WW(a,0)};t.UKb=function(a,b){if(0>b||b>=this.$a.length)throw e.yC(b,this.$a.length);this.yU(a);this.$a.splice(b+1,0,a);this.WW(a,b+1)};t.U7a=function(a,b){if(0>b||b>=this.$a.length)throw e.yC(b,this.$a.length);this.yU(a);this.$a.splice(b,0,a);this.WW(a,b)};t.mr=function(a){a=this.$a.indexOf(a);if(-1==a)throw e.JPc();return this.Lp(a)};t.Lp=function(a){if(0>a||a>=this.$a.length)throw e.yC(a,this.$a.length);var b=this.$a[a];this.$a.splice(a,
1);e.nfa(b);this.QU(b);this.H2(b,a);return b};t.egb=function(){return this.Lp(0)};t.ggb=function(){return this.Lp(this.$a.length-1)};t.jj=function(){for(var a=0;a<this.$a.length;a++)this.QU(this.$a[a]);this.$a=[];this.Q$()};t.peb=function(a){for(var b=0,c=0;c<this.$a.length;c++)this.$a[c]===a&&b++;return b};t.kgb=function(a,b){if(0>b||b>=this.$a.length)throw e.yC(b,this.$a.length);var c=this.$a[b];e.nfa(c);this.QU(c);this.$a[b]=a;this.yU(a);return c};t.ag=function(){var a=e.N_a(this.Dca);if(a=e.he(a.fMa,
a.vnb))this.Eja(a),this.xq(a)};t.bj=function(){this.jj()};t.Ah=function(a){if(0<=a&&a<this.lc()){var b=this.Vd(a);b&&this.r$(b);this.ck=a;return"OK"}this.ck=-1;return"NR"};t.Vm=function(){return this.lc()};t.Cl=function(a){a===k&&(a=this.ck);0<=a&&a<this.lc()&&this.Lp(a)};t.ak=function(){var a=this.ck;0<=a&&a<this.lc()&&(a=this.Vd(a))&&this.Eja(a)};t.ll=function(a,b,c){for(var d=0;d<this.lc();d++){var e=this.Vd(d);if(e&&(e=e.PV())){var f={},g;for(g in e)f[g]=e[g].get();if(a(f))return null!=b&&b.set(d+
1),c&&this.Ah(d),this.ck=d,"OK"}}return"NR"};t.Oo=function(a){this.jj();for(var b=0;b<a;b++)this.ag()};t.Dq=function(){return new c.mbb(this)};t.Agb=function(){null==this.GP&&(this.GP=new c.RSb);return this.GP};c.RSb=function(){f.v.call(this)};var f=c.u(c.RSb,c.nbb);c.MSb=function(){g.v.call(this);this.ck=-1};var g=c.u(c.MSb,c.yKa);g.aR=function(){return"PRIM_LCOL<"+this.Dca+">"};g.Kec=function(a){for(var b=0;b<a.lc();b++)this.xq(a.Vd(b))};g.sic=function(a){for(var b=e.he("PRIM_LCOL"),c=0;c<this.lc();c++)b.xq(this.Vd(c));
for(c=0;c<a.lc();c++)b.xq(a.Vd(c));e.nfa(b);return b};e.$c(c.MSb,"PRIM_LCOL",{eK:a.Fu.$Ya,Va:{First:{f:function(){return this.W3a()}},Last:{f:function(){return this.q4a()}},Item:{f:function(a){return this.Vd(e.aa(a)-1)},i:function(a,b){this.fs(e.aa(a)-1,b)}},IndexOf:{f:function(a,b){return this.f4a(a,b===k?k:e.aa(b)-1)+1}},LastIndexOf:{f:g.aHb},Collects:{i:g.rX}},Ec:{Append:g.Kec,Concatenate:g.sic,Contains:g.Ud,Insert:g.xq,InsertFirst:g.VKb,InsertLast:g.WKb,InsertAfter:function(a,b){return this.UKb(a,
e.aa(b)-1)},InsertBefore:function(a,b){return this.U7a(a,e.aa(b)-1)},Remove:g.mr,RemoveAt:function(a){return this.Lp(e.aa(a)-1)},RemoveFirst:g.egb,RemoveLast:g.ggb,RemoveAll:g.jj,OccurrencesOf:g.peb,ReplaceAt:function(a,b){return this.kgb(a,e.aa(b)-1)}},Jf:{Ef:"Item"},so:{M9:function(a){var b=e.he("PRIM_NMBR");b.set(a);return b},Nn:function(a){return this.Vd(e.aa(a)-1)},Vt:function(){return this.lc()}},lw:{ag:g.ag,Ah:function(a){return this.Ah(e.aa(a)-1)},Oo:g.Oo,bj:g.bj,Vm:g.Vm,Cl:function(a){return this.Cl(a?
e.aa(a)-1:k)},ak:g.ak,ll:g.ll,Dq:g.Dq}});c.ePb=function(){n.v.call(this)};var n=c.u(c.ePb,c.yKa);n.aR=function(){return"PRIM_ACOL<"+this.Dca+">"};e.$c(c.ePb,"PRIM_ACOL",{eK:a.Fu.$Ya,Va:{First:{f:function(){return this.W3a()}},Last:{f:function(){return this.q4a()}},Item:{f:function(a){return this.Vd(e.aa(a)-1)},i:function(a,b){this.fs(e.aa(a)-1,b)}},IndexOf:{f:function(a,b){return this.f4a(a,b===k?k:e.aa(b)-1)+1}},LastIndexOf:{f:n.aHb},Collects:{i:n.rX}},Ec:{Contains:n.Ud,Insert:n.xq,InsertFirst:n.VKb,
InsertLast:n.WKb,InsertAfter:function(a,b){return this.UKb(a,e.aa(b)-1)},InsertBefore:function(a,b){return this.U7a(a,e.aa(b)-1)},Remove:n.mr,RemoveAt:function(a){return this.Lp(e.aa(a)-1)},RemoveFirst:n.egb,RemoveLast:n.ggb,RemoveAll:n.jj,OccurrencesOf:n.peb,ReplaceAt:function(a,b){return this.kgb(a,e.aa(b)-1)}},Jf:{Ef:"Item"},so:{M9:function(a){var b=e.he("PRIM_NMBR");b.set(a);return b},Nn:function(a){return this.Vd(e.aa(a)-1)},Vt:function(){return this.lc()}},lw:{ag:n.ag,Ah:function(a){return this.Ah(e.aa(a)-
1)},Oo:n.Oo,bj:n.bj,Vm:n.Vm,Cl:function(a){return this.Cl(a?e.aa(a)-1:k)},ak:n.ak,ll:n.ll,Dq:n.Dq}});c.YSb=function(){l.v.call(this)};var l=c.u(c.YSb,c.yKa);l.xq=function(b){this.yU(b);for(var c=0,d=this.$a.length-1;c<=d;){var e=Math.floor((c+d)/2);this.Zqc(b,this.$a[e])==a.Zc.dl?d=e-1:c=e+1}this.$a.splice(c,0,b)};l.Zqc=function(b,c){var d=a.Zc.Rj,f=e.Pb();f.Ub("SUBJECT",b);f.Ub("OBJECT",c);f.jM("RESULT",d,a.Zc.H);this.Aa(a.M.xEa,f);d=f.S3a("RESULT",a.Zc.H);f.jc();return d};e.$c(c.YSb,"PRIM_SACO",
{Va:{First:{f:function(){return this.W3a()}},Last:{f:function(){return this.q4a()}},Item:{f:function(a){return this.Vd(e.aa(a)-1)},i:function(a,b){this.fs(e.aa(a)-1,b)}},IndexOf:{f:function(a,b){return this.f4a(a,b===k?k:e.aa(b)-1)+1}},Collects:{i:l.rX}},Ec:{Remove:l.mr,RemoveAt:function(a){return this.Lp(e.aa(a)-1)},RemoveAll:l.jj,RemoveLast:l.ggb,RemoveFirst:l.egb,Contains:l.Ud,OccurrencesOf:l.peb,Insert:l.xq},Jf:{Ef:"Item"},so:{M9:function(a){var b=e.he("PRIM_NMBR");b.set(a);return b},Nn:function(a){return this.Vd(e.aa(a)-
1)},Vt:function(){return this.lc()}}});c.BW=function(a){d.v.call(this);this.Xbc=a};var d=c.u(c.BW,c.Yia);d.Vd=function(a){if(0>a||a>=this.lc())throw e.yC(a,this.lc());return this.$v(a)};d.lc=function(){return this.Xbc.lc()};d.$v=function(a){return this.Xbc.$v(a)};e.$c(c.BW,"PRIM_PCOL",{Va:{Item:{f:function(a){return this.Vd(e.aa(a)-1)},i:function(a,b){this.fs(e.aa(a)-1,b)}}},Jf:{Ef:"Item"},so:{Nn:function(a){return this.$v(e.aa(a)-1)},Vt:function(){return this.lc()}}});c.LSb=function(){q.v.call(this);
this.$a={};this.yP=null;this.He=a.DJa.h2a};var q=c.u(c.LSb,c.Yia);q.R=function(){this.jj();q.j.R.call(this)};q.aR=function(){return"PRIM_KCOL<"+this.OSa+" "+this.hwc()+">"};q.Pf=function(){return this.He};q.ub=function(a){this.He=a};q.lc=function(){return this.z$().length};q.Vd=function(b){b=this.vZa(b);if(this.$a[b]===k&&this.He==a.DJa.h2a){var c=null;this.hqb?c=new this.hqb:this.OSa&&(c=e.N_a(this.OSa),c=e.he(c.fMa,c.vnb));c&&(this.$a[b]=c,this.yU(c),this.RE())}return this.$a[b]};q.fs=function(a,
b){a=this.vZa(a);var c=a.toString();this.$a[c]===k?this.RE():this.QU(this.$a[c]);this.yU(b);this.$a[c]=b};q.$v=function(a){a=this.z$()[a];return this.$a[a]};q.m4a=function(a){a=this.z$()[a];this.yP.set(a);return this.yP};q.n4a=function(a){for(var b in this.$a)if(this.$a[b]===a)return this.yZa(b);return this.yP.Fxc()};q.rX=function(a,b){"string"!==typeof a?this.hqb=a:(this.OSa=a,this.hqb=b)};q.kOa=function(a){this.yP=new a;this.yP.va()};q.rkd=function(){return this.OSa};q.hwc=function(){var a="";this.yP&&
(a=this.yP.Csa());return a};q.WDa=function(a){this.rX(a.v0b(),a.Pwb(0));this.kOa(a.Pwb(1))};q.vZa=function(a){this.yP.set(a);a=this.yP.get();return a.toString()};q.yZa=function(a){this.yP.set(a);return this.yP.get()};q.mr=function(a){a=this.vZa(a);var b=null;this.$a[a]!==k&&(b=this.$a[a],e.nfa(b),this.QU(b),delete this.$a[a],this.RE(),this.H2(b,0));return b};q.jj=function(){for(var a in this.$a)this.QU(this.$a[a]);this.$a={};this.RE();this.Q$()};q.RE=function(){delete this.sD};q.z$=function(){var a=
this;if(this.sD===k){this.sD=[];for(var b in this.$a)this.sD.push(b);this.sD.sort(function(b,c){b=a.yZa(b);c=a.yZa(c);return e.cmp(b,c)})}return this.sD};var v={COLLECTION:a.DJa.fic,FACTORY:a.DJa.h2a};e.$c(c.LSb,"PRIM_KCOL",{Va:{Style:{f:function(){return e.Ja(this.Pf(),v)},i:function(a){this.ub(e.Ba(a,v))}},Item:{f:function(a){return this.Vd(a)},i:function(a,b){this.fs(a,b)},Hu:"na"},Collects:{i:q.rX},KeyedBy:{i:q.kOa},KeyOf:{f:function(a){return this.n4a(a)},Hu:"na"}},Ec:{Remove:q.mr,RemoveAll:q.jj},
Jf:{Ef:"Item"},so:{M9:function(a){return this.m4a(e.aa(a)-1)},Nn:function(a){return this.$v(e.aa(a)-1)},Vt:function(){return this.lc()}}});c.bSb=function(){C.v.call(this);this.sP=(s++).toString();this.EF=[];this.Dca=this.Gbc=""};var C=c.u(c.bSb,c.Yia);C.aR=function(){return"PRIM_DCOL<"+this.Dca+" "+this.Gbc+">"};C.lc=function(){return this.EF.length};C.$v=function(a){return this.EF[a].nF[this.sP]};C.Vd=function(a){return a.nF===k||a.nF[this.sP]===k?null:a.nF[this.sP]};C.fs=function(a,b){a.nF===k&&
(a.nF={});var c=a.nF[this.sP];c===k?(this.EF.push(a),a.va()):this.QU(c);a.nF[this.sP]=b;this.yU(b)};C.m4a=function(a){return this.EF[a]};C.rX=function(a){this.Dca=a};C.kOa=function(a){this.Gbc=a};C.n4a=function(a,b){for(var c=b;c<this.EF.length;c++){var d=this.EF[c];if(d.nF[this.sP]===a)return d}return null};C.Iqc=function(a){return this.Vd(a)};C.Ud=function(a){return-1!=this.EF.indexOf(a)};C.xic=function(a){for(var b=0;b<this.EF.length;b++)if(this.EF[b].nF[this.sP]===a)return!0;return!1};C.xq=function(a,
b){var c=this.Vd(b);this.fs(b,a);return c};C.mr=function(a){if(a.nF!==k){var b=a.nF[this.sP];if(b!==k)return delete a.nF[this.sP],this.EF.splice(this.EF.indexOf(a),1),e.nfa(b),this.QU(b),a.sb(),this.H2(b,0),b}return null};C.jj=function(){for(var a=0;a<this.EF.length;a++){var b=this.EF[a],c=b.nF[this.sP];c!==k&&(delete b.nF[this.sP],this.QU(c))}this.EF=[];this.Q$()};e.$c(c.bSb,"PRIM_DCOL",{Va:{Item:{f:function(a){return this.Vd(a)},i:function(a,b){this.fs(a,b)},Hu:"na"},Collects:{i:C.rX,Hu:"na"},KeyedBy:{i:C.kOa,
Hu:"na"},KeyOf:{f:function(a,b){return this.n4a(a,b!==k?e.aa(b)-1:0)},Hu:"na"}},Ec:{Contains:C.Ud,ContainsItem:C.xic,Insert:C.xq,Remove:C.mr,RemoveAll:C.jj,Find:C.Iqc},Jf:{Ef:"Item"},so:{M9:function(a){return this.m4a(e.aa(a)-1)},Nn:function(a){return this.$v(e.aa(a)-1)},Vt:function(){return this.lc()}}})});
