window.LANSA.addSrc("hint",function(e,c,a,b,k){function s(a){this.zt=a;this.pad=!1;this.wbc=new c.ga(0,0,0,0)}function p(a){this.zt=a;this.cXa=this.ib="";this.Rc=null}e.Eb("PRIM_PPNL");e.$c(function(){},"PRIM_HINT",{});c.YWb=function(a){t.v.call(this);this.zt=a;this.Grb=this.g_=this.Ki=this.mz=this.Bt=this.ST=null;a=b.KJ();e.Eb("PRIM_PANL");e.Eb("PRIM_LABL");this.ST=new c.Ol;this.ST.Ia(this);this.ST.hb(new c.ga(0,0,0,0));this.Bt=new c.kr;this.mz=new c.kr;this.Bt.Ia(this.ST);this.mz.Ia(this.ST);this.Grb=
new c.pb;this.Grb.CC(!0);this.g_=new c.pb;this.g_.qd(b.Q().aZ);this.g_.pn(0);this.g_.Gm(0);this.g_.Sl(0);this.g_.Vk(0);this.g_.rr(a);this.ST.Ln(this.g_);this.mz.Ln(this.Grb)};var t=c.u(c.YWb,c.bv);t.Sd=function(){return this.ST.Sd()};t.kPa=function(c,e,f){this.g_.qd(b.Q().aZ);c.O();c.L();this.Yb(c.$()+4);this.yc(c.ba()+4);this.ST.Yb(c.$());this.ST.yc(c.ba());this.mz.Yb(c.$());this.mz.yc(c.ba());this.Bt.Yb(c.$());this.Bt.yc(c.ba());this.mz.Wb(this.zt.rP);this.Bt.Wb(this.zt.Bt);0==this.mz.Db().length?
(this.Bt.Ua(0),this.Bt.Sa(0),this.Bt.Im(a.Ug.Xp)):(this.mz.Ua(2),this.mz.Sa(2),this.Bt.Ua(e.ba()),this.Bt.Sa(10),this.Bt.Im(a.Ug.UY));this.PWc(f.pad);this.A3(c.O(),c.L(),k,k,null)};t.ska=function(a){this.ST.Xf(100);return t.j.ska.call(this,a)};t.pfb=function(a){return t.j.pfb.call(this,a)};t.OQ=function(){this.Aia()&&this.zm()};c.oUb=function(){f.v.call(this);this.mWa=7;this.fU=this.k5=0;this.Xn=this.zna=this.Ana=null;this.GVa=3;this.aP=this.WK=this.l5=null;this.fL=0;this.pSa=b.c$(-1,-1);this.WK=
new c.YWb(this);b.QG().Lha().Ha(this,a.M.vY,this.g7)};var f=c.u(c.oUb,c.Si);f.rb=function(){b.QG().Lha().Us(this,a.M.vY);f.j.rb.call(this)};f.R=function(){this.zna=this.Ana=null;this.c3(null);this.qgb();b.ka(this.WK);this.WK=null;f.j.R.call(this)};f.c6a=function(a){this.fL|=a};f.A1=function(a){this.fL&=~a};f.Atd=function(a,b){this.fL=this.fL&~a|(b?a:0)};f.Pkd=function(){return this.aP};f.c3=function(c){if(this.aP!=c){this.aP&&(b.Q().Gs(this.aP,!1),this.aP.wa(this,this.Ezb));if(this.aP=c)this.aP.ya(this,
this.Ezb),this.aP.DA(!0);this.m(a.a.h)}};f.Iid=function(){return this.Xn};f.Kid=function(){return this.Ana};f.Gid=function(){return this.zna};f.$nd=function(){null==this.l5&&(this.l5=[]);return this.l5};f.Qkd=function(){return this.Bt};f.Rkd=function(){return this.rP};f.FHa=function(){return b.On().Cna/200};f.zjd=function(){return 1};f.Krd=function(){return 2};f.Ajd=function(){return 1};f.Lrd=function(){return 1};f.ysd=function(){return 6};f.zsd=function(){return 4};f.kBc=function(){return 0!=(this.fL&
1)};f.td=function(){return 0!=(this.fL&8)};f.ILb=function(){return 0!=(this.fL&16)};f.dLb=function(){return 0!=(this.fL&32)};f.HLb=function(a){var c=!1;a=b.Q().tA(a);null!=a&&a.U8a()&&(c=!0);return c};f.qgb=function(){if(this.l5){for(;0<this.l5.lo();){var a=this.l5.Lp(0);b.ka(a)}delete this.l5;this.l5=null}};f.tfa=function(a){this.HLb(a)||(this.z_b(a),this.Xn==a&&null==this.Ana&&null==this.zna)||(this.Xn=a,this.zna=this.Ana=null,this.rP=this.Bt="",this.k5=this.fU=0,this.Y_b(),null!=this.Xn&&null!=
this.Xn.gb()&&this.Xn.Cp(),this.Vza())};f.Edd=function(a,b,c,d){this.HLb(a)||(this.z_b(a),this.Xn==a&&this.Ana==b&&this.zna==d)||(this.Xn=a,this.Ana=b,this.zna=d,this.rP=this.Bt="",this.k5=this.fU=0,this.Y_b(),this.Vza())};f.z_b=function(a){this.Xn!=a&&(null!=this.Xn&&this.Xn.wa(this,this.izb),null!=a&&a.ya(this,this.izb))};f.Tnb=function(a){this.Xn==a&&this.Vza()};f.wwb=function(c){var e,f=null;e=b.ml();var d=b.Hbb(e),k=b.Q().Ueb(e);if(null==k||k!=this.aP)null==d||d.VEc()||(d=null),null!=d&&(f=d.Id()),
null!=d&&d.td()&&null!=f&&(null==this.Xn||this.Xn.Id()!=f)&&(f=d.Id().zic(e,a.Vra.xEb))&&(f.yd(a.W.sva),this.Xn==f&&(d=f)),this.Xn!=d&&this.tfa(null),this.ILb()?b.ebb(this.pSa,e)?++this.k5>=this.FHa()&&(this.k5=this.FHa(),this.c3(null),this.A1(16),this.fU=0,this.rP=this.Bt=""):(this.pSa=e,this.k5=0,this.Xn&&this.Xn.HHb()&&(this.rP=this.Bt="",this.fU=0,this.c3(null),this.A1(16))):(null!=this.Xn&&(d=!1,b.ebb(this.pSa,e)||(this.pSa=e,this.Xn&&this.Xn.HHb()&&(this.k5=this.fU=0),d=!1,this.fU<this.mWa&&
this.k5<this.FHa()?this.fU=0:c=!1),++this.fU>=this.mWa&&!d&&(this.fU=this.mWa,this.k5<this.FHa()?this.kPa():c=!1)),c&&3<=++this.GVa&&(this.GVa=3)),null==b.TN()&&this.qgb()};f.Ked=function(){return!1};f.Hed=function(){return!1};f.mJd=function(){};f.YAd=function(){};f.mNc=function(){this.kBc()||this.qgb();this.A1(1);this.tfa(null)};f.lNc=function(a){b.Q().zia()||(this.c6a(32),this.Tnb(a),this.A1(32))};f.nNc=function(){(0>b.Bh(a.Ga.iAa)||0>b.Bh(a.Ga.kna)||0>b.Bh(a.Ga.SRa))&&this.tfa(null)};f.JHd=function(){};
f.Vza=function(){if(null!=this.Xn)if(this.ILb())this.kPa();else{if(3>this.GVa||this.dLb())this.fU=this.mWa,this.wwb(!1)}else this.c3(null),this.A1(16)};f.kPa=function(){var b,c,e=new s(this),d=null;this.Xn&&(c=new p(this),this.Xn.yd(a.W.tva,c,null),d=c.Rc,b=c.ib,c=c.cXa);0==b.length&&null===d?(this.Bt=b,this.rP=c,this.c3(null),this.A1(16)):(this.XZc(d,b,c,e),this.GVa=0)};f.aCc=function(){this.c3(null);this.WK&&this.WK.Aia()&&this.WK.zm();this.A1(16)};f.XZc=function(a,e,f,d){null==a&&(a=this.WK);if(a!=
this.WK||this.dLb()||0<e.length&&this.Bt!=e){var q=b.av(0,0),p=b.av(0,0),p=new c.ga(0,0,0,0);this.Bt=e;this.rP=f;this.A1(2);p=this.a5b(this.Bt);this.td()&&0<this.rP.length&&(q=this.a5b(this.rP),0==q.ba()&&(q=this.b5b(this.rP)));0==p.ba()&&(p=this.b5b(this.Bt),0<this.rP.length&&p.Yb(p.$()+10));e=b.c$(d.wbc.O(),d.wbc.L());b.ebb(e,b.c$(0,0))&&(e=b.ml(),e.$j(e.yb()+15));p=this.Dsc(e,p,q);this.td()&&(this.c3(a),a==this.WK?this.WK.kPa(p,q,d):(d=b.c$(p.O(),p.L()),a==this.aP&&a.Lh()&&a.ska(d),a.A3(d.xb(),
d.yb(),k,k,null)));this.c6a(16)}};f.b5b=function(a){var e=b.av(0,0),f=this.WK.Sd(),d=new c.ga(0,0,0,0);b.nA(a,d,0,f);e.Yb(d.$()+6);e.yc(d.ba()+4);return e};f.a5b=function(a){for(var e=b.av(0,0),f=String.fromCharCode(13),d=this.WK.Sd(),k=a.indexOf(f),p=0;;)if(0<=k){var s;0!=k&&(s=a.substr(0,k));a=a.substr(k+1);0<s.length&&(k=new c.ga(0,0,0,0),b.nA(s,k,0,d),e.Yb(Math.max(e.$(),k.$())));p++;k=a.indexOf(f)}else{0<a.length&&(k=new c.ga(0,0,0,0),b.nA(a,k,0,d),e.Yb(Math.max(e.$(),k.$())),p++);break}1<p&&
(this.c6a(2),k=new c.ga(0,0,0,0),b.nA("W",k,0,d),e.Yb(e.$()+6),e.yc(k.ba()*p+4));return e};f.Dsc=function(a,e,f){var d=b.qC(),k=new c.ga(0,0,0,0),p=d.$()-1,s=d.ba()-1,d=new c.ga(d.O()+1,d.L()+1,p,s),s=d.aW(d),d=s.$();s.ba();if(e.$()<d){var h=a.xb();h+e.$()>d&&a.Xk(s.pa-e.$());k.Bb(a.xb(),a.yb());k.ih(e.$(),e.ba());0<f.ba()&&k.ZX(0,f.ba());f.$()>k.$()&&k.ZX(f.$()-k.$(),0);0<f.$()&&e.$()+10>f.$()&&k.ZX(10,0);return k}if(e.$()<p)return h=a.xb(),h+e.$()>p&&(h=p-e.$()),k.Bb(h,a.yb()),k.ih(e.$(),e.ba()),
k.ZX(0,f.ba()),k;k=this.Esc(e,s,a);k.ZX(0,f.ba());return k};f.Esc=function(a,e,f){var d=b.qC(),k=d.$()-2,p=d.ba()-2,p=new c.ga(d.O()+1,d.L()+1,k,p),d=[b.RN(),b.RN(),b.RN(),b.RN()],k=[];k.push(3);k.push(2);k.push(1);k.push(0);var s,h,t,J,p=e.aW(p);p.$();p.ba();e=a.$()*a.ba();s=p.O();h=p.L();d[0].Bb(s,h);d[0].ih(f.xb()-s,f.yb()-h);d[1].Bb(f.xb(),h);d[1].ih(p.pa-f.xb(),f.yb()-h);d[2].Bb(s,f.yb());d[2].ih(f.xb()-s,p.na-f.yb());d[3].Bb(f.xb(),f.yb());d[3].ih(p.pa-f.xb(),p.na-f.yb());for(h=p=t=0;4>h;h++){s=
k[h];J=d[s].$()*d[s].ba();t=Math.max(t,J);if(e<J){p=s;break}t==J&&(p=s)}d=d[p];k=a.ba();a=Math.min(a.$(),d.$());e=(e/a+k-1)/k*k;switch(p){case 0:d.Bb(f.xb()-a,f.yb()-e);d.ih(a,e);break;case 1:d.Bb(f.xb(),f.yb()-e);d.ih(a,e);break;case 2:d.Bb(f.xb()-a,f.yb());d.ih(a,e);break;case 3:d.Bb(f.xb(),f.yb()),d.ih(a,e)}return d};f.Y_b=function(){this.td();var a=null!=this.Xn&&null!=this.Xn.Na()&&this.Xn.Na().HN()&&this.Xn.td();this.fL=this.fL&-9|(a?8:0)};f.Ezb=function(b,c){switch(c.Za){case a.a.qb:case a.a.Rb:this.c3(null)}};
f.g7=function(){b.Q().oJa()||b.Q().zia()||this.wwb(!0)};f.izb=function(b,c){switch(c.Za){case a.a.qb:case a.a.Rb:this.tfa(null)}}},{rp:["PRIM_PPNL"]});
