window.LANSA.addSrc("json",function(e,c,a,b,k){function s(a,b,d){var f=null;if(null===d)f=e.Tr(new c.nwa(a,b));else switch(typeof d){case "object":f=Array.isArray(d)?e.Tr(new c.wja(a,b)):e.Tr(new c.xja(a,b));f.fxb(d);break;case "number":f=e.Tr(new c.owa(a,b,d));break;case "string":f=e.Tr(new c.pwa(a,b,d));break;case "boolean":f=e.Tr(new c.mwa(a,b,d))}return f}e.Eb("PRIM_PCOL");a.kC={Y1a:0,lEb:1,iEb:2,mEb:3,kEb:4,jEb:5};a.kC.H={NULL:a.kC.Y1a,OBJECT:a.kC.lEb,ARRAY:a.kC.iEb,STRING:a.kC.mEb,NUMBER:a.kC.kEb,
BOOLEAN:a.kC.jEb};c.RWb=function(){p.v.call(this);this.pg="";this.PCa=null;this.I_=!1};var p=c.u(c.RWb,c.ed);p.R=function(){this.UOa(null);p.j.R.call(this)};p.Byc=function(){return this.PCa};p.UOa=function(a){this.PCa=a};p.hAc=function(){return this.I_};p.iPa=function(a){this.I_=a};p.Bp=function(){return this.I_?JSON.stringify(this.PCa.gJ()):this.pg};p.AK=function(a){this.pg=a;var b=null,c=null;try{b=JSON.parse(a)}catch(d){}b?(c=s(this,null,b),this.iPa(!0)):this.iPa(!1);this.UOa(c)};p.wjc=function(){this.UOa(e.Tr(new c.wja(this,
null)));this.iPa(!0);return this.PCa};p.xjc=function(){this.UOa(e.Tr(new c.xja(this,null)));this.iPa(!0);return this.PCa};e.tb(c.RWb,"PRIM_WEB","Json",{Va:{Text:{f:p.Bp,i:function(a){this.AK(e.ra(a))}},IsValid:{f:p.hAc},RootItem:{f:p.Byc}},Ec:{CreateRootArray:p.wjc,CreateRootObject:p.xjc},Jf:{Ef:"Text"}});c.m2=function(a,b){t.v.call(this);this.nD=a;this.vCa=b};var t=c.u(c.m2,c.ed);t.D8=function(){return a.kC.Y1a};t.gJ=function(){return null};t.lc=function(){return 0};t.Vd=function(){return null};
t.$v=function(){return null};t.Omd=function(){return this.nD};t.Qxc=function(){return this.vCa};t.iha=function(){return this.vCa?this.vCa.WGb(this):""};t.WGb=function(){return""};t.wi=function(){return this.vCa?this.vCa.g4a(this):-1};t.g4a=function(){return-1};t.y6=function(){throw e.IPc(JSON.stringify(this.gJ()));};t.$Xa=function(){throw e.zxa(JSON.stringify(this.gJ()));};t.QXa=function(){throw e.lgb(JSON.stringify(this.gJ()));};t.mr=function(){return null};t.jj=function(){};e.tb(c.m2,"PRIM_WEB",
"JsonElement",{Va:{Key:{f:t.iha},Index:{f:function(){return this.wi()+1}},Type:{f:function(){return e.Ja(this.D8(),a.kC.H)}},Item:{f:function(a){return this.Vd(e.ra(a))}},ItemAt:{f:function(a){return this.$v(e.aa(a)-1)}},ItemCount:{f:function(){return this.lc()}},ParentItem:{f:t.Qxc}},Ec:{AsString:function(){return this.y6()},AsNumber:function(){return e.Un(this.$Xa())},AsBoolean:function(){return this.QXa()},Remove:function(a){return this.mr(e.ra(a))},RemoveAt:function(a){return this.Lp(e.aa(a)-
1)},RemoveAll:function(){this.jj()}},Jf:{Ef:"Item"},so:{Nn:function(a){return this.$v(e.aa(a)-1)},Vt:function(){return this.lc()}}});c.wja=function(a,b){f.v.call(this,a,b);this.$a=[]};var f=c.u(c.wja,c.m2);f.D8=function(){return a.kC.iEb};f.gJ=function(){for(var a=[],b=0;b<this.$a.length;b++)a.push(this.$a[b].gJ());return a};f.$v=function(a){return 0<=a&&a<this.$a.length?this.$a[a]:null};f.lc=function(){return this.$a.length};f.g4a=function(a){for(var b=0;b<this.$a.length;b++)if(this.$a[b]===a)return b;
return-1};f.fxb=function(a){for(var b=0;b<a.length;b++){var c=s(this.nD,this,a[b]);c&&this.$a.push(c)}};f.S7a=function(){var a=e.Tr(new c.wja(this.nD,this));this.$a.push(a);return a};f.$7a=function(){var a=e.Tr(new c.xja(this.nD,this));this.$a.push(a);return a};f.c8a=function(a){a=e.Tr(new c.pwa(this.nD,this,a));this.$a.push(a);return a};f.Z7a=function(a){a=e.Tr(new c.owa(this.nD,this,a));this.$a.push(a);return a};f.V7a=function(a){a=e.Tr(new c.mwa(this.nD,this,a));this.$a.push(a);return a};f.Y7a=
function(){var a=e.Tr(new c.nwa(this.nD,this));this.$a.push(a);return a};f.Lp=function(a){var b=null;0<=a&&a<this.$a.length&&(b=this.$a[a],this.$a.splice(a,1));return b};f.jj=function(){this.$a=[]};e.tb(c.wja,"PRIM_WEB","JsonArray",{Ec:{InsertArray:f.S7a,InsertObject:f.$7a,InsertNumber:function(a){return this.Z7a(e.lu(a))},InsertString:function(a){return this.c8a(e.ra(a))},InsertBoolean:function(a){return this.V7a(e.Fa(a))},InsertNull:f.Y7a}});c.xja=function(a,b){g.v.call(this,a,b);this.$a={}};var g=
c.u(c.xja,c.m2);g.D8=function(){return a.kC.lEb};g.gJ=function(){var a={},b;for(b in this.$a)a[b]=this.$a[b].gJ();return a};g.Vd=function(a){a=this.$a[a];return a===k?null:a};g.$v=function(a){var b=this.z$();return 0<=a&&a<b.length?this.$a[b[a]]:null};g.lc=function(){return this.z$().length};g.WGb=function(a){for(var b in this.$a)if(this.$a[b]===a)return b};g.g4a=function(a){var b=-1,c;for(c in this.$a)if(b++,this.$a[c]===a)break;return b};g.fxb=function(a){for(var b in a){var c=s(this.nD,this,a[b]);
c&&(this.$a[b]=c)}this.RE()};g.RE=function(){delete this.sD};g.z$=function(){if(this.sD===k){this.sD=[];for(var a in this.$a)this.sD.push(a)}return this.sD};g.S7a=function(a){var b=e.Tr(new c.wja(this.nD,this));this.$a[a]=b;this.RE();return b};g.$7a=function(a){var b=e.Tr(new c.xja(this.nD,this));this.$a[a]=b;this.RE();return b};g.c8a=function(a,b){var d=e.Tr(new c.pwa(this.nD,this,b));this.$a[a]=d;this.RE();return d};g.V7a=function(a,b){var d=e.Tr(new c.mwa(this.nD,this,b));this.$a[a]=d;this.RE();
return d};g.Y7a=function(a){var b=e.Tr(new c.nwa(this.nD,this));this.$a[a]=b;this.RE();return b};g.Z7a=function(a,b){var d=e.Tr(new c.owa(this.nD,this,b));this.$a[a]=d;this.RE();return d};g.mr=function(a){var b=null;this.$a[a]!==k&&(b=this.$a[a],delete this.$a[a],this.RE());return b};g.Lp=function(a){var b=this.z$();return 0<=a&&a<b.length?this.mr(b[a]):null};g.jj=function(){this.$a={};this.RE()};e.tb(c.xja,"PRIM_WEB","JsonObject",{Ec:{InsertArray:function(a){return this.S7a(e.ra(a))},InsertObject:function(a){return this.$7a(e.ra(a))},
InsertNumber:function(a,b){return this.Z7a(e.ra(a),e.lu(b))},InsertString:function(a,b){return this.c8a(e.ra(a),e.ra(b))},InsertBoolean:function(a,b){return this.V7a(e.ra(a),e.Fa(b))},InsertNull:function(a){return this.Y7a(e.ra(a))}}});c.owa=function(a,b,c){n.v.call(this,a,b);this.bb=c};var n=c.u(c.owa,c.m2);n.D8=function(){return a.kC.kEb};n.gJ=function(){return this.bb};n.$Xa=function(){return this.bb};n.y6=function(){return this.bb.toString()};e.tb(c.owa,"PRIM_WEB","JsonNumber",{});c.pwa=function(a,
b,c){l.v.call(this,a,b);this.bb=c};var l=c.u(c.pwa,c.m2);l.D8=function(){return a.kC.mEb};l.gJ=function(){return this.bb};l.y6=function(){return this.bb};l.$Xa=function(){if(isNaN(Number(this.bb)))throw e.zxa(this.bb);return new c.Hi(this.bb)};l.QXa=function(){if("TRUE"==this.bb.toUpperCase())return!0;if("FALSE"==this.bb.toUpperCase())return!1;throw e.lgb(this.bb);};e.tb(c.pwa,"PRIM_WEB","JsonString",{});c.mwa=function(a,b,c){d.v.call(this,a,b);this.bb=c};var d=c.u(c.mwa,c.m2);d.D8=function(){return a.kC.jEb};
d.gJ=function(){return this.bb};d.QXa=function(){return this.bb};d.y6=function(){return this.bb?"true":"false"};e.tb(c.mwa,"PRIM_WEB","JsonBoolean",{});c.nwa=function(a,b){q.v.call(this,a,b)};var q=c.u(c.nwa,c.m2);q.D8=function(){return a.kC.Y1a};q.gJ=function(){return null};e.tb(c.nwa,"PRIM_WEB","JsonNull",{})},{rp:["PRIM_PCOL"]});
