window.LANSA.addSrc("fld",function(e,c,a,b,k){function s(b,c){var e=a.Ea.qk;null!=b&&(b.mthLOAD!=k&&b.mthLOAD(c),e=a.Ea.zb);return e}a.PW={aZb:0,$Yb:1,bZb:2};a.PW.H={DEFAULTITEM:a.PW.aZb,BLANKS:a.PW.$Yb,SHOWVALUE:a.PW.bZb};a.Peb={Efb:0,s0b:15};a.Xwa={Reb:1,oAd:15,WZb:16,nAd:240};c.$ia=function(a){p.v.call(this);this.xv=new c.vKa(a);new c.HQb(this)};var p=c.u(c.$ia,c.LJ);p.wy=function(){return this.xv};p.gh=function(){return this.xv.gh()};p.Tj=function(){return this.xv.Tj()};p.yy=function(){var b=
this.gh(),c=this.Tj();switch(this.bJ()){case a.Pd.l8:case a.Pd.m8:return b-c;case a.Pd.G0:switch(b){case 1:return a.tIc;case 2:return a.qIc;case 4:return a.rIc;case 8:return a.sIc}break;case a.Pd.xGa:switch(b){case 4:return 6;case 8:return 15}}return 0};p.bJ=function(){return this.xv.bJ()};p.Psa=function(){return this.xv.Psa()};p.Nr=function(){return this.xv.Nr()};p.qV=function(){return this.xv.qV()};p.sV=function(){return this.xv.sV()};p.tV=function(){return this.xv.tV()};p.gR=function(){return this.xv.gR()};
p.OB=function(){return this.xv.OB()};p.C8=function(){return this.xv.C8()};p.H3a=function(){return this.xv.H3a()};p.Fxc=function(){switch(this.bJ()){case a.Pd.G0:case a.Pd.l8:case a.Pd.m8:return 0;case a.Pd.gsa:case a.Pd.jsa:case a.Pd.msa:case a.Pd.ksa:case a.Pd.fsa:return"";case a.Pd.hsa:case a.Pd.lsa:case a.Pd.isa:return b.Sk();case a.Pd.Aga:return!1}};p.Ma=function(){if(this.Kn().kl())return e.Cf;switch(this.bJ()){case a.Pd.Aga:return 0!==this.Kn().Ma()}return this.Kn().Ma()};p.Ya=function(c){if(c==
e.Cf)this.Kn().sM();else{switch(this.bJ()){case a.Pd.G0:c=e.aa(c);break;case a.Pd.l8:case a.Pd.m8:0==this.Tj()&&(c=e.aa(c));break;case a.Pd.gsa:case a.Pd.jsa:case a.Pd.msa:case a.Pd.ksa:case a.Pd.fsa:c=e.ra(c);break;case a.Pd.hsa:"string"===typeof c&&(c=b.qZa(c));break;case a.Pd.lsa:"string"===typeof c&&(c=b.EZa(c));break;case a.Pd.isa:"string"===typeof c&&(c=b.sZa(c));break;case a.Pd.Aga:c=e.Fa(c),this.Kn().Ya(c?1:0)}this.Kn().Ya(c)}};p.ffa=function(){return this};p.KXa=function(){this.Ya(this.OB())};
p.Dfa=function(){return new c.$ia(this.xv.yr)};e.$c(c.$ia,"PRIM_FLD",{eK:a.Fu.U6,Va:{Text:{f:function(){return this.Qga()}},Length:{f:p.gh},Decimals:{f:p.Tj},Value:{f:p.Ma,i:p.Ya}},Jf:{Ef:"Value"}});var t=p;t.aD=t.applyDefault=t.KXa;c.HQb=function(b){f.v.call(this,b);this.ip=a.kn.GLa;b=b.wy();switch(b.fwc()){case a.iw.dNb:this.ip|=a.II.KZa;break;case a.iw.cNb:this.ip|=a.II.JZa;break;case a.iw.gNb:this.ip|=a.II.OZa;break;case a.iw.fNb:this.ip|=a.II.Jjc;break;case a.iw.eNb:this.ip|=a.kn.AKc}this.ip=
b.NDc()?this.ip|a.Es.Odb:this.ip|a.Es.kob;b.gLb()&&(this.ip|=a.kn.wwa);b.wJa()&&(this.ip|=a.kn.TYb);b.u9a()&&(this.ip|=a.kn.UYb);b.jEc()&&(this.ip|=a.kn.ywa)};var f=c.u(c.HQb,c.QN);f.gh=function(){return this.kb().gh()};f.Tj=function(){return this.kb().Tj()};f.yy=function(){return this.kb().yy()};f.bJ=function(){return this.kb().bJ()};f.Nr=function(){return this.kb().Nr()};f.qV=function(){return this.kb().qV()};f.sV=function(){return this.kb().sV()};f.tV=function(){return this.kb().tV()};f.gR=function(){return this.kb().gR()};
f.OB=function(){return this.kb().OB()};f.C8=function(){return this.kb().C8()};f.Jl=function(){switch(this.bJ()){case a.Pd.G0:return 8==this.gh()?a.Wa.NA:a.Wa.Nx;case a.Pd.l8:case a.Pd.m8:if(0==this.Tj()&&this.gh()<=a.uIc)return a.Wa.Bw;if(this.gh()<=a.pIc&&this.Tj()<=a.oIc)return a.Wa.MA;break;case a.Pd.xGa:return a.Wa.UC;case a.Pd.M2a:return a.Wa.mAa;case a.Pd.N2a:return a.Wa.nAa}return f.j.Jl.call(this)};f.PKb=function(){var a=this.kb().H3a();a&&(a=new a,a.MR(),this.fb.YVc(a))};f.OGa=function(){switch(this.kb().bJ()){case a.Pd.G0:case a.Pd.l8:case a.Pd.m8:if(0<
this.C8().length)return a.ee.s_a;switch(this.kb().Psa()){case a.ii.H1a:case a.ii.I1a:return a.ee.r_a}return a.ee.KEa;case a.Pd.gsa:case a.Pd.msa:return a.ee.NEa;case a.Pd.jsa:case a.Pd.ksa:return a.ee.MEa;case a.Pd.fsa:return a.ee.T6;case a.Pd.Aga:return a.ee.JEa;case a.Pd.isa:return a.ee.g0;case a.Pd.hsa:return a.ee.CM;case a.Pd.lsa:return a.ee.DM}};f.A1b=function(c,e){var f="";switch(c){case a.pk.Yqa:f=this.kb().Nr();break;case a.pk.h0:f=this.kb().gR();break;case a.pk.Xqa:var g=this.qV(),h=this.sV(),
l=this.tV(),k=b.Jy(g),n=b.Jy(h),p=b.Jy(l);switch(e){case a.x9.d7a:f=g+"\n"+h+"\n"+l;break;case a.x9.sKb:""==k&&(""==n?""==!p&&(g=l,l=""):(g=h,h=l,l=""));f=g;if(0<h.length||0<l.length)f=f+"\n"+h,0<l.length&&(f=f+"\n"+l);break;case a.x9.uKb:f="",0<g.length&&(f=g),0<h.length&&(f=f+(0<f.length?" ":"")+h),0<l.length&&(f=f+(0<f.length?" ":"")+l)}}return f};f.oZa=function(c){var f=null;this.kb().G8()||null!=this.kb().fv()&&(f=b.Dab(c));if(null==f)switch(this.po()){case a.ee.T6:case a.ee.NEa:f=b.GRb(c);break;
case a.ee.LEa:case a.ee.MEa:f=b.QRb(c);break;case a.ee.Bxb:throw 0;case a.ee.CM:case a.ee.DM:case a.ee.g0:b.sKa==k&&e.Eb("PRIM_DTIM");f=a.dd.A1a;f=b.sKa(c,this.Jl(),f,void 0,void 0);break;case a.ee.s_a:b.JQb==k&&e.Eb("PRIM_FMTN");f=b.JQb(c,this);break;case a.ee.zxb:case a.ee.KEa:f=this.kb().bJ()!=a.Pd.G0?!0:!1;switch(this.kb().Psa()){case a.ii.iDb:f=f?b.Xt(c,a.xc.Awa):b.nw(c,a.xc.Awa);break;case a.ii.jDb:f=f?b.Xt(c,a.xc.Bwa):b.nw(c,a.xc.Bwa);break;case a.ii.kDb:f=f?b.Xt(c,a.xc.Oja):b.nw(c,a.xc.Oja);
break;case a.ii.lDb:f=f?b.Xt(c,a.xc.Cwa):b.nw(c,a.xc.Cwa);break;case a.ii.mDb:f=f?b.Xt(c,a.xc.Dwa):b.nw(c,a.xc.Dwa);break;case a.ii.nDb:f=f?b.Xt(c,a.xc.Ewa):b.nw(c,a.xc.Ewa);break;case a.ii.oDb:f=f?b.Xt(c,a.xc.Fwa):b.nw(c,a.xc.Fwa);break;case a.ii.pDb:f=f?b.Xt(c,a.xc.Gwa):b.nw(c,a.xc.Gwa);break;case a.ii.qDb:f=f?b.Xt(c,a.xc.Hwa):b.nw(c,a.xc.Hwa);break;case a.ii.uDb:f=f?b.Xt(c,a.xc.Lwa):b.nw(c,a.xc.Lwa);break;case a.ii.rDb:f=f?b.Xt(c,a.xc.Iwa):b.nw(c,a.xc.Iwa);break;case a.ii.xDb:f=f?b.Xt(c,a.xc.Mwa):
b.nw(c,a.xc.Mwa);break;case a.ii.sDb:f=f?b.Xt(c,a.xc.Jwa):b.nw(c,a.xc.Jwa);break;case a.ii.yDb:f=f?b.Xt(c,a.xc.Nwa):b.nw(c,a.xc.Nwa);break;case a.ii.tDb:f=f?b.Xt(c,a.xc.Kwa):b.nw(c,a.xc.Kwa);break;case a.ii.BDb:f=f?b.Xt(c,a.xc.Owa):b.nw(c,a.xc.Owa);break;case a.ii.DDb:for(var g="",l=0;l<this.yy();l++)g+="#";f=f?b.cJc(c,g):b.bJc(c,g);break;case a.ii.$Fa:case a.ii.wDb:if(!f){f=b.nw(c,a.xc.Xfa);break}f=f?b.Xt(c,a.xc.Pja):b.nw(c,a.xc.Pja);break;default:f=f?b.Xt(c,a.xc.Pja):b.nw(c,a.xc.Pja)}break;case a.ee.r_a:switch(this.kb().Psa()){case a.ii.H1a:f=
b.tKa(c,a.LQ.B_a);break;case a.ii.I1a:f=b.tKa(c,a.LQ.C_a);break;default:f=b.tKa(c,a.LQ.Vxb)}break;case a.ee.JEa:f=b.$Ic(c)}return f};f.pZa=function(){var c=this.Jl();return c==a.Wa.Bw?(b.QQb==k&&e.Eb("PRIM_FMTN"),b.QQb(this.fb)):c==a.Wa.Nx?(b.MQb==k&&e.Eb("PRIM_FMTN"),b.MQb(this.fb)):c==a.Wa.NA?(b.OQb==k&&e.Eb("PRIM_FMTN"),b.OQb(this.fb)):f.j.pZa.call(this)};f.oeb=function(c){var e=c[1],e=b.gJc(c[0]);c[1]=e;c[2]=0;return a.Ea.zb};c.SQb=function(b){g.v.call(this);this.Osb=a.Peb.Efb;this.Kbc=b;this.Ida=
null;this.ho=[]};var g=c.u(c.SQb,c.ed);g.rb=function(){this.Ida&&this.Ida.sb()};g.R=function(){this.zwb();g.j.R.call(this)};g.nqd=function(){return this.ho};g.IXc=function(b){this.OHa()!=b&&(this.Osb=this.Osb&~a.Peb.s0b|b,this.m(a.a.h))};g.OHa=function(){return this.Osb&a.Peb.s0b};g.G1=function(){this.Kbc&&(this.Ida=e.he(this.Kbc),this.Ida.va(),s(this.Ida,this))};g.ZKb=function(a,b){a.Ob=this;a.ya(this,this.inc);b&&a.MXc();this.c9b(a);this.ho.push(a)};g.nPc=function(a){a.Ob=null;a.wa(this);this.ho.splice(this.ho.indexOf(a),
1)};g.cG=function(b,c,e){var f=a.Ea.qk,h=this.C9a(b);null==h&&(h=this.P_a());if(h){for(h=this.ho.indexOf(h);0<c;c--)if(0>--h)if(e)h=this.ho.length-1;else{f=a.Ea.QI;break}0<=h&&(h=this.ho[h],f=h.DI(b))}return f};g.DG=function(b,c,e){var f=a.Ea.qk,h=this.C9a(b);null==h&&(h=this.P_a());if(h){for(h=this.ho.indexOf(h);0<c;c--)if(++h>=this.ho.length)if(e)h=0;else{f=a.Ea.QI;break}h<this.ho.length&&(h=this.ho[h],f=h.DI(b))}return f};g.P_a=function(){for(var a=null,b=this.ho,c,e=0;e<b.length&&null!=(c=b[e]);e++)if(c.R0()){a=
c;break}null==a&&0<this.ho.length&&(a=this.ho[0]);return a};g.lo=function(){return this.ho.length()};g.Nn=function(a){return this.ho[a]};g.C9a=function(b){var e=new c.Kab;b.T_(e);b=null;for(var f=this.ho,g,h=0;h<f.length&&null!=(g=f[h]);h++)if(g.VH.xEa(e)==a.Zc.Rj){b=g;break}null==b&&this.OHa()==a.PW.aZb&&(b=this.P_a());return b};g.P1=function(a){for(var c=null,e=this.ho,f,h=0;h<e.length&&null!=(f=e[h]);h++)if(b.pC(f.Nu(),a)){c=f;break}return c};g.AFc=function(a,c){var e=null,f=null,h=this.ho,g=0;
if(null!=c)for(g=0;g<h.length&&null!=(f=h[g])&&f!=c;g++);for(;g<h.length&&null!=(f=h[g]);g++){var l=f.Nu();if(b.$Sb(l,a)){e=f;break}}if(null==e&&null!=c)for(g=0;g<h.length&&null!=(f=h[g])&&f!=c;g++)if(l=f.Nu(),b.$Sb(l,a)){e=f;break}return e};g.c9b=function(a){a.R0()||(a=null);for(var b,c=this.ho,e=0;e<c.length&&null!=(b=c[e]);e++)b.R0()&&b!=a&&(null!=a?b.RNa(!1):a=b)};g.bgb=function(){var b=a.Ea.zb;this.Ida&&(b=s(this.Ida,this));return b};g.Hkc=function(){this.zwb()};g.Gkc=function(b,c,f,g){f=f!==
k?f:!1;g=g!==k?g:null;var h=e.he("PRIM_PKIT");h.va(this);h.qr(c);h.LZc(b);h.RNa(f);g&&h.Vc(g);this.ZKb(h,!0);return a.Ea.zb};g.zwb=function(){for(var a;null!=(a=this.ho.shift());)a.Ia(null),a.$Lb()&&(a.EN()?a.sb(this,!0):a.ko());this.ho=[]};g.inc=function(){this.m(a.a.h,a.ae.zIc)};e.$c(c.SQb,"PRIM_PKLT",{Va:{NoMatchAction:{f:function(){return e.Ja(this.OHa(),a.PW.H)},i:function(b){this.IXc(e.Ba(b,a.PW.H))}},DefaultPicklist:{f:function(){return!0},i:function(){}}},Ec:{Add:g.Gkc,RemoveAll:g.Hkc}});
c.TQb=function(){n.v.call(this);this.Ob=null;this.bb=this.ib="";this.TT=0;this.VH=new c.Kab;this.VH.zvb()};var n=c.u(c.TQb,c.ed);n.R=function(){this.Vc(null);this.Ia(null);n.j.R.call(this)};n.zc=function(){return this.za};n.Vc=function(b){this.za!=b&&(null!=this.za&&(this.za.wa(this,this.Dl),this.za.sb()),this.za=b,null!=this.za&&(this.za.va(),this.za.ya(this,this.Dl)),this.m(a.a.h))};n.Z=function(){return this.Ob};n.Ia=function(b){this.Ob!=b&&(this.Ob&&this.Ob.nPc(this),b&&b.ZKb(this,!1),this.m(a.a.h))};
n.Nu=function(){return this.ib};n.qr=function(b){this.ib!=b&&(this.ib=b,this.m(a.a.h,a.ae.XJa))};n.Ma=function(){return this.VH.bb};n.Ya=function(b){this.VH.bb!=b&&(this.VH.rfc(b),this.m(a.a.h))};n.fmd=function(){return this.VH};n.SIb=function(){return e.ra(this.Ma())};n.LZc=function(b){this.SIb()!=b&&(this.VH.Cob(b),this.m(a.a.h))};n.R0=function(){return 0!=(this.TT&a.Xwa.Reb)};n.RNa=function(b){this.R0()!=b&&(this.TT=b?this.TT|=a.Xwa.Reb:this.TT&=~a.Xwa.Reb,this.Ob&&this.Ob.c9b(this),this.m(a.a.h))};
n.MXc=function(){!0!=this.$Lb()&&(this.TT=this.TT|=a.Xwa.WZb,this.m(a.a.h))};n.DI=function(a){return a.rQ(this.VH)};n.Co=function(a){return a.m9b(this.VH)};n.$Lb=function(){return 0!=(this.TT&a.Xwa.WZb)};e.$c(c.TQb,"PRIM_PKIT",{Va:{Value:{f:n.Ma,i:n.Ya},Caption:{f:n.Nu,i:function(a){this.qr(e.ra(a))}},Image:{f:n.zc,i:n.Vc},Default:{f:n.R0,i:function(){}},Parent:{f:n.Z,i:n.Ia}}});c.zRb=function(a){l.v.call(this,a)};var l=c.u(c.zRb,c.W9);l.$W=function(){return a.Ea.zb};l.DN=function(b){var c=b[0],e=
b[1],f=b[2],h=b[3],g=b[4],l=a.Ea.Ff,k=this.kb().D4,n=null,p,n=k.P1(c);0<e&&(p=c.substr(0,e));if(n=k.AFc(p+f,n))l=a.Ea.zb,h=1,c=n.Nu(),this.gc().SC(n.SIb());b[0]=c;b[1]=e;b[2]=f;b[3]=h;b[4]=g;return l};l.Uwa=function(b){var c=a.Ea.qk,e=this.kb().D4;e&&(c=(b=e.P1(b))?b.Co(this.gc()):a.Ea.Ff);return c};l.ox=function(b){var c="",e=a.Ea.qk,f=this.kb().D4;if(f)if(e=f.C9a(this.gc()))c=e.Nu(),0==c.length&&this.gc().dX(c),e=a.Ea.zb;else switch(f.OHa()){case a.PW.$Yb:c="";e=a.Ea.zb;break;case a.PW.bZb:c=this.gc().xj();
e=a.Ea.zb;break;default:e=a.Ea.Ff}b[0]=c;return e}});
