window.LANSA.addSrc("gpbx",function(e,c,a,b){a.Rpc={yLd:0,xLd:9,F$c:6,zLd:5,ALd:10};a.sAc={Urc:0};c.nUb=function(){k.v.call(this);this.brb=a.Rpc.F$c;this.yF=a.sAc.Urc;this.QF=new c.ga;this.Kc=this.Kc|a.Tb.N9|a.Tb.bva|a.Tb.O9a|a.Tb.mC|a.Tb.XR|a.Tb.lC;this.Vg=this.Vg|a.Jh.NN|a.Jh.mW;this.Ze(!1)};var k=c.u(c.nUb,c.fS);k.Ag=function(){return c.zXb};k.aGd=function(b){this.brb!=b&&(this.brb=b,this.m(a.a.h),this.Ut())};k.mnd=function(){return this.brb};k.Uo=function(a){k.j.Uo.call(this,a);this.KLc()};k.znb=
function(){if(this.Mb()){var a=this.Sd(),a=Math.abs(a.Ra()),c=this.we();this.td();this.td();c.Sa(c.O()+a);""==this.Db()?(c.Oa(c.O()),c.xa(a)):(this.Db(),c.Oa(c.O()+this.iV()),c.xa(this.Kga()),c.Oa(c.pa+a));b.Ro(this.QF,c)||(this.QF=c,this.Cb());this.Uo(!0)}};k.oe=function(a){a.Ua(a.L()+this.QF.ba());a.Sa(a.O()+4);a.Oa(a.pa-4);a.xa(a.na-4);k.j.oe.call(this,a)};k.BOc=function(a,b,c){a.Ua(a.L()+this.QF.ba());a.Sa(a.O()+4);a.Oa(a.pa-4);a.xa(a.na-4);k.j.BOc.call(this,a,b,c)};k.Pi=function(){k.j.Pi.call(this);
this.yd(a.W.Fx)};k.Uc=function(){var b=this.yJ()||this.Wj()&&(this.iW()||this.MN());this.TF(a.Tb.DJ,b);k.j.Uc.call(this)};k.wC=function(a){var b=!1,b=a.Qd().QMa(this,this.ea.Mh,this.iW(),this.MN(),a);!1==b&&k.j.wC.call(this,a)};k.sS=function(a){var b=!1;null!=a.Qd()&&a.Ca().Wj()&&(b=a.Qd().RMa(this,this.ea.Mh,a,this.iW(),this.MN()));!1==b&&k.j.sS.call(this,a)};k.Yd=function(b){""==b[1]&&(b[1]=a.fOb);k.j.Yd.call(this,b)};k.KLc=function(){var a=this.we(),a=this.Kz(a,null),c=this.we();c.Ua(c.L()+this.QF.ba()/
2+1);c.Sa(c.O()+2);c.Oa(c.pa-2);c.xa(c.na-2);var e=this.Na().gb(),g=this.Db();b.Fd[e].ng(g,c,this.QF);b.ka(a)};k.nq=k[a.W.BE]=function(a){this.znb();k.j.nq.call(this,a)};k.Is=k[a.W.AE]=function(){k.j.Is.call(this);this.znb()};k.dE=k[a.W.Fx]=function(){this.znb();this.Ut()};k.Enc=k[a.W.s$a]=function(){this.Jg()};e.$c(c.nUb,"PRIM_GPBX",{Va:{Caption:{f:k.Db,i:function(a){this.Wb(e.ra(a))}},ThemeStyle:{f:function(){return e.Ja(this.pJ(),a.kt.H)},i:function(b){this.Aya(e.Ba(b,a.kt.H))}}}});c.zXb=function(a){s.v.call(this,
a);this.ib=this.zSa=this.xAa=this.Nd=this.Cc=null};var s=c.u(c.zXb,c.n2);s.Ve=function(a,b){var c=null;s.j.Ve.call(this,a,b);this.zSa=4;this.Cc=document.createElement("div");this.Nd=document.createElement("div");this.xAa=document.createElement("div");this.ib=document.createElement("span");this.w.appendChild(this.Cc);this.w.appendChild(this.Nd);this.w.appendChild(this.xAa);this.w.appendChild(this.ib);this.P7a(this.Cc,this.zSa);this.P7a(this.Nd,0);this.P7a(this.xAa,0);c=this.Cc.style;c.borderTopWidth=
"0px";c=this.Nd.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.xAa.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.ib.style;c.position="absolute";c.whiteSpace="nowrap";c.cursor="inherit";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";return this.w};s.P7a=function(a,b){var c=a.style;c.position="absolute";c.overflowX="hidden";c.overflowY=
"hidden";c.whiteSpace="nowrap";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.outline="none";c.background="rgba(0,0,0,0)";c.borderTopWidth="1px";c.borderBottomWidth="1px";c.borderLeftWidth="1px";c.borderRightWidth="1px";c.borderTopLeftRadius=b+"px";c.webkitBorderTopLeftRadius=b+"px";c.borderTopRightRadius=b+"px";c.webkitBorderTopRightRadius=b+"px";c.borderBottomLeftRadius=b+"px";c.webkitBorderBottomLeftRadius=b+"px";c.borderBottomRightRadius=
b+"px";c.webkitBorderBottomRightRadius=b+"px"};s.ng=function(a,b,c){var e=this.Cc.style;e.left=b.O()+"px";e.top=b.L()+"px";e.width=b.$()+"px";e.height=b.ba()+"px";e.borderColor=this.uk();e=this.Nd.style;e.left=b.O()+this.zSa-1+"px";e.top=b.L()+"px";e.width=c.O()-b.O()+"px";e.height="1px";e.borderColor=this.uk();e=this.xAa.style;e.left=c.pa+2+"px";e.top=b.L()+"px";e.width=b.pa-this.zSa-c.pa+"px";e.height="1px";e.borderColor=this.uk();e=this.ib.style;e.left=c.O()+7+"px";e.top=c.L()+2+"px";e.height=
c.ba()+"px";e.width=c.$()+"px";this.ib.textContent=a}});
