LANSA.addComponent({id:"DF_HISTHO",ot:"rp",tp:"Reusable Part",de:"\\OC=Demonstration History Tab",tl:14020001},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")){cL=l.gCL();}var Fd={F1:{nm:"STD_INT",ft:"I",ln:4,dc:0,ec:"J",lb:{"ENG":"Std Integer","FRA":"?","JPN":"?"}[cL],h1:{"ENG":"Standard","FRA":"?","JPN":"?"}[cL],h2:{"ENG":"Integer","FRA":"?","JPN":"?"}[cL],h3:{"ENG":"Field","FRA":"?","JPN":"?"}[cL],de:{"ENG":"Standard Integer field","FRA":"?","JPN":"?"}[cL],dv:0,ia:["FE","RB"]
}};var cO=l.rC(oI,{an:"VF_AC010O",fd:Fd,mt:{uExecute:{ps:{"GotoFreeState":{pt:"io"},"SwitchCallerReference":{pt:"i"}}},AddGraphMaxium:{ps:{"Value":{pt:"i"}}},GetMonth:{ps:{"For":{pt:"i"}}}},co:function(){cO.aN.call(this);this.aF("DF_HISTHO",Fd);var C0=this.cR("CUSTOMERINFORMATION","PRIM_LABL");var C1=this.cR("PIECHART","DF_T49PCO");var C2=this.cR("BARCHART","DF_T49BCO");var C3=this.cR("ATTACHLAYOUT1","PRIM_ATLM");var C4=this.cR("ATTACHITEM1","PRIM_ATLI");var C5=this.cR("ATTACHITEM2","PRIM_ATLI");
var C6=this.cR("ATTACHITEM3","PRIM_ATLI");var C7=this.cA("DF_RAMPCV","DF_RAMPCV");var C8=this.cR("RANDOMGRAPHNUMBERS","PRIM_ACOL");var C9=this.cR("PIECHART_INITIALIZED","PRIM_BOLN");var C10=this.cR("BARCHART_INITIALIZED","PRIM_BOLN");C0.setDisplayPosition(1);C0.setEllipses("WORD");C0.setHeight(25);C0.setLeft(4);C0.setParent(this);C0.setTabPosition(2);C0.setTabStop(false);C0.setTop(4);C0.setWidth(721);C0.setAlignment("CENTER");C0.setVerticalAlignment("CENTER");C0.iC();C1.setDisplayPosition(3);C1.setHeight(272);
C1.setLeft(0);C1.setParent(this);C1.setTabPosition(3);C1.setTabStop(false);C1.setTop(33);C1.setWidth(297);C1.iC();C2.setDisplayPosition(2);C2.setHeight(272);C2.setLeft(297);C2.setParent(this);C2.setTabPosition(1);C2.setTabStop(false);C2.setTop(33);C2.setWidth(432);C2.iC();C3.iC();C4.setManage(C0);C4.setParent(C3);C4.setAttachment("TOP");C4.setMarginBottom(4);C4.setMarginLeft(4);C4.setMarginRight(4);C4.setMarginTop(4);C4.iC();C5.setParent(C3);C5.setAttachment("LEFT");C5.setManage(C1);C5.iC();C6.setParent(C3);
C6.setAttachment("CENTER");C6.setManage(C2);C6.iC();if((C7!=null)&&(C7.iI()==false)){C7.iC();}C8.setCollects("STD_INT");C8.iC();C9.iC();C10.iC();C1.aH("INITIALIZE",this,e2);C2.aH("INITIALIZE",this,e1);this.REF.AVLOCALTIMER.aH("TICK",this,e3);this.setHeight(305);this.setWidth(729);this.setLayoutManager(C3);}});var cA=cO.aN.prototype;cO.mthUEXECUTE=function(p0,p1){var m=this.REF,r=l.mR(this,cO,"uExecute",47);var P0=r.cP("GOTOFREESTATE","PRIM_BOLN");var P1=r.cPD("SWITCHCALLERREFERENCE");P0.set(p0.get());
P1=p1;var C0=r.cD("C0");r.ln=47;{r.ln=52;cA.mthUEXECUTE.call(this,P0,P1);r.ln=56;C0=r.sR("C0",this.REF.AVLISTMANAGER.getCURRENTINSTANCE());r.ln=60;this.setVisible((C0!=null));r.ln=63;if(this.getVisible()){r.ln=66;if(this.REF.AVFRAMEWORKMANAGER.getAVSMALLSCREEN()){r.ln=67;this.setAVTITLEBARCAPTION(C0.getAVVISUALID1().get());}r.ln=71;m.CUSTOMERINFORMATION.setCaption(l.add(l.cat(C0.getAVVISUALID1().get()," - "),C0.getAVVISUALID2().get()));r.ln=75;m.RANDOMGRAPHNUMBERS.mthREMOVEALL();r.ln=77;for(var i1=1,s1=1,t1=l.tI(6);(((s1>=0)&&(i1<=t1))||((s1<0)&&(i1>=t1)));i1+=s1)
{r.ln=78;this.mthADDGRAPHMAXIUM(50);}r.ln=81;for(var i1=1,s1=1,t1=l.tI(12);(((s1>=0)&&(i1<=t1))||((s1<0)&&(i1>=t1)));i1+=s1){r.ln=82;this.mthADDGRAPHMAXIUM(15000);}r.ln=86;m.DF_RAMPCV.ref.mthGETRANDOMVALUESLIST(m.RANDOMGRAPHNUMBERS);r.ln=89;this.REF.AVLOCALTIMER.setInterval(400);r.ln=92;P0.set(false);}p0.set(P0.get());}r.ln=96;r.e();};function e1(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#BarChart.Initialize",99);r.ln=99;{r.ln=101;m.BARCHART_INITIALIZED.set(true);}r.ln=103;r.e();};function e2(sender,Ps)
{var m=this.REF,r=l.eR(this,cO,"#PieChart.Initialize",106);r.ln=106;{r.ln=108;m.PIECHART_INITIALIZED.set(true);}r.ln=110;r.e();};function e3(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#AVLOCALTIMER.Tick",113);var C0=r.cF("INDEX",Fd.F1.Dc);var C1=r.cF("MONTH",Fd.F1.Dc);C0.iC();C1.iC();r.ln=113;{r.ln=119;this.REF.AVLOCALTIMER.setInterval(0);r.ln=123;if(l.or(l.b.Not(m.BARCHART_INITIALIZED.get()),l.b.Not(m.PIECHART_INITIALIZED.get()))){r.ln=125;this.REF.AVLOCALTIMER.setInterval(100);}else{r.ln=130;m.PIECHART.mthCLEAR();
r.ln=131;m.PIECHART.setTITLE("Bi-Monthly Yield Spread YTD");r.ln=132;C0.set(0);r.ln=133;for(var i1=1,s1=1,t1=l.tI(6);(((s1>=0)&&(i1<=t1))||((s1<0)&&(i1>=t1)));i1+=s1){r.ln=134;C0.set(l.add(C0.get(),1));r.ln=135;m.PIECHART.mthINSERT(m.RANDOMGRAPHNUMBERS.get(C0.get()).get(),l.cat("Period ",l.n.AsString(C0.get())));}r.ln=139;m.BARCHART.mthCLEAR();r.ln=140;m.BARCHART.setTITLE("Last Year Comparable Sales");r.ln=141;C0.set(6);r.ln=142;C1.set(0);r.ln=143;for(var i1=1,s1=1,t1=l.tI(12);(((s1>=0)&&(i1<=t1))||((s1<0)&&(i1>=t1)));i1+=s1)
{r.ln=144;C0.set(l.add(C0.get(),1));r.ln=145;C1.set(l.add(C1.get(),1));r.ln=146;m.BARCHART.mthINSERT(m.RANDOMGRAPHNUMBERS.get(C0.get()).get(),cO.mthGETMONTH.call(this,C1.get()));}r.ln=150;this.mthAVGOTOFREESTATE();}}r.ln=154;r.e();};cO.mthADDGRAPHMAXIUM=function(p0){var m=this.REF,r=l.mR(this,cO,"AddGraphMaxium",158);var P0=r.cPF("VALUE",Fd.F1.Dc);P0.set(p0);r.ln=158;{r.ln=160;m.RANDOMGRAPHNUMBERS.mthINSERT(P0);}r.ln=161;r.e();};cO.mthGETMONTH=function(p0){var r=l.mR(this,cO,"GetMonth",164);var P0=r.cPF("FOR",Fd.F1.Dc);
var P1=r.cP("MONTH","PRIM_ALPH");P0.set(p0);r.ln=164;{r.ln=168;{var v1=P0.get();if(r.ln=169,l.n.eq(v1,1)){r.ln=170;P1.set("Jan");}else if(r.ln=171,l.n.eq(v1,2)){r.ln=172;P1.set("Feb");}else if(r.ln=173,l.n.eq(v1,3)){r.ln=174;P1.set("Mar");}else if(r.ln=175,l.n.eq(v1,4)){r.ln=176;P1.set("Apr");}else if(r.ln=177,l.n.eq(v1,5)){r.ln=178;P1.set("May");}else if(r.ln=179,l.n.eq(v1,6)){r.ln=180;P1.set("Jun");}else if(r.ln=181,l.n.eq(v1,7)){r.ln=182;P1.set("Jul");}else if(r.ln=183,l.n.eq(v1,8)){r.ln=184;P1.set("Aug");
}else if(r.ln=185,l.n.eq(v1,9)){r.ln=186;P1.set("Sep");}else if(r.ln=187,l.n.eq(v1,10)){r.ln=188;P1.set("Oct");}else if(r.ln=189,l.n.eq(v1,11)){r.ln=190;P1.set("Nov");}else if(r.ln=191,l.n.eq(v1,12)){r.ln=192;P1.set("Dec");}else{r.ln=194;P1.set("Unk");}r.ln=195;}}r.ln=197;return r.rV(P1.get());};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"STD_INT"});}cO.srAVLISTMANAGER=function(rn){cA.srAVLISTMANAGER.call(this,rn);};cO.srAVFRAMEWORKMANAGER=function(rn){cA.srAVFRAMEWORKMANAGER.call(this,rn);
};},{rc:["VF_AC010O","DF_T49PCO","DF_T49BCO","DF_RAMPCV"],rp:["PRIM_LABL","PRIM_ATLM","PRIM_ATLI","PRIM_ACOL","PRIM_BOLN","PRIM_FLD"],dc:["VF_LM003O"]});