LANSA.addComponent({id:"DF_T69CTO",ot:"rp",tp:"Reusable Part",de:"\\OC=Print Widget Container",tl:14020001},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")){cL=l.gCL();}var Fd={F1:{nm:"STD_INT",ft:"I",ln:4,dc:0,ec:"J",lb:{"ENG":"Std Integer","FRA":"?","JPN":"?"}[cL],h1:{"ENG":"Standard","FRA":"?","JPN":"?"}[cL],h2:{"ENG":"Integer","FRA":"?","JPN":"?"}[cL],h3:{"ENG":"Field","FRA":"?","JPN":"?"}[cL],de:{"ENG":"Standard Integer field","FRA":"?","JPN":"?"}[cL],dv:0,ia:["FE","RB"]}
};var cO=l.rC(oI,{an:"PRIM_OBJT",fd:Fd,mt:{uInitialize:{ps:{"ContainerWidth":{pt:"i"},"ContainerHeight":{pt:"i"},"ContainerTitle":{pt:"i"},"FontName":{pt:"i"},"FontSize":{pt:"i"},"FontColor":{pt:"i"},"getHeight":{pt:"o"},"getWidth":{pt:"o"}}},uAddPage:{ps:{"LandscapeMode":{pt:"i"}}},uInsertText:{ps:{"Text":{pt:"i"},"Align":{pt:"i"},"FromLeft":{pt:"i"},"FromTop":{pt:"i"},"FontName":{pt:"i"},"FontSize":{pt:"i"},"FontColor":{pt:"i"},"Underline":{pt:"i"},"Bold":{pt:"i"},"Italic":{pt:"i"}}},uInsertImage:
{ps:{"Width":{pt:"i"},"Height":{pt:"i"},"FromLeft":{pt:"i"},"FromTop":{pt:"i"},"SourcePath":{pt:"i"},"Name":{pt:"i"}}},uInsertLine:{ps:{"Length":{pt:"i"},"FromLeft":{pt:"i"},"ToLeft":{pt:"i"},"FromTop":{pt:"i"},"ToTop":{pt:"i"},"Thickness":{pt:"i"},"Color":{pt:"i"},"Repeat":{pt:"i"},"Spacing":{pt:"i"}}},uInsertRectangle:{ps:{"Align":{pt:"i"},"Width":{pt:"i"},"Height":{pt:"i"},"FromLeft":{pt:"i"},"FromTop":{pt:"i"},"Thickness":{pt:"i"},"Color":{pt:"i"},"BackColor":{pt:"i"}}},uDrawBarcode:{ps:{"Data":
{pt:"i"},"Format":{pt:"i"},"Height":{pt:"i"},"LineWidth":{pt:"i"},"FromLeft":{pt:"i"},"FromTop":{pt:"i"},"FontName":{pt:"i"},"FontSize":{pt:"i"}}},uShow:{ps:{"PrintPreview":{pt:"i"}}},uClearPages:{},uTerminate:{}},ev:{uPrintWidgetInitialized:{}},co:function(){cO.aN.call(this);this.aF("DF_T69CTO",Fd);var C0=this.cR("REPORT","DF_T69RPO");C0.iC();C0.aH("INITIALIZE",this,e1);}});function e1(sender,Ps){var r=l.eR(this,cO,"#Report.Initialize",24);r.ln=24;{r.ln=26;this.fE("UPRINTWIDGETINITIALIZED");}r.ln=28;
r.e();};cO.mthUINITIALIZE=function(p0,p1,p2,p3,p4,p5,p6,p7){var m=this.REF,r=l.mR(this,cO,"uInitialize",31);var P0=r.cPF("CONTAINERWIDTH",Fd.F1.Dc);var P1=r.cPF("CONTAINERHEIGHT",Fd.F1.Dc);var P2=r.cP("CONTAINERTITLE","PRIM_ALPH");var P3=r.cP("FONTNAME","PRIM_ALPH");var P4=r.cP("FONTSIZE","PRIM_ALPH");var P5=r.cP("FONTCOLOR","PRIM_ALPH");var P6=r.cPF("GETHEIGHT",Fd.F1.Dc);var P7=r.cPF("GETWIDTH",Fd.F1.Dc);P0.set((p0===u)?(810):(p0));P1.set((p1===u)?(600):(p1));P2.set((p2===u)?("Report Preview"):(p2));
P3.set((p3===u)?("Arial"):(p3));P4.set((p4===u)?("12pt"):(p4));P5.set((p5===u)?("black"):(p5));r.ln=31;{r.ln=47;m.REPORT.mthUINITIALIZE(P2.get(),P0.get(),P1.get(),P3.get(),P4.get(),P5.get());r.ln=49;P6.set(m.REPORT.getUHEIGHT());r.ln=50;P7.set(m.REPORT.getUWIDTH());if(p6!==u){p6.set(P6.get());}if(p7!==u){p7.set(P7.get());}}r.ln=52;r.e();};cO.mthUADDPAGE=function(p0){var m=this.REF,r=l.mR(this,cO,"uAddPage",54);var P0=r.cP("LANDSCAPEMODE","PRIM_BOLN");P0.set((p0===u)?(false):(p0));r.ln=54;{r.ln=58;
m.REPORT.mthUADDPAGE();}r.ln=60;r.e();};cO.mthUINSERTTEXT=function(p0,p1,p2,p3,p4,p5,p6,p7,p8,p9){var m=this.REF,r=l.mR(this,cO,"uInsertText",62);var P0=r.cP("TEXT","PRIM_ALPH");var P1=r.cP("ALIGN","PRIM_ALPH");var P2=r.cPF("FROMLEFT",Fd.F1.Dc);var P3=r.cPF("FROMTOP",Fd.F1.Dc);var P4=r.cP("FONTNAME","PRIM_ALPH");var P5=r.cP("FONTSIZE","PRIM_ALPH");var P6=r.cP("FONTCOLOR","PRIM_ALPH");var P7=r.cP("UNDERLINE","PRIM_BOLN");var P8=r.cP("BOLD","PRIM_BOLN");var P9=r.cP("ITALIC","PRIM_BOLN");P0.set(p0);
P1.set((p1===u)?("coords"):(p1));P2.set((p2===u)?(0):(p2));P3.set((p3===u)?(0):(p3));P4.set((p4===u)?(""):(p4));P5.set((p5===u)?(""):(p5));P6.set((p6===u)?("black"):(p6));P7.set((p7===u)?(false):(p7));P8.set((p8===u)?(false):(p8));P9.set((p9===u)?(false):(p9));r.ln=62;{r.ln=75;m.REPORT.mthUINSERTTEXT(P0.get(),P4.get(),P5.get(),P6.get(),P1.get(),P2.get(),P3.get(),P7.get(),P8.get(),P9.get());}r.ln=77;r.e();};cO.mthUINSERTIMAGE=function(p0,p1,p2,p3,p4,p5){var m=this.REF,r=l.mR(this,cO,"uInsertImage",79);
var P0=r.cPF("WIDTH",Fd.F1.Dc);var P1=r.cPF("HEIGHT",Fd.F1.Dc);var P2=r.cPF("FROMLEFT",Fd.F1.Dc);var P3=r.cPF("FROMTOP",Fd.F1.Dc);var P4=r.cP("SOURCEPATH","PRIM_ALPH");var P5=r.cP("NAME","PRIM_ALPH");P0.set((p0===u)?(0):(p0));P1.set((p1===u)?(0):(p1));P2.set((p2===u)?(0):(p2));P3.set((p3===u)?(0):(p3));P4.set((p4===u)?("/"):(p4));P5.set(p5);r.ln=79;{r.ln=88;m.REPORT.mthUINSERTIMAGE(P2.get(),P3.get(),P0.get(),P1.get(),l.cat(l.s.Trim(P4.get()),P5.get()));}r.ln=90;r.e();};cO.mthUINSERTLINE=function(p0,p1,p2,p3,p4,p5,p6,p7,p8)
{var m=this.REF,r=l.mR(this,cO,"uInsertLine",92);var P0=r.cPF("LENGTH",Fd.F1.Dc);var P1=r.cPF("FROMLEFT",Fd.F1.Dc);var P2=r.cPF("TOLEFT",Fd.F1.Dc);var P3=r.cPF("FROMTOP",Fd.F1.Dc);var P4=r.cPF("TOTOP",Fd.F1.Dc);var P5=r.cPF("THICKNESS",Fd.F1.Dc);var P6=r.cP("COLOR","PRIM_ALPH");var P7=r.cPF("REPEAT",Fd.F1.Dc);var P8=r.cPF("SPACING",Fd.F1.Dc);P0.set((p0===u)?(0):(p0));P1.set((p1===u)?(0):(p1));P2.set((p2===u)?(0):(p2));P3.set((p3===u)?(0):(p3));P4.set((p4===u)?(-9999):(p4));P5.set((p5===u)?(1):(p5));
P6.set((p6===u)?("black"):(p6));P7.set((p7===u)?(1):(p7));P8.set((p8===u)?(1):(p8));r.ln=92;{r.ln=104;if(l.n.eq(P4.get(),-9999)){r.ln=105;P4.set(P3.get());}r.ln=108;m.REPORT.mthUINSERTLINE(P1.get(),P2.get(),P3.get(),P4.get(),P5.get(),P6.get(),P0.get(),P7.get(),P8.get());}r.ln=110;r.e();};cO.mthUINSERTRECTANGLE=function(p0,p1,p2,p3,p4,p5,p6,p7){var m=this.REF,r=l.mR(this,cO,"uInsertRectangle",112);var P0=r.cP("ALIGN","PRIM_ALPH");var P1=r.cPF("WIDTH",Fd.F1.Dc);var P2=r.cPF("HEIGHT",Fd.F1.Dc);var P3=r.cPF("FROMLEFT",Fd.F1.Dc);
var P4=r.cPF("FROMTOP",Fd.F1.Dc);var P5=r.cPF("THICKNESS",Fd.F1.Dc);var P6=r.cP("COLOR","PRIM_ALPH");var P7=r.cP("BACKCOLOR","PRIM_ALPH");P0.set((p0===u)?("coords"):(p0));P1.set((p1===u)?(0):(p1));P2.set((p2===u)?(0):(p2));P3.set((p3===u)?(0):(p3));P4.set((p4===u)?(0):(p4));P5.set((p5===u)?(1):(p5));P6.set((p6===u)?("black"):(p6));P7.set((p7===u)?("white"):(p7));r.ln=112;{r.ln=123;m.REPORT.mthUINSERTRECTANGLE(P3.get(),P4.get(),P1.get(),P2.get(),P5.get(),P6.get(),P0.get(),P7.get());}r.ln=125;r.e();
};cO.mthUDRAWBARCODE=function(p0,p1,p2,p3,p4,p5,p6,p7){var m=this.REF,r=l.mR(this,cO,"uDrawBarcode",127);var P0=r.cP("DATA","PRIM_ALPH");var P1=r.cP("FORMAT","PRIM_ALPH");var P2=r.cPF("HEIGHT",Fd.F1.Dc);var P3=r.cPF("LINEWIDTH",Fd.F1.Dc);var P4=r.cPF("FROMLEFT",Fd.F1.Dc);var P5=r.cPF("FROMTOP",Fd.F1.Dc);var P6=r.cP("FONTNAME","PRIM_ALPH");var P7=r.cPF("FONTSIZE",Fd.F1.Dc);P0.set(p0);P1.set((p1===u)?("CODE128"):(p1));P2.set((p2===u)?(80):(p2));P3.set((p3===u)?(2):(p3));P4.set((p4===u)?(10):(p4));P5.set((p5===u)?(10):(p5));
P6.set((p6===u)?("monospace"):(p6));P7.set((p7===u)?(20):(p7));r.ln=127;{r.ln=138;m.REPORT.mthUDRAWBARCODE(P0.get(),P1.get(),P2.get(),P4.get(),P5.get(),P6.get(),P7.get(),P3.get());}r.ln=140;r.e();};cO.mthUSHOW=function(p0){var m=this.REF,r=l.mR(this,cO,"uShow",142);var P0=r.cP("PRINTPREVIEW","PRIM_BOLN");P0.set((p0===u)?(true):(p0));r.ln=142;{r.ln=146;m.REPORT.mthUSHOW(P0.get());}r.ln=148;r.e();};cO.mthUCLEARPAGES=function(){var m=this.REF,r=l.mR(this,cO,"uClearPages",150);r.ln=150;{r.ln=152;m.REPORT.mthUCLEARPAGES();
}r.ln=153;r.e();};cO.mthUTERMINATE=function(){var m=this.REF,r=l.mR(this,cO,"uTerminate",155);r.ln=155;{r.ln=156;m.REPORT.mthUTERMINATE();}r.ln=157;r.e();};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"STD_INT"});}},{rc:["DF_T69RPO"],rp:["PRIM_OBJT","PRIM_FLD"]});