LANSA.addComponent({id:"DF_T54F1O",ot:"rp",tp:"Reusable Part",de:"\\OC=List Manager Filter by Name",tl:14020001},function(l,oI,u){var lIO="";var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")){cL=l.gCL();}var Fd={F1:{nm:"DF_ELTX",ft:"A",ln:255,dc:0,lb:{"ENG":"Enter Text","FRA":"Texte","JPN":"ﾃｷｽﾄ"}[cL],h1:{"ENG":"Enter","FRA":"Texte","JPN":"ﾃｷｽﾄ"}[cL],h2:{"ENG":"Text","FRA":"Text","JPN":" "}[cL],h3:" ",de:{"ENG":"Enter Text","FRA":"Texte","JPN":"ﾃｷｽﾄ入力"}[cL],dv:"",ia:["LC","FE"]},F2:{nm:"STD_INT",
ft:"I",ln:4,dc:0,ec:"J",lb:{"ENG":"Std Integer","FRA":"?","JPN":"?"}[cL],h1:{"ENG":"Standard","FRA":"?","JPN":"?"}[cL],h2:{"ENG":"Integer","FRA":"?","JPN":"?"}[cL],h3:{"ENG":"Field","FRA":"?","JPN":"?"}[cL],de:{"ENG":"Standard Integer field","FRA":"?","JPN":"?"}[cL],dv:0,ia:["FE","RB"]},F3:{nm:"XSURNAME",an:"xEmployeeSurname",ft:"N",ln:40,dc:0,lb:"Surname",h1:"Employee",h2:"Surname",h3:" ",de:"Surname",dv:"",ia:["FE","LC"]},F4:{nm:"XGIVENAME",an:"xEmployeeGivenNames",ft:"N",ln:40,dc:0,lb:"Given Names",
h1:"Employee",h2:"Given",h3:"Names",de:"Given Names",dv:"",ia:["FE","LC"]},F5:{nm:"LISTCOUNT",ft:"P",ln:7,dc:0,ec:"J",lb:{"ENG":"Entries .......","FRA":"Entrées . . . .","JPN":"Entries ......."}[cL],h1:{"ENG":"Number","FRA":"Nombre","JPN":"Number"}[cL],h2:{"ENG":"of Entrys","FRA":"d´Entrées","JPN":"of Entrys"}[cL],h3:" ",de:{"ENG":"Number of entries in a browse list","FRA":"Liste, nombre d´entrées ds liste BROWSE","JPN":"Number of entries in a browse list"}[cL],dv:0,ia:["FE","RB"]},F6:{nm:"XEMPLOYID",
an:"xEmployeeIdentification",ft:"A",ln:10,dc:0,lb:{"ENG":"Employee Id","FRA":"Id employé","JPN":"社員 ID"}[cL],h1:{"ENG":"Employee","FRA":"Identification","JPN":"社員"}[cL],h2:{"ENG":"Identification","FRA":"Employé","JPN":"ID"}[cL],h3:" ",de:{"ENG":"Identification","FRA":"Identification","JPN":"身分証明"}[cL],dv:"",ia:["FE"]},F7:{nm:"XSTREET",an:"xEmployeeStreet",ft:"N",ln:40,dc:0,lb:{"ENG":"Street","FRA":"Rue","JPN":"番地"}[cL],h1:{"ENG":"Street","FRA":"Rue","JPN":"番地"}[cL],h2:" ",h3:" ",de:{"ENG":"Street","FRA":"Rue","JPN":"番地"}[cL],
dv:"",ia:["FE","LC"]},F8:{nm:"XCITY",an:"xEmployeeCity",ft:"N",ln:40,dc:0,lb:{"ENG":"City","FRA":"Commune","JPN":"市区町村"}[cL],h1:{"ENG":"City","FRA":"Commune","JPN":"市区町村"}[cL],h2:" ",h3:" ",de:{"ENG":"City","FRA":"Commune","JPN":"市区町村"}[cL],dv:"",ia:["FE","LC"]},F9:{nm:"XSTATE",an:"xEmployeeState",ft:"N",ln:40,dc:0,lb:{"ENG":"State","FRA":"Etat","JPN":"州"}[cL],h1:{"ENG":"State","FRA":"Etat","JPN":"州"}[cL],h2:" ",h3:" ",de:{"ENG":"State","FRA":"Etat","JPN":"州"}[cL],dv:"",ia:["FE","LC"]},F10:{nm:"XPOSTCODE",
an:"xEmployeePostalCode",ft:"A",ln:10,dc:0,lb:{"ENG":"Postal Code","FRA":"Code Postal","JPN":"郵便番号"}[cL],h1:{"ENG":"Postal","FRA":"Code","JPN":"郵便"}[cL],h2:{"ENG":"Code","FRA":"Postal","JPN":"番号"}[cL],h3:" ",de:{"ENG":"Postal Code","FRA":"Code Postal","JPN":"郵便番号"}[cL],dv:"",ia:["FE"]},F11:{nm:"XPHONEHME",an:"xEmployeeHomeTelephone",ft:"A",ln:15,dc:0,lb:{"ENG":"Home Phone","FRA":"Téléphone perso","JPN":"自宅 電話"}[cL],h1:{"ENG":"Home","FRA":"Téléphone","JPN":"自宅"}[cL],h2:{"ENG":"Telephone","FRA":"Personnel","JPN":"電話"}[cL],
h3:" ",de:{"ENG":"Home Telephone","FRA":"Téléphone personnel","JPN":"自宅 電話"}[cL],dv:"",ia:["FE"]},F12:{nm:"XPHONEBUS",an:"xEmployeeBusinessTelephone",ft:"A",ln:15,dc:0,lb:{"ENG":"Business Phone","FRA":"Tél. travail","JPN":"会社 電話"}[cL],h1:{"ENG":"Business","FRA":"Téléphone","JPN":"会社"}[cL],h2:{"ENG":"Telephone","FRA":"Travail","JPN":"電話"}[cL],h3:" ",de:{"ENG":"Business Telephone","FRA":"Téléphone travail","JPN":"会社 電話"}[cL],dv:"",ia:["FE"]},F13:{nm:"XSTARTDTE",an:"xEmployeeStartDate",ft:"D",ln:10,
dc:0,lb:{"ENG":"Start Date","FRA":"Date Embauche","JPN":"開始日"}[cL],h1:{"ENG":"Start","FRA":"Date","JPN":"開始"}[cL],h2:{"ENG":"Date","FRA":"Embauche","JPN":"日付"}[cL],h3:" ",de:{"ENG":"Start Date","FRA":"Date d'Embauche","JPN":"開始日"}[cL],dv:l.SqlNull,ia:["FE","ASQN"]},F14:{nm:"XTERMDATE",an:"xEmployeeTerminationDate",ft:"D",ln:10,dc:0,lb:{"ENG":"Termination","FRA":"Date de départ","JPN":"終了日"}[cL],h1:{"ENG":"Termination","FRA":"Date","JPN":"終了"}[cL],h2:{"ENG":"Date","FRA":"Départ","JPN":"日付"}[cL],h3:" ",
de:{"ENG":"Termination Date","FRA":"Date de départ","JPN":"終了日"}[cL],dv:l.SqlNull,ia:["FE","ASQN"]},F15:{nm:"XDEPTMENT",an:"xDepartmentCode",ft:"A",ln:4,dc:0,lb:{"ENG":"Department","FRA":"Département","JPN":"部門"}[cL],h1:{"ENG":"Department","FRA":"Code","JPN":"部門"}[cL],h2:{"ENG":"Code","FRA":"Département","JPN":"コード"}[cL],h3:" ",de:{"ENG":"Department","FRA":"Département","JPN":"部門"}[cL],dv:"",ia:["FE"]},F16:{nm:"XSALARY",an:"xEmployeeSalary",ft:"P",ln:15,dc:2,ec:"1",lb:{"ENG":"Annual Salary","FRA":"Salaire annuel","JPN":"年収"}[cL],
h1:{"ENG":"Annual","FRA":"Salaire","JPN":"年収"}[cL],h2:{"ENG":"Salary","FRA":"Annuel","JPN":" "}[cL],h3:" ",de:{"ENG":"Annual Salary","FRA":"Salaire annuel","JPN":"年収"}[cL],dv:0,ia:["FE","RB"]},F17:{nm:"IO$STS",ft:"A",ln:2,dc:0,lb:{"ENG":"I/O status ....","FRA":"Statut I/O  . .","JPN":"I/O status ...."}[cL],h1:{"ENG":"I/O","FRA":"Statut","JPN":"I/O"}[cL],h2:{"ENG":"Status","FRA":"I/O","JPN":"Status"}[cL],h3:" ",de:{"ENG":"Data base I/O operation status code","FRA":"Code statut opération I/O","JPN":"Data base I/O operation status code"}[cL],
dv:"",ia:["FE"]}};var cO=l.rC(oI,{an:"VF_AC007O",fd:Fd,mt:{uInitialize:{},uSelectData:{}},co:function(){cO.aN.call(this);var f=this.aF("DF_T54F1O",Fd);var C0=this.cR("LABEL_HOW_IT_WORKS","PRIM_LABL");var C1=this.cR("LABEL_INSTRUCTION","PRIM_LABL");var C2=this.cF("SEARCHSURNAME",Fd.F1.VISUALEDIT);var C3=this.cR("BUTTON_SEARCH","PRIM_PHBN");C0.setCaption("See component DF_T54F1O for details of this FILTER");C0.setDisplayPosition(4);C0.setEllipses("WORD");C0.setHeight(57);C0.setLeft(8);C0.setParent(this);
C0.setTabPosition(4);C0.setTabStop(false);C0.setTop(3);C0.setVerticalAlignment("CENTER");C0.setWidth(177);C0.iC();C1.setCaption("Enter a partial surname");C1.setDisplayPosition(1);C1.setHeight(25);C1.setLeft(8);C1.setParent(this);C1.setTabPosition(1);C1.setTabStop(false);C1.setTop(62);C1.setWidth(193);C1.setVerticalAlignment("CENTER");C1.iC();C2.setDisplayPosition(2);C2.setHeight(25);C2.setParent(this);C2.setTabPosition(2);C2.setTop(94);C2.setWidth(145);C2.setLabelType("CAPTION");C2.setMarginLeft(0);
C2.setLeft(8);C2.aD();C2.iC();C3.setCaption("Search");C3.setDisplayPosition(3);C3.setHeight(33);C3.setParent(this);C3.setTabPosition(3);C3.setTop(126);C3.setWidth(145);C3.setLeft(8);C3.setEnabled(false);C3.iC();C2.aH("ENTER",this,e1);C2.aH("CHANGED",this,e2);C3.aH("CLICK",this,e1);this.setHeight(169);this.setWidth(193);this.setLayoutManager(null);var li=this.aL("DF_T54F1O");li.SAVE_KEYS=l.cLT({"XSURNAME":f.F3,"XGIVENAME":f.F4},null);li.XEMPLOYEELIST=l.cLT({"XEMPLOYID":f.F6,"XSURNAME":f.F3,"XGIVENAME":f.F4,"XSTREET":f.F7,"XCITY":f.F8,"XSTATE":f.F9,"XPOSTCODE":f.F10,"XPHONEHME":f.F11,"XPHONEBUS":f.F12,"XSTARTDTE":f.F13,"XTERMDATE":f.F14,"XDEPTMENT":f.F15,"XSALARY":f.F16},f.F5);
}});var cA=cO.aN.prototype;cO.mthUINITIALIZE=function(){var r=l.mR(this,cO,"uInitialize",45);r.ln=45;{r.ln=47;cA.mthUINITIALIZE.call(this);r.ln=49;if(this.REF.AVFRAMEWORKMANAGER.getAVSMALLSCREEN()){r.ln=51;this.setAVFILTERLOCATION("TOP");this.setAVALLOWLOCATIONCHANGE(false);}else{r.ln=53;this.setAVFILTERLOCATION("LEFT");this.setAVALLOWLOCATIONCHANGE(false);}}r.ln=56;r.e();};function e1(sender,Ps){var r=l.eR(this,cO,"#Button_Search.Click #SearchSurname.Enter",60);r.ln=60;{r.ln=62;this.mthUSELECTDATA();
}r.ln=64;r.e();};function e2(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#SearchSurname.Changed",67);r.ln=67;{r.ln=69;m.BUTTON_SEARCH.setEnabled(l.s.ne(l.s.Trim(m.SEARCHSURNAME.get()),""));}r.ln=71;r.e();};cO.mthUSELECTDATA=function(){var li=this.LIST.DF_T54F1O,f=this.FLD.DF_T54F1O,m=this.REF,r=l.mR(this,cO,"uSelectData",74),mth=r;var C0=r.cDR("FIND","DF_T54DSO","FINDEMPBYSURNAME");C0.iC();C0.aH("COMPLETED",this,e3);r.ln=74;{r.ln=80;li.SAVE_KEYS.initList(1);r.ln=83;this.mthAVGOTOBUSYSTATE("Searching",false,u);
r.ln=87;this.REF.AVLISTMANAGER.setAVNCOLUMNPREFIX3("$");r.ln=90;this.REF.AVLISTMANAGER.mthCLEARLIST(u,u);r.ln=93;C0.mthEXECUTEASYNC({FLD:{"XSURNAME":m.SEARCHSURNAME.get(),"XGIVENAME":f.F4.get()}},{LIST:{"XEMPLOYEELIST":li.XEMPLOYEELIST}});}r.ln=124;r.e();function e3(sender,Ps){var r=l.eR(this,cO,"#Find.Completed",96,mth);var C1=r.cF("NUMERICPOSTALCODE",Fd.F2.Dc);C1.iC();r.ln=96;{r.ln=101;{var l1=li.XEMPLOYEELIST.selectList();while(l1.step()){r.ln=105;if(l.s.IsNumber(f.F10.get())){r.ln=106;C1.set(l.s.AsNumber(f.F10.get()));
}else{r.ln=108;C1.set(0);}r.ln=111;this.REF.AVLISTMANAGER.mthADDTOLIST(f.F6.get(),l.add(l.cat(f.F3.get(),", "),f.F4.get()),f.F6.get(),u,u,u,u,u,u,u,u,u,u,u,u,u,u,u,u,u,f.F12.get(),f.F7.get(),u,u,u,u,u,u,u,u,C1.get(),u,f.F16.get(),u,u,u,u,u,u,u,u,u,u,u,u,u,u);r.ln=113;}l1.end();}r.ln=116;f.F17.set(lIO=li.SAVE_KEYS.getEntry(1));r.ln=119;this.mthAVGOTOFREESTATE();}r.ln=121;r.e();}};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"DF_ELTX"});Fd.F1.VISUALEDIT=function()
{this.aN.call(this,new Fd.F1.Dc());this.setComponentVersion(1);this.setHeight(21);this.setUsePicklist(false);this.setWidth(782);};l.cFC({co:Fd.F1.VISUALEDIT,an:"PRIM_EVEF",fn:"DF_ELTX",cn:"VisualEdit"});}{Fd.F2.Dc=function(){this.aN.call(this,Fd.F2);};l.cFC({co:Fd.F2.Dc,an:"PRIM_FLD",fn:"STD_INT"});}cO.srAVFRAMEWORKMANAGER=function(rn){cA.srAVFRAMEWORKMANAGER.call(this,rn);};cO.srAVLISTMANAGER=function(rn){cA.srAVLISTMANAGER.call(this,rn);};},{rc:["VF_AC007O"],rp:["PRIM_LABL","PRIM_EVEF","PRIM_PHBN","PRIM_WEB.DataRequest","PRIM_FLD"]
});