LANSA.addComponent({id:"DF_T5802O",ot:"rp",tp:"Reusable Part",de:"\\OC=Custom Manager - Example 2",tl:14020001},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")){cL=l.gCL();}var Fd={F1:{nm:"STD_INT",ft:"I",ln:4,dc:0,ec:"J",lb:{"ENG":"Std Integer","FRA":"?","JPN":"?"}[cL],h1:{"ENG":"Standard","FRA":"?","JPN":"?"}[cL],h2:{"ENG":"Integer","FRA":"?","JPN":"?"}[cL],h3:{"ENG":"Field","FRA":"?","JPN":"?"}[cL],de:{"ENG":"Standard Integer field","FRA":"?","JPN":"?"}[cL],dv:0,ia:["FE","RB"]
}};var cO=l.rC(oI,{an:"VF_AC010O",fd:Fd,mt:{uInitialize:{},uTerminate:{},uExecute:{ps:{"GotoFreeState":{pt:"io"},"SwitchCallerReference":{pt:"i"}}}},co:function(){cO.aN.call(this);this.aF("DF_T5802O",Fd);var C0=this.cR("THISDEMOOBJECT","PRIM_LABL");var C1=this.cR("THISDEMOOBJECTSTYLE","PRIM_VS","Style");var C2=this.cR("LABEL1","PRIM_LABL");var C3=this.cR("SIMPLEENTRYFIELD","PRIM_EDIT");var C4=this.cR("STARTSIGNAL1","PRIM_PHBN");var C5=this.cR("LABEL2","PRIM_LABL");var C6=this.cF("DISPLAYEDNEXTORDERNUMBER",Fd.F1.VISUALEDIT);
var C7=this.cR("INCREMENTORDERNUMBER","PRIM_PHBN");this.cD("AVCUSTOMMANAGER");C0.setParent(this);C0.setDisplayPosition(4);C0.setTabPosition(4);C0.setTabStop(false);C0.setHeight(23);C0.setWidth(381);C0.setCaption("DF_T5802O - Custom Manager 2");C0.setStyle(C1);C0.setTop(4);C0.setLeft(4);C0.iC();C1.setTextColor("BLUE");C1.setFontSize(14);C1.iC();C2.setDisplayPosition(2);C2.setEllipses("WORD");C2.setHeight(41);C2.setLeft(24);C2.setParent(this);C2.setTabPosition(2);C2.setTabStop(false);C2.setTop(56);
C2.setVerticalAlignment("CENTER");C2.setWidth(489);C2.setCaption("Make sure that DF_T5801O (Custom Manager 1) is also active and visible");C2.iC();C3.setDisplayPosition(3);C3.setLeft(25);C3.setParent(this);C3.setShowSelection(false);C3.setShowSelectionHilight(false);C3.setTabPosition(3);C3.setTop(174);C3.setWidth(449);C3.iC();C4.setCaption("Click here to Start DF_T5801O (Custom Manager 1)");C4.setDisplayPosition(6);C4.setLeft(24);C4.setParent(this);C4.setTabPosition(6);C4.setTop(96);C4.setWidth(337);
C4.iC();C5.setDisplayPosition(1);C5.setEllipses("WORD");C5.setHeight(49);C5.setLeft(24);C5.setParent(this);C5.setTabPosition(1);C5.setTabStop(false);C5.setTop(136);C5.setVerticalAlignment("CENTER");C5.setWidth(473);C5.setCaption("Type text here to see it change in both command handlers.");C5.iC();C6.setComponentVersion(1);C6.setDisplayPosition(7);C6.setLeft(24);C6.setParent(this);C6.setTabPosition(7);C6.setTop(224);C6.setCaption("Next Order Number is");C6.setLabelType("CAPTION");C6.setWidth(177);
C6.setMarginLeft(140);C6.setReadOnly(true);C6.aD();C6.iC();C7.setCaption("Click to Increment the Next Order Number");C7.setDisplayPosition(5);C7.setLeft(24);C7.setParent(this);C7.setTabPosition(5);C7.setTop(248);C7.setWidth(337);C7.iC();C3.aH("CHANGED",this,e2);C4.aH("CLICK",this,e1);C7.aH("CLICK",this,e4);this.setHeight(425);this.setWidth(497);this.setLayoutManager(null);}});var cA=cO.aN.prototype;cO.mthUINITIALIZE=function(){var m=this.REF,r=l.mR(this,cO,"uInitialize",44);r.ln=44;{r.ln=47;cA.mthUINITIALIZE.call(this);
r.ln=49;this.srAVCUSTOMMANAGER(l.cast(this.REF.AVFRAMEWORKMANAGER.getAVCUSTOMMANAGERBASEREFERENCE(),"DF_OCUSTM"));}r.ln=51;r.e();};cO.mthUTERMINATE=function(){var m=this.REF,r=l.mR(this,cO,"uTerminate",54);r.ln=54;{r.ln=57;this.srAVCUSTOMMANAGER(null);r.ln=59;cA.mthUTERMINATE.call(this);}r.ln=61;r.e();};cO.mthUEXECUTE=function(p0,p1){var m=this.REF,r=l.mR(this,cO,"uExecute",64);var P0=r.cP("GOTOFREESTATE","PRIM_BOLN");var P1=r.cPD("SWITCHCALLERREFERENCE");P0.set(p0.get());P1=p1;r.ln=64;{r.ln=67;m.DISPLAYEDNEXTORDERNUMBER.set(m.AVCUSTOMMANAGER.getNEXTORDERNUMBER());
r.ln=70;m.SIMPLEENTRYFIELD.set(m.AVCUSTOMMANAGER.getSOMESHAREDTEXT());p0.set(P0.get());}r.ln=72;r.e();};function e1(sender,Ps){var r=l.eR(this,cO,"#StartSignal1.Click",76);r.ln=76;{r.ln=78;this.REF.AVFRAMEWORKMANAGER.mthAVSWITCH("CUSTOM_MANAGER_1",u,"COMMAND_EXAMPLE_1",u,this,u,u);}r.ln=80;r.e();};function e2(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#SimpleEntryField.Changed",85);r.ln=85;{r.ln=87;m.AVCUSTOMMANAGER.mthCHANGEDSHAREDTEXT(m.SIMPLEENTRYFIELD.get(),this);}r.ln=89;r.e();};function e3(sender,Ps)
{var m=this.REF,r=l.eR(this,cO,"#avCustomManager.SomeSharedTextChanged",94);var P0=Ps.r("BYCOMMANDHANDLER");r.ln=94;{r.ln=96;if((P0!==this)){r.ln=97;m.SIMPLEENTRYFIELD.setValue(m.AVCUSTOMMANAGER.getSOMESHAREDTEXT());}}r.ln=100;r.e();};function e4(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#IncrementOrderNumber.Click",104);r.ln=104;{r.ln=106;m.AVCUSTOMMANAGER.setNEXTORDERNUMBER(l.add(m.AVCUSTOMMANAGER.getNEXTORDERNUMBER(),1));}r.ln=108;r.e();};function e5(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#avCustomManager.NextOrderNumberChanged",112);
r.ln=112;{r.ln=114;m.DISPLAYEDNEXTORDERNUMBER.set(m.AVCUSTOMMANAGER.getNEXTORDERNUMBER());}r.ln=116;r.e();};function e6(sender,Ps){var r=l.eR(this,cO,"#avCustomManager.DF_T58NNExamplesClose",120);r.ln=120;{r.ln=122;this.mthAVCLOSEFORM();}r.ln=124;r.e();};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"STD_INT"});Fd.F1.VISUALEDIT=function(){this.aN.call(this,new Fd.F1.Dc());this.setHeight(19);this.setUsePicklist(false);this.setWidth(247);};l.cFC({co:Fd.F1.VISUALEDIT,an:"PRIM_EVEF",fn:"STD_INT",cn:"VisualEdit"});
}cO.srAVCUSTOMMANAGER=function(rn){if(this.REF.AVCUSTOMMANAGER!=null){this.REF.AVCUSTOMMANAGER.rH("SOMESHAREDTEXTCHANGED",this,e3);this.REF.AVCUSTOMMANAGER.rH("NEXTORDERNUMBERCHANGED",this,e5);this.REF.AVCUSTOMMANAGER.rH("DF_T58NNEXAMPLESCLOSE",this,e6);}this.sR("AVCUSTOMMANAGER",rn);if(this.REF.AVCUSTOMMANAGER!=null){this.REF.AVCUSTOMMANAGER.aH("SOMESHAREDTEXTCHANGED",this,e3);this.REF.AVCUSTOMMANAGER.aH("NEXTORDERNUMBERCHANGED",this,e5);this.REF.AVCUSTOMMANAGER.aH("DF_T58NNEXAMPLESCLOSE",this,e6);
}};cO.srAVFRAMEWORKMANAGER=function(rn){cA.srAVFRAMEWORKMANAGER.call(this,rn);};},{rc:["VF_AC010O"],rp:["PRIM_LABL","PRIM_VS.Style","PRIM_EDIT","PRIM_PHBN","PRIM_EVEF"],dc:["DF_OCUSTM"]});