LANSA.addComponent({id:"DF_T53F1O",ot:"rp",tp:"Reusable Part",de:"\\OC=Business Object 103 Filter",tl:14020001},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")){cL=l.gCL();}var Fd={F1:{nm:"DF_ELTX",ft:"A",ln:255,dc:0,lb:{"ENG":"Enter Text","FRA":"Texte","JPN":"ﾃｷｽﾄ"}[cL],h1:{"ENG":"Enter","FRA":"Texte","JPN":"ﾃｷｽﾄ"}[cL],h2:{"ENG":"Text","FRA":"Text","JPN":" "}[cL],h3:" ",de:{"ENG":"Enter Text","FRA":"Texte","JPN":"ﾃｷｽﾄ入力"}[cL],dv:"",ia:["LC","FE"]},F2:{nm:"STD_INT",ft:"I",ln:4,
dc:0,ec:"J",lb:{"ENG":"Std Integer","FRA":"?","JPN":"?"}[cL],h1:{"ENG":"Standard","FRA":"?","JPN":"?"}[cL],h2:{"ENG":"Integer","FRA":"?","JPN":"?"}[cL],h3:{"ENG":"Field","FRA":"?","JPN":"?"}[cL],de:{"ENG":"Standard Integer field","FRA":"?","JPN":"?"}[cL],dv:0,ia:["FE","RB"]}};var cO=l.rC(oI,{an:"VF_AC007O",fd:Fd,mt:{uInitialize:{}},co:function(){cO.aN.call(this);this.aF("DF_T53F1O",Fd);var C0=this.cA("PEOPLE_CONTROLLER2","DF_T53CCO");var C1=this.cR("LABEL_HOW_IT_WORKS","PRIM_LABL");var C2=this.cF("SEARCHSURNAME",Fd.F1.EDITFIELD);
var C3=this.cR("BUTTON_SEARCH","PRIM_MD","RaisedButton");var C4=this.cR("LABEL1","PRIM_LABL");var C5=this.cR("ATTACHITEM1","PRIM_ATLI");var C6=this.cR("ATTACHITEM2","PRIM_ATLI");if((C0!=null)&&(C0.iI()==false)){C0.iC();}C1.setCaption("See component DF_T53F1O for details of this FILTER");C1.setDisplayPosition(1);C1.setHeight(24);C1.setLeft(4);C1.setParent(this);C1.setTabPosition(1);C1.setTabStop(false);C1.setTop(104);C1.setWidth(305);C1.setVerticalAlignment("CENTER");C1.iC();C2.setDisplayPosition(2);
C2.setHeight(36);C2.setParent(this);C2.setTabPosition(2);C2.setTop(8);C2.setWidth(201);C2.setLeft(8);C2.setPlaceholder("Enter all or part of a surname");C2.setHelperPosition("NONE");C2.setLabelPosition("NONE");C2.aD();C2.iC();C3.setCaption("Search");C3.setDisplayPosition(4);C3.setParent(this);C3.setTabPosition(4);C3.setTop(8);C3.setWidth(89);C3.setLeft(215);C3.setButtonDefault(true);C3.setThemeDrawStyle("MediumTitle");C3.iC();C4.setCaption("This example uses both a client controller and a Shared Server System Object (DF_T53SSO). The Server System object is useful if any common processing has to be done at the start and end of calls to server modules. For example setting the library list for the job, or setting the job user profile.");
C4.setDisplayPosition(3);C4.setEllipses("WORD");C4.setHeight(117);C4.setLeft(4);C4.setParent(this);C4.setTabPosition(3);C4.setTabStop(false);C4.setTop(136);C4.setVerticalAlignment("CENTER");C4.setWidth(305);C4.iC();C5.setManage(C4);C5.setParent(this.REF.MAINPANELATTACHMENTMANAGER);C5.setAttachment("BOTTOM");C5.setMarginLeft(4);C5.setMarginRight(4);C5.setMarginTop(4);C5.setMarginBottom(4);C5.iC();C6.setManage(C1);C6.setParent(this.REF.MAINPANELATTACHMENTMANAGER);C6.setAttachment("BOTTOM");C6.setMarginLeft(4);
C6.setMarginRight(4);C6.setMarginTop(4);C6.setMarginBottom(4);C6.iC();C2.aH("CHANGED",this,e1);C2.aH("ENTER",this,e2);C3.aH("CLICK",this,e2);this.setHeight(257);this.setWidth(313);}});var cA=cO.aN.prototype;cO.mthUINITIALIZE=function(){var m=this.REF,r=l.mR(this,cO,"uInitialize",53);r.ln=53;{r.ln=55;cA.mthUINITIALIZE.call(this);r.ln=57;if(this.REF.AVFRAMEWORKMANAGER.getAVSMALLSCREEN()){r.ln=59;this.setAVFILTERLOCATION("TOP");this.setAVALLOWLOCATIONCHANGE(false);r.ln=60;m.LABEL1.setVisible(false);
r.ln=61;m.LABEL_HOW_IT_WORKS.setVisible(false);r.ln=62;this.setHeight(90);}else{r.ln=64;this.setAVFILTERLOCATION("LEFT");this.setAVALLOWLOCATIONCHANGE(false);}r.ln=67;m.BUTTON_SEARCH.setEnabled(false);}r.ln=69;r.e();};function e1(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#SearchSurname.Changed",72);r.ln=72;{r.ln=74;m.BUTTON_SEARCH.setEnabled(l.s.ne(l.s.Trim(m.SEARCHSURNAME.get()),""));}r.ln=76;r.e();};function e2(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Button_Search.Click #SearchSurname.Enter",79);
var C0=r.cF("TOTALFOUND",Fd.F2.Dc);C0.iC();r.ln=79;{r.ln=85;if(l.s.ne(l.s.Trim(m.SEARCHSURNAME.get()),"")){r.ln=88;this.REF.AVFRAMEWORKMANAGER.mthAVCLEARMESSAGES(this,u,u);r.ln=91;m.PEOPLE_CONTROLLER2.ref.mthFINDEMPLOYEES(2,false,m.SEARCHSURNAME.get(),this.REF.AVLISTMANAGER,true,C0);r.ln=94;this.REF.AVFRAMEWORKMANAGER.mthAVISSUEMESSAGE(l.cat(l.cat(l.cat("Search for '",m.SEARCHSURNAME.get()),"' found "),l.n.AsString(C0.get())),u,u,this,true,u,true);}}r.ln=98;r.e();};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);
};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"DF_ELTX"});Fd.F1.EDITFIELD=function(){this.aN.call(this,new Fd.F1.Dc());};l.cFC({co:Fd.F1.EDITFIELD,an:"PRIM_MD",at:"Edit",fn:"DF_ELTX",cn:"EditField"});}{Fd.F2.Dc=function(){this.aN.call(this,Fd.F2);};l.cFC({co:Fd.F2.Dc,an:"PRIM_FLD",fn:"STD_INT"});}cO.srAVFRAMEWORKMANAGER=function(rn){cA.srAVFRAMEWORKMANAGER.call(this,rn);};cO.srAVLISTMANAGER=function(rn){cA.srAVLISTMANAGER.call(this,rn);};},{rc:["VF_AC007O","DF_T53CCO"],rp:["PRIM_LABL","PRIM_MD.Edit","PRIM_MD.RaisedButton","PRIM_ATLI","PRIM_FLD"]
});