LANSA.addComponent({id:"VF_FL001O",ot:"rp",tp:"Reusable Part",de:"\\OC=VLF-ONE Filter Default RAD-PAD",tl:14020001},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")){cL=l.gCL();}var Fd={F1:{nm:"STD_NUM",ft:"P",ln:7,dc:0,ec:"A",lb:{"ENG":"Number","FRA":"Nombre","JPN":"Number"}[cL],h1:{"ENG":"Standard","FRA":"Nombre","JPN":"Standard"}[cL],h2:{"ENG":"Number","FRA":" ","JPN":"Number"}[cL],h3:" ",de:{"ENG":"Standard Number","FRA":"Nombre Standard","JPN":"Standard Number"}[cL],dv:0,ia:["FE","RB"]
},F2:{nm:"STD_INT",ft:"I",ln:4,dc:0,ec:"J",lb:{"ENG":"Std Integer","FRA":"?","JPN":"?"}[cL],h1:{"ENG":"Standard","FRA":"?","JPN":"?"}[cL],h2:{"ENG":"Integer","FRA":"?","JPN":"?"}[cL],h3:{"ENG":"Field","FRA":"?","JPN":"?"}[cL],de:{"ENG":"Standard Integer field","FRA":"?","JPN":"?"}[cL],dv:0,ia:["FE","RB"]}};var cO=l.rC(oI,{an:"VF_AC007O",fd:Fd,mt:{SetInitialFocus:{},uBringToFront:{},uInitialize:{},uTerminate:{}},co:function(){cO.aN.call(this);this.aF("VF_FL001O",Fd);var C0=this.cR("ATTACHLAYOUT1","PRIM_ATLM");
var C1=this.cR("ATTACHITEM1","PRIM_ATLI");var C2=this.cR("ATTACHITEM2","PRIM_ATLI");var C3=this.cR("ATTACHLAYOUT2","PRIM_ATLM");var C4=this.cR("ATTACHITEMLIMIT","PRIM_ATLI");var C5=this.cR("ATTACHITEMSEARCH","PRIM_ATLI");var C6=this.cR("RADPANEL","VF_UI031O");var C7=this.cR("SEARCHPANEL","PRIM_PANL");var C8=this.cR("SEARCH","VF_UI048O");var C9=this.cF("LIMIT",Fd.F1.VISUAL);C0.iC();C1.setManage(C6);C1.setParent(C0);C1.setAttachment("CENTER");C1.iC();C2.setManage(C7);C2.setParent(C0);C2.setAttachment("BOTTOM");
C2.iC();C3.iC();C4.setManage(C9);C4.setParent(C3);C4.setAttachment("LEFT");C4.setMarginLeft(6);C4.setMarginTop(4);C4.setMarginBottom(4);C4.iC();C5.setParent(C3);C5.setAttachment("LEFT");C5.setMarginLeft(6);C5.setMarginTop(4);C5.setMarginBottom(4);C5.setManage(C8);C5.iC();C6.setParent(this);C6.setHeight(217);C6.setWidth(220);C6.iC();C7.setParent(this);C7.setDisplayPosition(2);C7.setTabPosition(2);C7.setLeft(0);C7.setWidth(220);C7.setHeight(30);C7.setTop(217);C7.setLayoutManager(C3);C7.iC();C8.setDisplayPosition(2);
C8.setTabPosition(2);C8.setTop(4);C8.setWidth(200);C8.setHeight(22);C8.setParent(C7);C8.setLeft(81);C8.iC();C9.setDisplayPosition(1);C9.setHeight(22);C9.setLabelType("CAPTION");C9.setMarginLeft(40);C9.setTabPosition(1);C9.setUsePicklist(false);C9.setWidth(69);C9.setCaption("Limit");C9.setParent(C7);C9.setLeft(6);C9.setTop(4);C9.aD();C9.iC();C8.aH("WASCLICKED",this,e1);C9.aH("ENTER",this,e1);C9.aH("CHANGED",this,e3);this.REF.AVLOCALTIMER.aH("TICK",this,e2);this.setWidth(220);this.setLayoutManager(C0);
this.setHeight(247);}});var cA=cO.aN.prototype;cO.mthSETINITIALFOCUS=function(){var m=this.REF,r=l.mR(this,cO,"SetInitialFocus",30);r.ln=30;{r.ln=32;m.SEARCH.mthSETFOCUS();}r.ln=34;r.e();};cO.mthUBRINGTOFRONT=function(){var r=l.mR(this,cO,"uBringToFront",37);r.ln=37;{r.ln=39;this.mthSETINITIALFOCUS();}r.ln=41;r.e();};cO.mthUINITIALIZE=function(){var m=this.REF,r=l.mR(this,cO,"uInitialize",44);var C0=r.cR("SEARCHCAPTION","PRIM_ALPH");var C1=r.cF("MARGINS",Fd.F2.Dc);C0.iC();C1.iC();r.ln=44;{r.ln=50;
cA.mthUINITIALIZE.call(this);r.ln=54;this.REF.USYSTEM.ref.mthZINT_SETBUTTONBARHEIGHT(m.SEARCHPANEL);r.ln=55;m.SEARCH.mthZINT_INITIALIZE("",true,false,true,true);r.ln=56;if(this.REF.USYSTEM.ref.getUIMATERIALDESIGN()){r.ln=57;C1.set(l.div(l.sub(m.SEARCHPANEL.getHeight(),26),2));r.ln=58;m.ATTACHITEMLIMIT.setMarginBottom(C1.get());m.ATTACHITEMLIMIT.setMarginTop(C1.get());}r.ln=61;C0.set(this.REF.USYSTEM.ref.getUMTXTVALUES("SEARCHFOR"));r.ln=62;C0.set(l.s.Substitute(C0.get(),this.getASSOCIATEDVF_FR003O().getUCAPTION()));
r.ln=63;m.SEARCH.setCAPTION(C0.get());r.ln=64;this.setAVTITLEBARCAPTION(C0.get());r.ln=66;m.LIMIT.setCaption(this.REF.USYSTEM.ref.getUMTXTVALUES("LIMIT"));r.ln=67;m.LIMIT.set(10);r.ln=71;this.setAVALLOWLOCATIONCHANGE(true);r.ln=75;if(this.getASSOCIATEDFILTERDEFINITIONREFERENCE().getURADPADFILEEXISTS()){r.ln=77;m.RADPANEL.setVisible(true);r.ln=78;m.RADPANEL.mthZINT_INITIALIZE(this);r.ln=79;this.setAVFILTERLOCATION("LEFT");}else{r.ln=84;m.RADPANEL.setVisible(false);r.ln=85;this.setHeight(m.SEARCHPANEL.getHeight());
r.ln=87;this.setAVFILTERLOCATION("TOP");}r.ln=92;if(this.REF.AVFRAMEWORKMANAGER.getAVSMALLSCREEN()){r.ln=93;this.setAVFILTERLOCATION("LEFT");}r.ln=96;this.mthSETINITIALFOCUS();}r.ln=98;r.e();};cO.mthUTERMINATE=function(){var m=this.REF,r=l.mR(this,cO,"uTerminate",101);r.ln=101;{r.ln=103;m.RADPANEL.mthZINT_TERMINATE();r.ln=105;m.SEARCH.mthZINT_TERMINATE();r.ln=107;cA.mthUTERMINATE.call(this);}r.ln=109;r.e();};function e1(sender,Ps){var r=l.eR(this,cO,"#SEARCH.WasClicked #Limit.Enter",112);r.ln=112;
{r.ln=114;this.mthAVGOTOBUSYSTATE(this.REF.USYSTEM.ref.getUMTXTVALUES("SEARCHING"),false,u);r.ln=116;this.REF.AVLOCALTIMER.setInterval(5);}r.ln=118;r.e();};function e2(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#AVLOCALTIMER.Tick",121);r.ln=121;{r.ln=123;this.REF.AVLOCALTIMER.setInterval(0);r.ln=125;this.REF.USYSTEM.ref.mthEMULATEINSTANCELISTSEARCH(m.LIMIT.get(),this.REF.ASSOCIATEDVF_FR003O,"",u,u);r.ln=127;this.mthAVGOTOFREESTATE();}r.ln=129;r.e();};function e3(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Limit.Changed",132);
r.ln=132;{r.ln=134;if(l.n.lt(m.LIMIT.get(),1)){r.ln=135;m.LIMIT.set(1);}r.ln=138;if(l.n.gt(m.LIMIT.get(),200)){r.ln=139;m.LIMIT.set(200);}}r.ln=142;r.e();};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"STD_NUM"});Fd.F1.VISUAL=function(){this.aN.call(this,new Fd.F1.Dc());};l.cFC({co:Fd.F1.VISUAL,an:"PRIM_EVEF",fn:"STD_NUM",cn:"Visual"});}{Fd.F2.Dc=function(){this.aN.call(this,Fd.F2);};l.cFC({co:Fd.F2.Dc,an:"PRIM_FLD",fn:"STD_INT"});}cO.srAVFRAMEWORKMANAGER=function(rn)
{cA.srAVFRAMEWORKMANAGER.call(this,rn);};cO.srASSOCIATEDVF_FR003O=function(rn){cA.srASSOCIATEDVF_FR003O.call(this,rn);};},{rc:["VF_AC007O","VF_UI031O","VF_UI048O"],rp:["PRIM_ATLM","PRIM_ATLI","PRIM_PANL","PRIM_EVEF","PRIM_FLD"],dp:["PRIM_ALPH"]});