LANSA.addComponent({id:"XBNTRANS",nm:"XBNTransactions",ot:"rp",tp:"Reusable Part",de:"Transactions Panel",tl:14020001},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")||(l.gCL()=="LLL")){cL=l.gCL();}var Fd={F1:{nm:"XBNTRNDAT",an:"XBNTransactionDate",ft:"D",ln:10,dc:0,lb:{"ENG":"Trans. Date","FRA":"?","JPN":"Trans. Date","LLL":"Trans. Date"}[cL],h1:{"ENG":"Transaction","FRA":"?","JPN":"Transaction","LLL":"Transaction"}[cL],h2:{"ENG":"Date","FRA":"","JPN":"Date","LLL":"Date"}[cL],
h3:"",de:{"ENG":"Transaction Date","FRA":"?","JPN":"Transaction Date","LLL":"Transaction Date"}[cL],dv:l.SqlNull,ia:["ASQN","FE","ISO"]},F2:{nm:"XBNTRNDSC",an:"XBNTransactionDescription",ft:"A",ln:100,dc:0,lb:{"ENG":"Trans. Desc.","FRA":"?","JPN":"Trans. Desc.","LLL":"Trans. Desc."}[cL],h1:{"ENG":"Transaction","FRA":"?","JPN":"Transaction","LLL":"Transaction"}[cL],h2:{"ENG":"Description","FRA":"","JPN":"Description","LLL":"Description"}[cL],h3:"",de:{"ENG":"Transaction Description","FRA":"?","JPN":"Transaction Description","LLL":"Transaction Description"}[cL],
dv:"",ia:["FE","LC"]},F3:{nm:"XBNTRNAMT",an:"XBNTransactionAmount",ft:"P",ln:9,dc:2,ec:"O",lb:{"ENG":"Trans. Amt.","FRA":"?","JPN":"Trans. Amt.","LLL":"Trans. Amt."}[cL],h1:{"ENG":"Transaction","FRA":"?","JPN":"Transaction","LLL":"Transaction"}[cL],h2:{"ENG":"Amount","FRA":"","JPN":"Amount","LLL":"Amount"}[cL],h3:"",de:{"ENG":"Transaction Amount","FRA":"?","JPN":"Transaction Amount","LLL":"Transaction Amount"}[cL],dv:0,ia:["FE","RB"]},F4:{nm:"XBNACTBAL",an:"XBNAccountBalance",ft:"P",ln:9,dc:2,ec:"O",
lb:{"ENG":"Account Bal.","FRA":"?","JPN":"Account Bal.","LLL":"Account Bal."}[cL],h1:{"ENG":"Account","FRA":"?","JPN":"Account","LLL":"Account"}[cL],h2:{"ENG":"Balance","FRA":"","JPN":"Balance","LLL":"Balance"}[cL],h3:"",de:{"ENG":"Account Balance","FRA":"?","JPN":"Account Balance","LLL":"Account Balance"}[cL],dv:0,ia:["FE","RB"]}};var cO=l.rC(oI,{an:"PRIM_PANL",fd:Fd,mt:{LoadTransactions:{ps:{"AccountName":{pt:"i"},"AccountDescription":{pt:"i"}}}},ev:{AccountsClicked:{}},co:function(){cO.aN.call(this);
var f=this.aF("XBNTRANS",Fd);var C0=this.cR("TABLELAYOUT","PRIM_TBLO");var C1=this.cR("COLUMN2","PRIM_TBLO","Column");var C2=this.cR("COLUMN3","PRIM_TBLO","Column");var C3=this.cR("COLUMN1","PRIM_TBLO","Column");var C4=this.cR("ROW1","PRIM_TBLO","Row");var C5=this.cR("ROW2","PRIM_TBLO","Row");var C6=this.cR("ROW3","PRIM_TBLO","Row");var C7=this.cR("ROW4","PRIM_TBLO","Row");var C8=this.cR("ROW5","PRIM_TBLO","Row");var C9=this.cR("LAYOUTITEM1","PRIM_TBLO","Item");var C10=this.cR("LAYOUTITEM3","PRIM_TBLO","Item");
var C11=this.cR("LAYOUTITEM2","PRIM_TBLO","Item");var C12=this.cR("LAYOUTITEM4","PRIM_TBLO","Item");var C13=this.cR("LAYOUTITEM5","PRIM_TBLO","Item");var C14=this.cR("DIVIDER","PRIM_PANL");var C15=this.cR("ACCOUNTSLABEL","PRIM_LABL");var C16=this.cR("LABEL1","PRIM_LABL");var C17=this.cR("ACCOUNTDESCRIPTIONLABEL","PRIM_LABL");var C18=this.cR("TRANSACTIONSLIST","PRIM_LIST");var C19=this.cR("COLUMN_DATE","PRIM_LIST","DateTime");var C20=this.cR("COLUMN_DESCRIPTION","PRIM_LIST","String");var C21=this.cR("COLUMN_AMOUNT","PRIM_LIST","Number");
var C22=this.cR("COLUMN_BALANCE","PRIM_LIST","Number");var C23=this.cR("DIVIDERLINESTYLE","PRIM_VS","Style");C0.iC();C1.setDisplayPosition(1);C1.setParent(C0);C1.iC();C2.setDisplayPosition(3);C2.setParent(C0);C2.iC();C3.setDisplayPosition(2);C3.setParent(C0);C3.setWidth(7);C3.iC();C4.setDisplayPosition(1);C4.setParent(C0);C4.setUnits("PIXELS");C4.setHeight(2);C4.iC();C5.setDisplayPosition(2);C5.setParent(C0);C5.setHeight(60);C5.setUnits("PIXELS");C5.iC();C6.setDisplayPosition(4);C6.setParent(C0);
C6.setHeight(5);C6.iC();C7.setDisplayPosition(3);C7.setParent(C0);C7.setUnits("PIXELS");C7.setHeight(10);C7.iC();C8.setDisplayPosition(5);C8.setParent(C0);C8.setHeight(30);C8.setUnits("PIXELS");C8.iC();C9.setManage(C15);C9.setParent(C0);C9.setRow(C5);C9.setColumn(C1);C9.setMarginLeft(15);C9.setColumnSpan(2);C9.setAlignment("TOPLEFT");C9.setSizing("FITTOHEIGHT");C9.setFlow("RIGHT");C9.iC();C10.setManage(C14);C10.setParent(C0);C10.setRow(C4);C10.setColumn(C1);C10.setColumnSpan(3);C10.setMarginLeft(10);
C10.setMarginRight(10);C10.iC();C11.setAlignment("TOPLEFT");C11.setColumn(C1);C11.setFlow("RIGHT");C11.setManage(C16);C11.setParent(C0);C11.setRow(C5);C11.setSizing("FITTOHEIGHT");C11.iC();C12.setAlignment("TOPLEFT");C12.setColumn(C1);C12.setManage(C17);C12.setParent(C0);C12.setRow(C5);C12.setFlow("RIGHT");C12.setColumnSpan(2);C12.setSizing("FITTOHEIGHT");C12.setMarginLeft(5);C12.iC();C13.setColumn(C3);C13.setManage(C18);C13.setParent(C0);C13.setRow(C6);C13.iC();C14.setDisplayPosition(2);C14.setHeight(2);
C14.setParent(this);C14.setTabPosition(1);C14.setTabStop(false);C14.setTop(0);C14.setWidth(744);C14.setStyle(C23);C14.iC();C15.setCaption("Accounts");C15.setDisplayPosition(1);C15.setEllipses("WORD");C15.setParent(this);C15.setTabPosition(2);C15.setTabStop(false);C15.setTop(2);C15.setVerticalAlignment("CENTER");C15.setWidth(86);C15.setThemeDrawStyle("Heading2AsLink");C15.setHeight(60);C15.setLeft(15);C15.iC();C16.setCaption(">>");C16.setDisplayPosition(3);C16.setEllipses("WORD");C16.setLeft(101);
C16.setParent(this);C16.setTabPosition(4);C16.setTabStop(false);C16.setTop(2);C16.setVerticalAlignment("CENTER");C16.setWidth(40);C16.setAlignment("CENTER");C16.setHeight(60);C16.setThemeDrawStyle("Heading2");C16.iC();C17.setCaption("Account Description");C17.setDisplayPosition(4);C17.setEllipses("WORD");C17.setParent(this);C17.setTabPosition(3);C17.setTabStop(false);C17.setTop(2);C17.setVerticalAlignment("CENTER");C17.setWidth(546);C17.setThemeDrawStyle("Heading2");C17.setLeft(146);C17.setHeight(60);
C17.iC();C18.setDisplayPosition(5);C18.setHeight(379);C18.setLeft(85);C18.setParent(this);C18.setTabPosition(5);C18.setTop(72);C18.setWidth(595);C18.setColumnHeaderHeight(40);C18.setColumnLines(false);C18.setRowHeight(24);C18.iC();C19.setDisplayPosition(1);C19.setParent(C18);C19.setSource(f.F1);C19.setColumnCaptionType("CAPTION");C19.setColumnCaption("Date");C19.setShowTime(false);C19.iC();C20.setDisplayPosition(2);C20.setParent(C18);C20.setSource(f.F2);C20.setColumnCaptionType("CAPTION");C20.setColumnCaption("Description");
C20.setColumnWidth(286);C20.iC();C21.setDisplayPosition(3);C21.setIncrement(1);C21.setParent(C18);C21.setSource(f.F3);C21.setWrap(false);C21.setColumnCaptionType("CAPTION");C21.setColumnCaption("Amount");C21.setDisplayAlignment("RIGHT");C21.setColumnWidth(90);C21.iC();C22.setDisplayPosition(4);C22.setIncrement(1);C22.setParent(C18);C22.setSource(f.F4);C22.setWrap(false);C22.setColumnCaptionType("CAPTION");C22.setColumnCaption("Balance");C22.setDisplayAlignment("RIGHT");C22.setColumnWidth(100);C22.iC();
C23.setBorderBottom(4);C23.setBorderColor("THEME200");C23.iC();C15.aH("CLICK",this,e1);this.setDisplayPosition(1);this.setHeight(481);this.setLeft(0);this.setTabPosition(1);this.setTop(0);this.setWidth(764);this.setLayoutManager(C0);}});function e1(sender,Ps){var r=l.eR(this,cO,"#AccountsLabel.Click",44);r.ln=44;{r.ln=46;this.fE("ACCOUNTSCLICKED");}r.ln=48;r.e();};cO.mthLOADTRANSACTIONS=function(p0,p1){var m=this.REF,r=l.mR(this,cO,"LoadTransactions",50);var P0=r.cP("ACCOUNTNAME","PRIM_ALPH");var P1=r.cP("ACCOUNTDESCRIPTION","PRIM_ALPH");
P0.set(p0);P1.set(p1);var C0=r.cDR("GETTRANSACTIONSROUTINE","XBNSRVR","GETTRANSACTIONS");C0.iC();r.ln=50;{r.ln=56;m.ACCOUNTDESCRIPTIONLABEL.set(P1.get());r.ln=58;m.TRANSACTIONSLIST.clearList();r.ln=60;C0.mthEXECUTEASYNC({FLD:{"ACCOUNTNAME":P0.get()}},{LIST:{"TRANSACTIONLIST":m.TRANSACTIONSLIST}});}r.ln=62;r.e();};},{rp:["PRIM_PANL","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_TBLO.Item","PRIM_LABL","PRIM_LIST","PRIM_LIST.DateTime","PRIM_LIST.String","PRIM_LIST.Number","PRIM_VS.Style","PRIM_WEB.DataRequest"]
});