LANSA.addComponent({id:"XDEMO_58",nm:"xDemoWebPopupinaLoopViewer",ot:"rp",tp:"Reusable Part",de:"Popup in a Loop Viewer",tl:14020001},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")||(l.gCL()=="LLL")){cL=l.gCL();}var c1=l.cDec("1.71");var rc1=l.cB("ximagep_4.png");var rc2=l.cB("ximagen_2.png");var rc3=l.cB("ximagefir.png");var rc4=l.cB("ximagelas.png");var Fd={F1:{nm:"XGIVENAME",an:"xEmployeeGivenNames",ft:"A",ln:20,dc:0,lb:{"ENG":"Given Names","FRA":"Prénoms","JPN":"名前","LLL":"Given Names"}[cL],
h1:{"ENG":"Employee","FRA":"Prénoms","JPN":"社員","LLL":"Employee"}[cL],h2:{"ENG":"Given","FRA":"Employé","JPN":"ファースト","LLL":"Given"}[cL],h3:{"ENG":"Names","FRA":" ","JPN":"ネーム","LLL":"Names"}[cL],de:{"ENG":"Given Names","FRA":"Prénoms","JPN":"ファーストネーム","LLL":"Given Names"}[cL],dv:"",ia:["FE","LC"]},F2:{nm:"XSURNAME",an:"xEmployeeSurname",ft:"N",ln:40,dc:0,lb:{"ENG":"Surname","FRA":"Nom","JPN":"姓","LLL":"Surname"}[cL],h1:{"ENG":"Employee","FRA":"Nom","JPN":"社員","LLL":"Employee"}[cL],h2:{"ENG":"Surname","FRA":"Employé","JPN":"姓","LLL":"Surname"}[cL],
h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:{"ENG":"Surname","FRA":"Nom","JPN":"姓","LLL":"Surname"}[cL],dv:"",ia:["FE","LC"]},F3:{nm:"XEMPLOYID",an:"xEmployeeIdentification",ft:"A",ln:10,dc:0,lb:{"ENG":"Employee Id","FRA":"Id employé","JPN":"社員 ID","LLL":"Employee Id"}[cL],h1:{"ENG":"Employee","FRA":"Identification","JPN":"社員","LLL":"Employee"}[cL],h2:{"ENG":"Identification","FRA":"Employé","JPN":"ID","LLL":"Identification"}[cL],h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:{"ENG":"Identification","FRA":"Identification","JPN":"身分証明","LLL":"Identification"}[cL],
dv:"",ia:["FE"]},F4:{nm:"XEMPTHM",an:"xEmployeeImageThumbnail",ft:"BL",ln:0,dc:0,lb:{"ENG":"Employee Image","FRA":"Image Employé","JPN":"社員画像","LLL":"Employee Image"}[cL],h1:{"ENG":"Employee","FRA":"Image","JPN":"社員","LLL":"Employee"}[cL],h2:{"ENG":"Image","FRA":"employé","JPN":"画像","LLL":"Image"}[cL],h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:{"ENG":"Employee Image Thumbnail","FRA":"Image miniature employé","JPN":"社員サムネイル画像","LLL":"Employee Image Thumbnail"}[cL],dv:l.SqlNull,ia:["ASQN","FE","LC"]
}};var cO=l.rC(oI,{an:"PRIM_PPNL",fd:Fd,mt:{ShowDetails:{ps:{"GivenNames":{pt:"i"},"Surname":{pt:"i"},"ID":{pt:"i"},"Thumbnail":{pt:"i"}}}},ev:{Navigating:{ps:{"Item":{pt:"i"}}}},co:function(){cO.aN.call(this);this.aF("XDEMO_58",Fd);var C0=this.cR("STYLE1","PRIM_VS","Style");var C1=this.cR("STYLE2","PRIM_VS","Style");var C2=this.cR("BRUSH1","PRIM_VS","SolidBrush");var C3=this.cR("LAYOUT1","PRIM_TBLO");var C4=this.cR("COLUMN1","PRIM_TBLO","Column");var C5=this.cR("ROW1","PRIM_TBLO","Row");var C6=this.cR("ROW2","PRIM_TBLO","Row");
var C7=this.cR("LAYOUTITEM2","PRIM_TBLO","Item");var C8=this.cR("LAYOUTITEM3","PRIM_TBLO","Item");var C9=this.cR("LAYOUTITEM4","PRIM_TBLO","Item");var C10=this.cR("LAYOUTITEM5","PRIM_TBLO","Item");var C11=this.cR("LAYOUTITEM1","PRIM_TBLO","Item");var C12=this.cR("EMPLOYEEIMAGE","PRIM_IMAG");var C13=this.cR("PREVIOUS","PRIM_IMAG");var C14=this.cR("NEXT","PRIM_IMAG");var C15=this.cR("FIRST","PRIM_IMAG");var C16=this.cR("LAST","PRIM_IMAG");C0.setCursor("HAND");C0.iC();C1.setBackgroundBrush(C2);C1.iC();
C2.setColor("0:0:0");C2.setOpacity(20);C2.iC();C3.iC();C4.setDisplayPosition(1);C4.setParent(C3);C4.iC();C5.setDisplayPosition(1);C5.setParent(C3);C5.setHeight(c1);C5.iC();C6.setDisplayPosition(2);C6.setParent(C3);C6.setHeight(56);C6.setUnits("PIXELS");C6.iC();C7.setColumn(C4);C7.setFlow("CENTERHORIZONTAL");C7.setManage(C15);C7.setParent(C3);C7.setRow(C6);C7.setSizing("NONE");C7.setMarginLeft(4);C7.setMarginRight(4);C7.iC();C8.setColumn(C4);C8.setFlow("CENTERHORIZONTAL");C8.setManage(C13);C8.setParent(C3);
C8.setRow(C6);C8.setSizing("NONE");C8.setMarginLeft(4);C8.setMarginRight(4);C8.iC();C9.setColumn(C4);C9.setFlow("CENTERHORIZONTAL");C9.setManage(C14);C9.setParent(C3);C9.setRow(C6);C9.setSizing("NONE");C9.setMarginLeft(4);C9.setMarginRight(4);C9.iC();C10.setColumn(C4);C10.setFlow("CENTERHORIZONTAL");C10.setManage(C16);C10.setParent(C3);C10.setRow(C6);C10.setSizing("NONE");C10.setMarginLeft(4);C10.setMarginRight(4);C10.iC();C11.setColumn(C4);C11.setManage(C12);C11.setParent(C3);C11.setRow(C5);C11.setMarginBottom(4);
C11.setMarginLeft(4);C11.setMarginRight(4);C11.setMarginTop(4);C11.iC();C12.setDisplayPosition(2);C12.setLeft(4);C12.setParent(this);C12.setTabPosition(1);C12.setTabStop(false);C12.setTop(34);C12.setHeight(257);C12.setWidth(431);C12.iC();C13.setDisplayPosition(3);C13.setHeight(32);C13.setImage(rc1);C13.setLeft(183);C13.setParent(this);C13.setTabPosition(3);C13.setTabStop(false);C13.setTop(307);C13.setWidth(32);C13.setStyle(C0);C13.iC();C14.setDisplayPosition(4);C14.setHeight(32);C14.setImage(rc2);
C14.setLeft(223);C14.setParent(this);C14.setTabPosition(4);C14.setTabStop(false);C14.setTop(307);C14.setWidth(32);C14.setStyle(C0);C14.iC();C15.setDisplayPosition(1);C15.setHeight(32);C15.setImage(rc3);C15.setLeft(143);C15.setParent(this);C15.setTabPosition(5);C15.setTabStop(false);C15.setTop(307);C15.setWidth(32);C15.setStyle(C0);C15.iC();C16.setDisplayPosition(5);C16.setHeight(32);C16.setImage(rc4);C16.setLeft(263);C16.setParent(this);C16.setTabPosition(6);C16.setTabStop(false);C16.setTop(307);
C16.setWidth(32);C16.setStyle(C0);C16.iC();C13.aH("CLICK",this,e1);C14.aH("CLICK",this,e1);C15.aH("CLICK",this,e1);C16.aH("CLICK",this,e1);this.setHeight(353);this.setLeft(0);this.setTop(0);this.setWidth(441);this.setAutoClose(false);this.setAutoFocus(true);this.setCloseButton(true);this.setLayoutManager(C3);this.setTitleBar(true);this.setShroudStyle(C1);}});function e1(SENDER,Ps){var r=l.eR(this,cO,"#First.Click #Last.Click #Next.Click #Previous.Click",27);r.ln=27;{r.ln=29;{var eP=l.ePs();eP.cR("ITEM","PRIM_STR");
eP.r("ITEM").set(SENDER.getName());this.fE("NAVIGATING",eP);eP.e();}}r.ln=31;r.e();};cO.mthSHOWDETAILS=function(p0,p1,p2,p3){var m=this.REF,r=l.mR(this,cO,"ShowDetails",33);var P0=r.cPF("GIVENNAMES",Fd.F1.Dc);var P1=r.cPF("SURNAME",Fd.F2.Dc);var P2=r.cPF("ID",Fd.F3.Dc);var P3=r.cPF("THUMBNAIL",Fd.F4.Dc);P0.set(p0);P1.set(p1);P2.set(p2);P3.set(p3);r.ln=33;{r.ln=39;this.setCaption(l.s.Substitute("&1 &2 (&3)",P0.get(),P1.get(),P2.get()));r.ln=40;m.EMPLOYEEIMAGE.setImage(l.APPL().mthCREATEBITMAP(P3.get()));
r.ln=42;if(l.not(this.getIsOpen())){r.ln=44;this.mthSHOWPOPUP(u,u,"CENTER",u,u);}}r.ln=48;r.e();};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"XGIVENAME"});}{Fd.F2.Dc=function(){this.aN.call(this,Fd.F2);};l.cFC({co:Fd.F2.Dc,an:"PRIM_FLD",fn:"XSURNAME"});}{Fd.F3.Dc=function(){this.aN.call(this,Fd.F3);};l.cFC({co:Fd.F3.Dc,an:"PRIM_FLD",fn:"XEMPLOYID"});}{Fd.F4.Dc=function(){this.aN.call(this,Fd.F4);};l.cFC({co:Fd.F4.Dc,an:"PRIM_FLD",fn:"XEMPTHM"});}},{rp:["PRIM_PPNL","PRIM_VS.Style","PRIM_VS.SolidBrush","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_TBLO.Item","PRIM_IMAG","PRIM_FLD"]
});