LANSA.addComponent({id:"XDEMO_69",nm:"xDemoWebRevolvingBanner",ot:"rp",tp:"Reusable Part",de:"Revolving Banner",tl:14020001},function(l,oI,u){var cO=l.rC(oI,{an:"PRIM_PANL",pt:{Interval:{da:"na"}},mt:{AddImage:{ps:{"Image":{pt:"i"}}},CreateImage:{ps:{"Image":{pt:"i"}}},CreateLabel:{},Iterate:{},Activate:{ps:{"Item":{pt:"i"}}}},co:function(){cO.aN.call(this);var C0=this.cR("ROUNDLABEL","PRIM_VS","Style");var C1=this.cR("LAYOUT1","PRIM_TBLO");var C2=this.cR("LAYOUTCOLUMN1","PRIM_TBLO","Column");var C3=this.cR("LAYOUTROW1","PRIM_TBLO","Row");
var C4=this.cR("LAYOUTROW2","PRIM_TBLO","Row");var C5=this.cR("IMAGES","PRIM_ACOL");var C6=this.cR("LABELS","PRIM_ACOL");var C7=this.cR("LAYOUTITEMS","PRIM_ACOL");var C8=this.cR("TIMER","PRIM_TIMR");var C9=this.cR("ACTIVEIMAGE","PRIM_NMBR");C0.setCornerBottomLeft(10);C0.setCornerBottomRight(10);C0.setCornerTopLeft(10);C0.setCornerTopRight(10);C0.setBorderLeft(0);C0.setBorderTop(0);C0.setBorderRight(0);C0.setBorderBottom(0);C0.setCursor("HAND");C0.iC();C1.iC();C2.setDisplayPosition(1);C2.setParent(C1);
C2.iC();C3.setDisplayPosition(1);C3.setParent(C1);C3.iC();C4.setDisplayPosition(2);C4.setParent(C1);C4.setHeight(40);C4.setUnits("PIXELS");C4.iC();C5.setCollects("PRIM_IMAG");C5.iC();C6.setCollects("PRIM_LABL");C6.iC();C7.setCollects("PRIM_TBLO.Item");C7.iC();C8.setInterval(3000);C8.setStartup("MANUAL");C8.iC();C9.setValue(1);C9.iC();C6.aH("CLICK",this,e2);C8.aH("TICK",this,e3);this.setDisplayPosition(1);this.setHeight(393);this.setLeft(0);this.setTabPosition(1);this.setTop(0);this.setWidth(529);
this.setLayoutManager(C1);this.aH("CREATEINSTANCE",this,e1);}});cO.mthGETINTERVAL=function(){var m=this.REF,r=l.pR(this,cO,"GetInterval",21);var P0=r.cP("PROPERTY","PRIM_NMBR");r.ln=21;{r.ln=24;P0.set(m.TIMER.getInterval());}r.ln=26;return r.rV(P0.get());};cO.mthSETINTERVAL=function(p0){var m=this.REF,r=l.pR(this,cO,"SetInterval",28);var P0=r.cP("PROPERTY","PRIM_NMBR");P0.set(p0);r.ln=28;{r.ln=31;m.TIMER.setInterval(P0.get());}r.ln=33;r.e();};function e1(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Com_owner.CreateInstance",35);
r.ln=35;{r.ln=37;{var l1=this.getComponentMembers().cI();while(l1.step()){var MEMBER=r.sR("MEMBER",l1.item());if(l.nIo(MEMBER,"PRIM_IMAG")){continue;}r.ln=38;m.IMAGES.mthINSERT(MEMBER);r.ln=39;}l1.end();r.dR("MEMBER");}r.ln=41;{var l1=this.getComponentMembers().cI();while(l1.step()){var MEMBER=r.sR("MEMBER",l1.item());if(l.nIo(MEMBER,"PRIM_LABL")){continue;}r.ln=42;m.LABELS.mthINSERT(MEMBER);r.ln=43;}l1.end();r.dR("MEMBER");}}r.ln=45;r.e();};function e2(SENDER,Ps){var m=this.REF,r=l.eR(this,cO,"#Labels<>.Click",47);
r.ln=47;{r.ln=49;cO.mthACTIVATE.call(this,m.LABELS.getIndexOf(SENDER));r.ln=52;m.TIMER.mthSTOP();r.ln=53;m.TIMER.mthSTART();}r.ln=55;r.e();};function e3(sender,Ps){var r=l.eR(this,cO,"#Timer.Tick",57);r.ln=57;{r.ln=59;this.mthITERATE();}r.ln=61;r.e();};cO.mthADDIMAGE=function(p0){var m=this.REF,r=l.mR(this,cO,"AddImage",63);var P0=r.cPD("IMAGE");P0=p0;r.ln=63;{r.ln=66;cO.mthCREATEIMAGE.call(this,P0);r.ln=67;this.mthCREATELABEL();r.ln=69;if(l.n.gt(m.IMAGES.getItemCount(),1)){r.ln=71;m.TIMER.mthSTART();
}}r.ln=75;r.e();};cO.mthCREATEIMAGE=function(p0){var m=this.REF,r=l.mR(this,cO,"CreateImage",77);var P0=r.cPD("IMAGE");P0=p0;r.ln=77;{r.ln=81;m.IMAGES.mthINSERT(l.cC("PRIM_IMAG"));r.ln=82;m.IMAGES.getLast().setImage(P0);r.ln=83;m.IMAGES.getLast().setVisible(l.n.eq(m.IMAGES.getItemCount(),1));r.ln=84;m.IMAGES.getLast().setParent(this);r.ln=87;m.LAYOUTITEMS.mthINSERT(l.cC("PRIM_TBLO","Item"));r.ln=88;m.LAYOUTITEMS.getLast().setColumn(m.LAYOUTCOLUMN1);r.ln=89;m.LAYOUTITEMS.getLast().setRow(m.LAYOUTROW1);
r.ln=90;m.LAYOUTITEMS.getLast().setManage(m.IMAGES.getLast());r.ln=91;m.LAYOUTITEMS.getLast().setParent(m.LAYOUT1);r.ln=92;m.LAYOUTITEMS.getLast().setSizing("FITBOTH");}r.ln=94;r.e();};cO.mthCREATELABEL=function(){var m=this.REF,r=l.mR(this,cO,"CreateLabel",96);r.ln=96;{r.ln=99;m.LABELS.mthINSERT(l.cC("PRIM_LABL"));r.ln=100;m.LABELS.getLast().setParent(this);r.ln=101;m.LABELS.getLast().setStyle(m.ROUNDLABEL);r.ln=102;m.LABELS.getLast().setHeight(20);m.LABELS.getLast().setWidth(20);r.ln=104;if(l.n.eq(m.LABELS.getItemCount(),1))
{r.ln=105;m.LABELS.getLast().setThemeDrawStyle("MEDIUMTITLE");}else{r.ln=107;m.LABELS.getLast().setThemeDrawStyle("ALTERNATEITEM");}r.ln=111;m.LAYOUTITEMS.mthINSERT(l.cC("PRIM_TBLO","Item"));r.ln=112;m.LAYOUTITEMS.getLast().setColumn(m.LAYOUTCOLUMN1);r.ln=113;m.LAYOUTITEMS.getLast().setRow(m.LAYOUTROW2);r.ln=114;m.LAYOUTITEMS.getLast().setManage(m.LABELS.getLast());r.ln=115;m.LAYOUTITEMS.getLast().setParent(m.LAYOUT1);r.ln=116;m.LAYOUTITEMS.getLast().setSizing("NONE");r.ln=117;m.LAYOUTITEMS.getLast().setFlow("CENTERHORIZONTAL");
r.ln=118;m.LAYOUTITEMS.getLast().setMarginLeft(2);m.LAYOUTITEMS.getLast().setMarginRight(2);}r.ln=120;r.e();};cO.mthITERATE=function(){var m=this.REF,r=l.mR(this,cO,"Iterate",122);r.ln=122;{r.ln=124;if(l.tB(l.n.ge(m.ACTIVEIMAGE.get(),m.IMAGES.getItemCount()))){r.ln=126;cO.mthACTIVATE.call(this,1);}else{r.ln=130;cO.mthACTIVATE.call(this,l.add(m.ACTIVEIMAGE.get(),1));}}r.ln=134;r.e();};cO.mthACTIVATE=function(p0){var m=this.REF,r=l.mR(this,cO,"Activate",136);var P0=r.cP("ITEM","PRIM_NMBR");P0.set(p0);
r.ln=136;{r.ln=139;m.IMAGES.get(m.ACTIVEIMAGE.get()).mthFADEOUT(u,u,u);r.ln=140;m.LABELS.get(m.ACTIVEIMAGE.get()).setThemeDrawStyle("ALTERNATEITEM");r.ln=142;m.IMAGES.get(P0.get()).mthFADEIN(u,u);r.ln=143;m.LABELS.get(P0.get()).setThemeDrawStyle("MEDIUMTITLE");r.ln=145;m.ACTIVEIMAGE.set(P0.get());}r.ln=147;r.e();};cO.getINTERVAL=function(){return this.mthGETINTERVAL();};cO.setINTERVAL=function(v){this.mthSETINTERVAL(v);};},{rp:["PRIM_PANL","PRIM_VS.Style","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_ACOL","PRIM_TIMR","PRIM_NMBR"],
dp:["PRIM_ANIM"]});