window.LANSA.addSrc("menu",function(e,c,a,b,l){e.yb("PRIM_TBLO");e.yb("PRIM_PPNL");e.yb("PRIM_IMAG");e.yb("PRIM_SPBN");a.ZLa={Xdb:16,$db:16};a.FS={dxa:0,feb:1,geb:2,aeb:4};a.eH={KYb:0,ydb:1,xdb:2};a.eH.G={NONE:a.eH.KYb,BREAK:a.eH.ydb,BARBREAK:a.eH.xdb};a.fH={Ndb:25,Pdb:1,Kdb:2,Fyd:4,Qdb:8,Mdb:16};a.eH={iKc:0};a.jyd=3;a.iyd=2;a.kyd=255;a.UJc=768;a.wYb=256;a.vYb=512;a.VLa=65536;a.WLa=131072;a.mdb=262144;a.odb=524288;a.ndb=1048576;a.SHd=2;a.RHd=2;c.Jwa=function(){u.v.call(this);this.xD=null;this.g6=
a.ZLa.Xdb;this.IL=a.FS.dxa;this.dm=null;this.gc=[];this.UF=new c.sw;this.Qea=new c.qb;this.el=new c.hv;this.Aad=new c.O$;this.zad=new c.L2;this.Aad.Un(this.el);this.zad.Un(this.el);this.UF.Ik(this.el);this.Qea.Fj(b.H(255,255,255));this.Qea.sj(b.lc().wFb(a.l.Aj));this.Qea.Km(1);this.Qea.rn(1);this.Qea.Yl(1);this.Qea.ul(1);this.UF.Da(this,a.K.Ry,this.nnc);this.UF.vb(this.Qea)};var u=c.u(c.Jwa,c.rw);u.tb=function(){this.gc=null;u.j.tb.call(this)};u.R=function(){null!=this.xD&&this.CT();for(var a=null;null!=
(a=this.gc[0]);)a.Ia(null);b.CJc(this);u.j.R.call(this)};u.Qod=function(){return this.xD};u.Tod=function(){return this.gc};u.Sod=function(){return this.gc.length};u.p9=function(){return this};u.$Ec=function(){return 0!=(this.IL&a.FS.geb)};u.UDc=function(){return 0!=(this.IL&a.FS.aeb)};u.Vod=function(){return 0!=(this.IL&a.FS.feb)};u.nXc=function(){var b=this.IL&~a.FS.feb|a.FS.feb;this.IL!=b&&(this.IL=b,this.ea(a.a.h))};u.w4a=function(){return 0!=(this.g6&a.ZLa.$db)};u.iGd=function(b){b=this.g6&~a.ZLa.$db|
(b?a.ZLa.$db:0);this.g6!=b&&(this.g6=b,this.ea(a.a.h))};u.Paa=function(a){this.dm!=a&&(this.dm=a,this.ANa())};u.Itc=function(){return this.dm};u.LR=function(){return this.gc};u.g$=function(){return null!=this.xD||null!=this.Df};u.Rtd=function(){for(var a,b=this.gc,c=0;c<b.length&&null!=(a=b[c]);c++)if(!0==a.kb())return!0;return!1};u.jn=function(){null==this.Df&&this.vs(b.ab().ty(this));return this.Df};u.q8=function(b){var c=e.Nb();c.Rb("CONTEXT",b);this.za(a.K.Ry,c);c.hc()};u.Jy=function(b){this.g$()&&
this.CT();b.Ob=this;this.MRa(b);b.ya(this,this.jsa);this.ea(a.a.h)};u.mDc=function(b){this.g$()&&this.CT();b.Ob=this;this.MRa(b);b.ya(this,this.jsa);this.ea(a.a.h)};u.Caa=function(b){this.g$()&&this.CT();b.Ob=null;b.wa(this,this.jsa);this.MRa(b);this.ea(a.a.h)};u.$ua=function(){b.Q();this.CT()};u.H0b=function(a){if(null==this.xD){if(null!=this.Df)this.xD=this.Df;else{var c=b.Q().Wpa;this.xD=this.tZa();null!=this.xD&&(c[this.xD]=this)}this.KMa(null,a)}};u.CT=function(){if(null!=this.xD){for(var a,
c=this.gc,d=0;d<c.length&&null!=(a=c[d]);d++){var e=a.Gr;a.vs(null);a.aPc();e&&e.CT()}null!=this.xD&&(null!=this.Df?(this.vs(null),this.xD=null):(a=b.Q().Wpa,null!=this.xD&&delete a[this.xD]));this.xD=null;this.vs(null);b.Q().Qs(this.UF,!1)}};u.QMc=function(){};u.dfb=function(){};u.KMa=function(a,b){this.UF.hb(new c.ha(0,0,0,5));for(var d,e=0,f=this.gc,g=0;g<f.length&&null!=(d=f[g]);g++)e=this.Qfa(a,b,d,e)};u.Qfa=function(a,b,c,e,f){return c.Qfa(a,b,this,e,f)};u.$wb=function(a){for(var b=!1,c,e=this.gc,
f=0;f<e.length&&null!=(c=e[f]);f++)if(c==a||null!=c.Gr&&c.Gr.$wb(a)){b=!0;break}return b};u.NAc=function(b){for(var c=!1,d=null,e=this.gc,f=0;f<e.length&&null!=(d=e[f]);f++)if(d.Mb()&&d.ae()){var g=d.Gr;if(null!=g&&g.NAc(b)){c=!0;break}if(d.uqa!=a.Z.Aya&&d.uqa==b){d.vh();c=!0;break}}return c};u.Fhd=function(){for(var a=this.gc,b=null,c=null,e=0;e<a.length&&null!=(c=a[e]);e++)if(c.q1()){b=c;break}return b};u.MRa=function(a){var c=this.gc.indexOf(a);-1!=c&&this.gc.splice(c,1);c+=1;if(a.Ob==this){0==
a.Kf()&&(a.Mg=this.gc.length+1);var d=a.Kf(),e=0;0<c&&d>c&&d++;for(var f,c=this.gc,g=0;g<c.length&&null!=(f=c[g])&&!(f.Kf()>=d);g++)e++;this.gc.splice(e,0,a)}b.AJc(this)};u.Yka=function(b){b==a.kR&&(this.g$()&&this.CT(),this.R2(),this.ea(a.a.h))};u.R2=function(){for(var b,c=this.gc,d=0;d<c.length&&null!=(b=c[d]);d++)b.Mg=1,b.ea(a.a.h)};u.Ayd=function(a){var c=b.Q();return null!=c.Wpa?c.Wpa[a]:null};u.ANa=function(){};u.YMa=function(){b.Q().Qs(this.UF,!1)};u.dfb=function(){};u.ku=function(a){this.IL|=
a};u.yw=function(a){this.IL&=~a};u.mv=function(a,b){this.IL=this.IL&~a|(b?a:0)};u.Hzb=function(b,c){switch(c.Ya){case a.a.rb:this.Paa(null)}};u.jsa=function(){this.$Ec()?this.ku(a.FS.aeb):this.g$()&&(this.CT(),this.ea(a.a.h))};u.nnc=function(){this.dfb(null,this.UF)};e.ad(c.Jwa,"PRIM_MENU",{Va:{}});c.gcb=function(){p.v.call(this);this.Xw=null};var p=c.u(c.gcb,c.Jwa);p.tb=function(){p.j.tb.call(this)};p.R=function(){this.jba(null);p.j.R.call(this)};p.xHb=function(){return this.Xw};p.jba=function(b){this.Xw!=
b&&(this.Xw&&this.Xw.IBd(this),b&&b.zud(this),this.ea(a.a.h))};p.QMc=function(){this.q8(null)};p.KMa=function(a,b){this.UF.hb(new c.ha(0,0,0,5));for(var d,e=0,f=this.gc,g=0;g<f.length&&null!=(d=f[g]);g++)e=this.Qfa(a,b,d,e,!0)};p.tZa=function(){throw 0;};e.ad(c.gcb,"PRIM_MBAR",{Va:{}});c.icb=function(){r.v.call(this);this.ooa=null;this.kpb=0};var r=c.u(c.icb,c.Jwa);r.tb=function(){r.j.tb.call(this)};r.R=function(){this.ANa();r.j.R.call(this)};r.vFd=function(b){b!=this.kpb&&(this.kpb=b,this.ANa(),
this.ea(a.a.h))};r.Uid=function(){return this.kpb};r.Vrc=function(){null==this.ooa&&(this.ooa=[]);return this.ooa};r.KMa=function(a,b){this.UF.hb(new c.ha(0,0,0,5));for(var d,e=0,f=this.Vrc(),g=0;g<f.length&&null!=(d=f[g]);g++)e=this.Qfa(a,b,d,e);f=this.gc;for(g=0;g<f.length&&null!=(d=f[g]);g++)e=this.Qfa(a,b,d,e)};r.tZa=function(){return b.Zta()};r.nma=function(a,b){a===l&&(a=0);b===l&&(b=0);this.p_b(new c.sd(a,b),null,!0,null)};r.p_b=function(c,e){var d=b.Q(),f=!1,f=d.Jj,g=b.Q().Lt;this.q8(e,c);
b.ALa(a.kR);this.Paa(e);f&&this.mr(f,a.Ha.s$b);null!=g&&g.QW()&&g.KM();this.H0b(this.UF);0<this.UF.Qa()&&(f=d.qvb(!0),this.UF.i4(c.zb(),c.Ab(),a.bj.ww,l,null),d.qvb(f))};r.ANa=function(){this.CT();if(this.ooa){for(var a;null!=(a=this.ooa[0]);)b.ja(a);this.ooa=null}};r.Med=function(a,b){var c=b.dia();c&&c.Wzd(b.$h.KI)};e.ad(c.icb,"PRIM_PMNU",{Va:{},yc:{Show:r.nma}});c.NVb=function(){f.v.call(this);this.Xw=null};var f=c.u(c.NVb,c.Jwa);f.tb=function(){f.j.tb.call(this)};f.R=function(){this.Xw&&this.Xw.ajb(null);
f.j.R.call(this)};f.xHb=function(){return this.Xw};f.jba=function(b){if(this.Xw!=b&&!this.$wb(b)){var c=this.Xw;this.Xw=b;c&&c.Nvb(null);this.Xw&&this.Xw.Nvb(this);this.ea(a.a.h,a.be.Pva)}};f.w4a=function(){var a=f.j.w4a.call(this);a&&(a=this.Xw.mFc());return a};f.p9=function(){var a=null;this.Xw&&(a=this.Xw.p9());return a};f.YMa=function(){f.j.YMa.call(this);this.Xw.W().YMa()};f.tZa=function(){return b.Zta()};f.Z7c=function(){if(null!=this.xD)for(var a,b=this.gc,c=0;c<b.length&&null!=(a=b[c]);c++){var e=
a.Gr;e&&e.CT()}};f.dfb=function(b,c){this.ku(a.FS.geb);this.q8(null);this.ku(a.FS.geb);this.g$()&&this.UDc()&&(this.Z7c(),this.KMa(b,c));this.ku(a.FS.aeb)};e.ad(c.NVb,"PRIM_SMNU",{Va:{Parent:{f:f.xHb,i:f.jba}}});c.gVb=function(){g.v.call(this);this.Ob=null;this.Ie=a.fH.Ndb;this.eb=a.eH.iKc;this.Qe=a.VLa|a.WLa;this.uqa=a.Z.Aya;this.wbc=this.Mg=this.Uq=this.pdc=this.KI=0;this.u_=this.Ba=this.Gr=this.Ob=null;this.ib=this.cXa="";this.xP=new c.Ul;this.aCa=new c.ls;this.SZ=new c.qb;this.mI=new c.cH;this.M5=
b.Rc(null,this.xP,null,null,1,1);this.bCa=b.Rc(null,this.mI,null,null,1,1);this.hpa=b.Rc(null,this.aCa,null,null,1,1);this.aCa.vb(this.SZ);this.aCa.Ia(this.xP);this.mI.Ia(this.xP);this.xP.Da(this,a.K.fc,this.emc);this.tec()};var g=c.u(c.gVb,c.rw);g.tb=function(){this.qkc();g.j.tb.call(this)};g.R=function(){this.ajb(null);this.Ia(null);g.j.R.call(this);this.Xc(null);this.NWc()};g.Vld=function(){var a="";this.OEc()||null!=this.p9()&&this.p9()instanceof c.icb?a=this.Hb():this.Ssc();return a};g.Hb=function(){return this.ib};
g.vx=function(){return this.Hb().Jp()};g.Ssc=function(){this.Hb()};g.rkd=function(){return this.sqb};g.csd=function(){return!0};g.Cqd=function(){return!0};g.Hpd=function(){return!0};g.Hib=function(){var a=this.p9();a&&a.nXc()};g.ig=function(){return 0!=(this.Qe&a.mdb)?!0:!1};g.q1=function(){return 0!=(this.Qe&a.ndb)?!0:!1};g.uFd=function(b){b!=this.l8a()&&(this.Ie=this.Ie&~a.fH.Kdb|(b?a.fH.Kdb:0),this.ea(a.a.h))};g.SB=function(){return this.Uq};g.Kvc=function(){return this.wbc};g.kxc=function(){var b=
a.eH.KYb;0!=(this.Qe&a.wYb)?b=a.eH.ydb:0!=(this.Qe&a.vYb)&&(b=a.eH.xdb);return b};g.W=function(){return this.Ob};g.p9=function(){var a=null;this.Ob&&(a=this.Ob.p9());return a};g.jua=function(){return 0!=(this.Qe&a.odb)?!0:!1};g.prd=function(){return this.uqa};g.qrd=function(){return""};g.nzc=function(){return this.Gr};g.l5a=function(){return this.KI};g.Jsd=function(){return this.pdc};g.kb=function(){return 0!=(this.Qe&a.WLa)?!0:!1};g.Vb=function(a){this.ib!=a&&(this.ib=a,this.DX())};g.qs=function(a){this.Hb().TK(a)};
g.Ah=function(b){var c=this.SB();if(b&&0!=c&&null!=this.W())for(var d,e=this.W().gc,f=0;f<e.length&&null!=(d=e[f]);f++)d!=this&&d.SB()==c&&d.Ah(!1);b=b?this.Qe|a.mdb:this.Qe&~a.mdb;b!=this.Qe&&(this.Qe=b,this.ea(a.a.h))};g.lOa=function(b){b=b?this.Qe|a.ndb:this.Qe&~a.ndb;b!=this.Qe&&(this.Qe=b,this.ea(a.a.h))};g.Kf=function(){return this.Mg};g.Pe=function(b){this.l8a()||(null!=this.Ob?(this.Mg=b,this.Ob.MRa(this)):this.Mg!=b&&(this.Mg=b,this.ea(a.a.h)))};g.ae=function(){return 0!=(this.Qe&a.VLa)?
!0:!1};g.Qf=function(b){b=b?this.Qe|a.VLa:this.Qe&~a.VLa;b!=this.Qe&&(this.Qe=b,this.ea(a.a.h))};g.$X=function(b){this.Uq!=b&&(this.Uq=b,this.ea(a.a.h))};g.FWc=function(b){this.wbc=b;this.ea(a.a.h)};g.mXc=function(b){var c=this.Qe&~a.UJc;switch(b){case a.eH.ydb:c|=a.wYb;break;case a.eH.xdb:c|=a.vYb}c!=this.Qe&&(this.Qe=c,this.ea(a.a.h))};g.Ia=function(b){this.Ob!=b&&(this.Ob&&this.Ob.Caa(this),b&&(this.l8a()?b.mDc(this):b.Jy(this)),null!=this.Ba&&this.Hib(),this.ea(a.a.h,a.be.Pva))};g.Nib=function(b){b=
b?this.Qe|a.odb:this.Qe&~a.odb;b!=this.Qe&&(this.Qe=b,this.ea(a.a.h))};g.gYc=function(b){this.uqa!=b&&(this.uqa=b,this.ea(a.a.h))};g.ajb=function(a){this.Gr!=a&&(this.Gr&&this.Gr.jba(null),a&&a.jba(this))};g.mPa=function(b){this.KI!=b&&(this.KI=b,this.ea(a.a.h))};g.qHd=function(a){this.pdc=a};g.Bc=function(){return this.Ba};g.Xc=function(b){this.Ba!=b&&(null!=this.Ba&&(this.Ba.wa(this,this.Hl),this.Ba.xb()),this.Ba=b,null!=this.Ba&&(this.Ba.va(),this.Ba.ya(this,this.Hl)),this.Hib(),this.ea(a.a.h))};
g.NWc=function(){null!=this.u_&&(null!=this.u_&&(this.u_.wa(this,this.uAb),this.u_.xb()),this.u_=null,null!=this.u_&&(this.u_.va(),this.u_.ya(this,this.uAb)),this.Hib(),this.ea(a.a.h))};g.Vnd=function(){return this.u_};g.Jzc=function(){return this.cXa};g.hZc=function(b){this.cXa!=b&&(this.cXa=b,this.ea(a.a.h,a.be.cGc))};g.aJa=function(){return 0!=(this.Ie&a.fH.Pdb)?!0:!1};g.iZc=function(b){b!=this.aJa()&&(this.Ie=this.Ie&~a.fH.Pdb|(b?a.fH.Pdb:0),this.ea(a.a.h))};g.Q5a=function(){return 0!=(this.Ie&
a.fH.Qdb)?!0:!1};g.jZc=function(b){b!=this.Q5a()&&(this.Ie=this.Ie&~a.fH.Qdb|(b?a.fH.Qdb:0),this.ea(a.a.h))};g.krd=function(){return!0};g.yha=function(){return 0!=(this.Ie&a.fH.Mdb)?!0:!1};g.X2b=function(b){b!=this.yha()&&(this.Ie=this.Ie&~a.fH.Mdb|(b?a.fH.Mdb:0),this.ea(a.a.h))};g.Jb=function(b){b=b?this.Qe|a.WLa:this.Qe&~a.WLa;b!=this.Qe&&(this.Qe=b,this.ea(a.a.h))};g.VHb=function(){return this.kd};g.jn=function(){null==this.Df&&this.vs(b.ab().ty(this));return this.Df};g.Mb=function(){return null!=
this.Ob&&this.Ob.g$()?!0:!1};g.rvd=function(){return"-"==this.Hb()?!0:!1};g.l8a=function(){return 0!=(this.Ie&a.fH.Kdb)?!0:!1};g.mFc=function(){var a=this.aJa();if(a&&this.Q5a()){var b=this.W();b&&(a=b.w4a())}return a};g.OEc=function(){return null!=this.W()&&this.W()instanceof c.gcb};g.vh=function(b){b===l&&(b=null);var c=e.Nb();c.Rb("CONTEXT",b);this.za(a.K.fc,c);c.hc()};g.wJd=function(){if(this.Gr)for(var a,b=this.Gr.gc,c=0;c<b.length&&null!=(a=b[c]);c++)a.Ah(!1)};g.Nvb=function(b){this.Gr!=b&&
(this.Gr&&(this.Gr.Xw==this?this.Gr.jba(null):(this.ea(a.a.HKc),this.Gr.wa(this,this.tBb),this.Gr=null)),b&&(b.Xw!=this?b.jba(this):(this.Gr=b,this.Gr.ya(this,this.tBb))),this.ea(a.a.h))};g.Cyd=function(a){return b.Q().VCa[a]};g.tec=function(){this.sqb=b.Q().mvb();b.Q().VCa[this.sqb]=this};g.Qfa=function(a,b,c,e){return this.Nec(b,e)};g.aPc=function(){this.xP.Ia(null)};g.Nec=function(b,e){if(this.kb()){var d=b.Tk(),f=null;this.SZ.fp(a.l.Fd);this.SZ.Fj(a.l.Fd);this.SZ.Km(1);this.SZ.rn(1);this.SZ.Yl(1);
this.SZ.ul(1);this.ig()&&(f=this.jua()?a.Qb.WYb:a.Qb.VYb,this.SZ.fp(a.l.rT),this.SZ.Fj(a.l.q4));this.Bc()&&(f=this.Bc());this.M5.Ia(d);this.M5.Eo(d.Jc(0));this.M5.Do(d.Tc(0));this.M5.qi(a.ta.Cj);this.M5.Kb(a.Ea.YD);this.M5.$b(a.ka.si);this.M5.Ke(4);this.M5.ue(2);this.hpa.Ia(d);this.hpa.Eo(d.Jc(0));this.hpa.Do(d.Tc(0));this.hpa.$b(a.ka.Sd);this.hpa.Kb(a.Ea.gl);this.hpa.Ke(2);this.bCa.Ia(d);this.bCa.Eo(d.Jc(0));this.bCa.Do(d.Tc(0));this.bCa.$b(a.ka.pf);this.bCa.Ke(22);this.xP.Ia(b);this.xP.Ik(d);this.xP.Pe(e+
1);this.xP.zO(this.aJa()?this.cXa:"");this.mI.zK(!1);this.mI.Up(a.Yd.AX);this.mI.LOa(a.vC.$wa);this.mI.bF(a.ws.WI);this.mI.Vb(this.Hb());this.mI.Lm(a.Wg.aq);this.mI.jY(this.Gr?this.Gr.UF:null);this.aCa.Ni(f);this.mI.Hk(!1,!0);d=60+this.mI.zR();f=10+this.mI.uha();this.xP.Ac(f);this.aCa.hb(new c.ha(2,2,18,18));this.mI.hb(new c.ha(22,2,d,18));b.Wb(Math.max(b.Sa(),d));b.Ac(b.Qa()+this.xP.Qa());null!=this.Gr&&this.Gr.H0b(this.Gr.UF);e++}return e};g.qkc=function(){delete b.Q().VCa[this.sqb];b.Q()};g.BJd=
function(a){this.Pe(a);null!=this.Ob&&this.Ob.R2()};g.DX=function(){this.ea(a.a.h,a.be.aOb)};g.emc=function(a,b){this.SB()&&this.Ah(!0);this.vh();this.W()&&this.W().YMa();b.HANDLED.set(!0)};g.tBb=function(){this.Mb()&&this.ea(a.a.h)};g.Hl=function(b,c){switch(c.Ya){case a.a.rb:case a.a.Pb:this.Xc(null)}};g.uAb=function(b,c){switch(c.Ya){case a.a.rb:case a.a.Pb:this.Xc(null)}};e.ad(c.gVb,"PRIM_MITM",{Va:{Parent:{f:g.W,i:g.Ia},Caption:{f:g.Hb,i:function(a){this.Vb(e.ma(a))}},Checked:{f:g.ig,i:function(a){this.Ah(e.Ja(a))}},
Default:{f:g.q1,i:function(a){this.lOa(e.Ja(a))}},GroupIndex:{f:g.SB,i:function(a){this.$X(e.aa(a))}},HelpContext:{f:g.Kvc,i:function(a){this.FWc(e.aa(a))}},MenuBreak:{f:function(){return e.Ga(this.kxc(),a.eH.G)},i:function(b){this.mXc(e.Aa(b,a.eH.G))}},RadioItem:{f:g.jua,i:function(a){this.Nib(e.Ja(a))}},SubMenu:{f:g.nzc,i:g.ajb},ShortCut:{f:function(){return e.Ga(this.uqa,a.Z.G)},i:function(b){this.gYc(e.Aa(b,a.Z.G))}},Tag:{f:g.l5a,i:function(a){this.mPa(e.aa(a))}},Tip:{f:g.Jzc,i:function(a){this.hZc(e.ma(a))}},
TipShow:{f:g.aJa,i:function(a){this.iZc(e.Ja(a))}},TipShowOfParent:{f:g.Q5a,i:function(a){this.jZc(e.Ja(a))}},Enabled:{f:g.ae,i:function(a){this.Qf(e.Ja(a))}},Visible:{f:g.kb,i:function(a){this.Jb(e.Ja(a))}},DisplayPosition:{f:g.Kf,i:function(a){this.Pe(e.aa(a))}},Image:{f:g.Bc,i:g.Xc}}})},{rp:["PRIM_TBLO","PRIM_PPNL","PRIM_IMAG","PRIM_SPBN"]});
