window.LANSA.addSrc("gpbx",function(e,c,a,b){a.Rpc={jLd:0,iLd:9,x$c:6,kLd:5,lLd:10};a.qAc={Trc:0};c.xUb=function(){l.v.call(this);this.irb=a.Rpc.x$c;this.KF=a.qAc.Trc;this.aG=new c.ha;this.Lc=this.Lc|a.Sb.n$|a.Sb.Hva|a.Sb.O9a|a.Sb.oC|a.Sb.pS|a.Sb.nC;this.Xg=this.Xg|a.Qh.eO|a.Qh.$W;this.Ve(!1)};var l=c.u(c.xUb,c.zS);l.yg=function(){return c.IXb};l.NFd=function(b){this.irb!=b&&(this.irb=b,this.m(a.a.h),this.fu())};l.$md=function(){return this.irb};l.cp=function(a){l.j.cp.call(this,a);this.HLc()};l.Enb=
function(){if(this.Mb()){var a=this.Od(),a=Math.abs(a.Qa()),c=this.ve();this.wd();this.wd();c.Ta(c.O()+a);""==this.Hb()?(c.Oa(c.O()),c.xa(a)):(this.Hb(),c.Oa(c.O()+this.zR()),c.xa(this.uha()),c.Oa(c.qa+a));b.yo(this.aG,c)||(this.aG=c,this.pb());this.cp(!0)}};l.pe=function(a){a.Ua(a.M()+this.aG.ba());a.Ta(a.O()+4);a.Oa(a.qa-4);a.xa(a.pa-4);l.j.pe.call(this,a)};l.xOc=function(a,b,c){a.Ua(a.M()+this.aG.ba());a.Ta(a.O()+4);a.Oa(a.qa-4);a.xa(a.pa-4);l.j.xOc.call(this,a,b,c)};l.zi=function(){l.j.zi.call(this);
this.Bd(a.U.Ix)};l.Wc=function(){var b=this.OJ()||this.ek()&&(this.WW()||this.dO());this.dG(a.Sb.UJ,b);l.j.Wc.call(this)};l.zC=function(a){var b=!1,b=a.xe().jNa(this,this.fa.Th,this.WW(),this.dO(),a);!1==b&&l.j.zC.call(this,a)};l.LS=function(a){var b=!1;null!=a.xe()&&a.Ca().ek()&&(b=a.xe().kNa(this,this.fa.Th,a,this.WW(),this.dO()));!1==b&&l.j.LS.call(this,a)};l.Td=function(b){""==b[1]&&(b[1]=a.tOb);l.j.Td.call(this,b)};l.HLc=function(){var a=this.ve(),a=this.Tz(a,null),c=this.ve();c.Ua(c.M()+this.aG.ba()/
2+1);c.Ta(c.O()+2);c.Oa(c.qa-2);c.xa(c.pa-2);var e=this.Na().gb(),g=this.Hb();b.Gd[e].ng(g,c,this.aG);b.ja(a)};l.rq=l[a.U.KE]=function(a){this.Enb();l.j.rq.call(this,a)};l.fr=l[a.U.pC]=function(){l.j.fr.call(this);this.Enb()};l.iE=l[a.U.Ix]=function(){this.Enb();this.fu()};l.Fnc=l[a.U.s$a]=function(){this.Kg()};e.ad(c.xUb,"PRIM_GPBX",{Va:{Caption:{f:l.Hb,i:function(a){this.Vb(e.ma(a))}},ThemeStyle:{f:function(){return e.Ga(this.FJ(),a.Et.G)},i:function(b){this.oza(e.Aa(b,a.Et.G))}}}});c.IXb=function(a){u.v.call(this,
a);this.ib=this.DSa=this.mBa=this.Pd=this.Ec=null};var u=c.u(c.IXb,c.N2);u.Ye=function(a,b){var c=null;u.j.Ye.call(this,a,b);this.DSa=4;this.Ec=document.createElement("div");this.Pd=document.createElement("div");this.mBa=document.createElement("div");this.ib=document.createElement("span");this.w.appendChild(this.Ec);this.w.appendChild(this.Pd);this.w.appendChild(this.mBa);this.w.appendChild(this.ib);this.N7a(this.Ec,this.DSa);this.N7a(this.Pd,0);this.N7a(this.mBa,0);c=this.Ec.style;c.borderTopWidth=
"0px";c=this.Pd.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.mBa.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.ib.style;c.position="absolute";c.whiteSpace="nowrap";c.cursor="inherit";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";return this.w};u.N7a=function(a,b){var c=a.style;c.position="absolute";c.overflowX="hidden";c.overflowY=
"hidden";c.whiteSpace="nowrap";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.outline="none";c.background="rgba(0,0,0,0)";c.borderTopWidth="1px";c.borderBottomWidth="1px";c.borderLeftWidth="1px";c.borderRightWidth="1px";c.borderTopLeftRadius=b+"px";c.webkitBorderTopLeftRadius=b+"px";c.borderTopRightRadius=b+"px";c.webkitBorderTopRightRadius=b+"px";c.borderBottomLeftRadius=b+"px";c.webkitBorderBottomLeftRadius=b+"px";c.borderBottomRightRadius=
b+"px";c.webkitBorderBottomRightRadius=b+"px"};u.ng=function(a,b,c){var e=this.Ec.style;e.left=b.O()+"px";e.top=b.M()+"px";e.width=b.$()+"px";e.height=b.ba()+"px";e.borderColor=this.Ck();e=this.Pd.style;e.left=b.O()+this.DSa-1+"px";e.top=b.M()+"px";e.width=c.O()-b.O()+"px";e.height="1px";e.borderColor=this.Ck();e=this.mBa.style;e.left=c.qa+2+"px";e.top=b.M()+"px";e.width=b.qa-this.DSa-c.qa+"px";e.height="1px";e.borderColor=this.Ck();e=this.ib.style;e.left=c.O()+7+"px";e.top=c.M()+2+"px";e.height=
c.ba()+"px";e.width=c.$()+"px";this.ib.textContent=a}});
