window.LANSA.addSrc("msg",function(e,c,a,b,l){e.yb("PRIM_PPNL");a.Eka={P2:0,yKc:1,AKc:2,vKc:4,wKc:8};a.Eka.G={NONE:a.Eka.P2,TEXT:a.Eka.yKc,WARNING:a.Eka.AKc,ERROR:a.Eka.vKc,FATAL:a.Eka.wKc};a.tX={LYb:1,NYb:2,MYb:4};a.tX.G={ERROR:a.tX.LYb,QUESTION:a.tX.NYb,INFORMATION:a.tX.MYb};a.Gn={jcd:16,vYa:1,TEa:16,QEa:32,VEa:64,SEa:128,UEa:256,REa:512};a.Gn.G={NONE:a.Gn.vYa,OK:a.Gn.TEa,CANCEL:a.Gn.QEa,YES:a.Gn.VEa,NO:a.Gn.SEa,RETRY:a.Gn.UEa,IGNORE:a.Gn.REa};a.RE={zdb:16,PYb:48,QYb:192,RYb:224,OYb:768};a.RE.G=
{OK:a.RE.zdb,OKCANCEL:a.RE.PYb,YESNO:a.RE.QYb,YESNOCANCEL:a.RE.RYb,IGNORERETRY:a.RE.OYb};c.YSb=function(){u.v.call(this)};var u=c.u(c.YSb,c.ld);e.ad(c.YSb,"PRIM_MSG",{});c.vab=function(){p.v.call(this);this.pB=[]};var p=c.u(c.vab,c.ld);p.oxc=function(){e.yb("PRIM_PCOL");var a=new c.aRb(this);return new c.lX(a)};p.Sg=function(a,b){var e=new c.wab(this,a);this.pB.push(e);e.fi(b);this.hrc(e);return e};p.mo=function(a){if(a)for(var b=0;b<this.pB.length;b++){var c=this.pB[b];c.Ca()==a&&(this.nFb(c),this.pB.splice(b--,
1),c.Syb())}};p.Whc=function(){for(;0<this.pB.length;){var a=this.pB.shift();this.nFb(a);a.Syb()}};p.hrc=function(b){var c=e.Nb();c.Rb("MESSAGE",b);this.za(a.K.fKc,c);c.hc()};p.nFb=function(b){var c=e.Nb();c.Rb("MESSAGE",b);this.za(a.K.gKc,c);c.hc()};e.ad(c.vab,"PRIM_MSGQ",{Va:{Messages:{f:p.oxc}},yc:{Add:function(a,b){return this.Sg(e.ma(a),b===l?null:b)},Clear:function(a){return this.mo(a===l?null:a)},ClearAll:function(){return this.Whc()}}});c.aRb=function(a){r.v.call(this);this.YCa=a};var r=c.u(c.aRb,
c.G$);r.wc=function(){return this.YCa.pB.length};r.cw=function(a){return this.YCa.pB[a]};c.wab=function(a,b){f.v.call(this);this.YCa=a;this.pg=b;this.Xa=null};var f=c.u(c.wab,c.ld);f.Jp=function(){return this.pg};f.Ca=function(){return this.Xa};f.fi=function(a){this.Of()&&this.Xa!=a&&(null!=this.Xa&&(this.Xa.uK(this),this.Xa.wa(this,this.In)),this.Xa=a)&&(a.RI(this),a.ya(this,this.In))};f.Of=function(){return null!==this.YCa};f.Syb=function(){this.fi(null);this.pg="";this.YCa=null};f.In=function(b,
c){switch(c.Ya){case a.a.rb:this.fi(null)}};e.ub(c.wab,"PRIM_MSGQ","Message",{Va:{Text:{f:f.Jp},Control:{f:f.Ca,i:f.fi}}});c.bXb=function(){g.v.call(this);this.Hoa=[]};var g=c.u(c.bXb,c.ld);g.R=function(){this.Uj();g.j.R.call(this)};g.we=function(a){return this.Hoa[a]};g.wc=function(){return this.Hoa.length};g.Sg=function(b){this.Hoa.push(b);this.m(a.a.h)};g.Uj=function(){this.Hoa=[];this.m(a.a.h)};g.$wc=function(){for(var a="",b=0;b<this.Hoa.length;b++){var c=this.Hoa[b];c.length>a.length&&(a=c)}return a};
e.ub(c.bXb,"PRIM_WEB","MessageBoxCaptions",{yc:{Add:g.Sg,RemoveAll:g.Uj}});c.aXb=function(){m.v.call(this);e.yb("PRIM_PHBN");e.yb("PRIM_LABL");this.LDa=this.I6=this.Efa=null;this.XCa=a.tX.MYb;this.nz=a.RE.zdb;this.Ee=a.Gn.vYa;this.JSa=[];this.tP=null;this.aXa=new c.lr;this.$Wa=new c.mO;this.wB=new c.Ul;this.GF=e.he("PRIM_WEB","MessageBoxCaptions");this.GF.va();this.GF.ya(this,this.Czb);this.og=new c.Ubb;this.hL=new c.mO;this.SF=new c.mO;this.OI=new c.mO;this.LL=new c.mO;this.VL=new c.mO;this.xI=new c.mO;
this.SF.Da(this,a.K.fc,this.Tmc);this.hL.Da(this,a.K.fc,this.flc);this.OI.Da(this,a.K.fc,this.Goc);this.LL.Da(this,a.K.fc,this.Rmc);this.VL.Da(this,a.K.fc,this.wnc);this.xI.Da(this,a.K.fc,this.tmc);this.wB.Ia(this);this.og.Ia(this);this.hL.Ia(this);this.SF.Ia(this);this.OI.Ia(this);this.LL.Ia(this);this.VL.Ia(this);this.xI.Ia(this);this.I6=new c.qb;this.LDa=new c.Uf;this.I6.od(this.LDa);this.LDa.xd(a.l.PO);this.LDa.Wf(9);this.o4b(this.I6);this.I6.va();this.LDa.va();this.wB.Ta(90);this.wB.Ve(!1);this.wB.Ua(57);
this.wB.Jb(!0);this.wB.mT(!0);this.wB.dY(!0);this.og.Pe(6);this.og.KC(a.Wg.aq);this.og.Ta(20);this.og.Ua(57);this.og.tt(64);this.og.KK(64);this.og.Ac(64);this.og.Wb(64);this.og.Ve(!1);this.SF.Vb(b.lm().ok||"OK");this.LL.Vb(b.lm().no||"No");this.OI.Vb(b.lm().yes||"Yes");this.VL.Vb(b.lm().retry||"Retry");this.hL.Vb(b.lm().cancel||"Cancel");this.xI.Vb(b.lm().ignore||"Ignore");this.K2b(this.nz);this.WNa(!1);this.fjb(!0)};var m=c.u(c.aXb,c.sw);m.R=function(){this.GF.wa(this,this.Czb);this.GF.xb();this.GF=
null;this.lyb();m.j.R.call(this)};m.ZUc=function(a){this.aXa.vb(a)};m.Qsc=function(){return this.aXa.Mf()};m.Rsc=function(){return this.aXa.qj()};m.tha=function(){return this.$Wa.Mf()};m.bF=function(a){this.$Wa.vb(a)};m.Ksc=function(){return this.$Wa.qj()};m.pza=function(b){b!=this.WR()&&(this.Vb(b),this.NRa(),this.m(a.a.h))};m.WR=function(){return this.Hb()};m.oXc=function(b){this.GF.Uj();b!=this.yHb()&&(this.GF.Sg(b),this.m(a.a.h))};m.Tsc=function(){return this.GF};m.yHb=function(){return 0<this.GF.wc()?
this.GF.we(0):""};m.$2b=function(b){this.tP!==b&&(null!=this.tP&&(this.tP.wa(this,this.Qzb),this.tP.xb()),this.tP=b,null!==this.tP&&(this.tP.va(),this.tP.ya(this,this.Qzb)),this.NRa(),this.m(a.a.h))};m.Ntc=function(){return this.tP};m.pXc=function(b){this.XCa!=b&&(this.XCa=b,this.NRa(),this.m(a.a.h))};m.Xod=function(){return this.XCa};m.K2b=function(b){this.nz=b;this.SF.Jb(0!=(this.nz&a.Gn.TEa));this.hL.Jb(0!=(this.nz&a.Gn.QEa));this.OI.Jb(0!=(this.nz&a.Gn.VEa));this.LL.Jb(0!=(this.nz&a.Gn.SEa));
this.xI.Jb(0!=(this.nz&a.Gn.REa));this.VL.Jb(0!=(this.nz&a.Gn.UEa))};m.Ejd=function(){return this.nz};m.wGd=function(a){this.Ee=a};m.Iqd=function(){return this.Ee};m.rjc=function(b,e,f){var k=new c.lr;k.Ia(this.wB);k.Ta(0);k.Ve(!1);k.Ua(e);k.Lm(a.Wg.aq);k.Wb(f.Sa());k.Ac(f.Qa());k.lh(!1);k.Vb(b);return k};m.h5b=function(a,e){var f=b.gv(0,0),k=new c.ha(0,0,0,0);b.AA(a,k,0,e);f.Wb(k.$()+2);f.Ac(k.ba()+2);return f};m.lyc=function(){if(null!=this.tP)return this.tP;var d="";switch(this.XCa){case a.tX.LYb:d=
"lansa_error.png";break;case a.tX.NYb:d="lansa_question.png";break;default:d="lansa_information.png"}var e=new c.ZJ;e.pu(b.mc(d));return e};m.Sec=function(){var a=this.$Wa.qj().Za.aC(),b=null;this.SF.qj().Uj();this.hL.qj().Uj();this.OI.qj().Uj();this.LL.qj().Uj();this.VL.qj().Uj();this.xI.qj().Uj();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.SF.qj().Sg(b),this.hL.qj().Sg(b),this.OI.qj().Sg(b),this.LL.qj().Sg(b),this.VL.qj().Sg(b),this.xI.qj().Sg(b);this.SF.Hk(!1,!0);this.hL.Hk(!1,!0);
this.OI.Hk(!1,!0);this.LL.Hk(!1,!0);this.VL.Hk(!1,!0);this.xI.Hk(!1,!0)};m.Yec=function(){var a=this.aXa.qj().Za.aC(),b=null;this.wB.qj().Uj();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.wB.qj().Sg(b);this.wB.Hk(!1,!0)};m.nma=function(){this.Efa=b.LO();this.Ee=a.Gn.vYa;this.pxb();var c=b.rl();this.Px(a.bj.oaa,null,c,null);this.WVc()};m.NRa=function(){this.VW()&&(this.pxb(),this.tg())};m.pxb=function(){var a;this.lyb();this.og.Xc(this.lyc());this.Sec();this.Yec();a=this.kvb();this.iMc(a)};
m.hya=function(){this.kvb();m.j.hya.call(this)};m.kvb=function(){var a=this.sy(),b=this.rhc(),c=this.xhc(),c=this.whc(c),e=this.thc(a),f=this.shc(b),k=this.zhc(c,e,f);this.yQc(k,b,e);this.xec(b,c,f,k);return a};m.yQc=function(a,b,c){this.Wb(a.Sa());this.Ac(a.Qa());a=b.Sa();b=b.Qa();this.hL.Wb(a);this.SF.Wb(a);this.OI.Wb(a);this.LL.Wb(a);this.VL.Wb(a);this.xI.Wb(a);this.hL.Ac(b);this.SF.Ac(b);this.OI.Ac(b);this.LL.Ac(b);this.VL.Ac(b);this.xI.Ac(b);this.wB.Wb(c.Sa());this.wB.Ac(c.Qa())};m.xec=function(a,
b,c,e){this.XUc(a);a=e.Qa()-c.Qa();this.hL.Ua(a);this.SF.Ua(a);this.OI.Ua(a);this.LL.Ua(a);this.VL.Ua(a);this.xI.Ua(a);this.og.Ta(20);this.og.Ua(this.xp.Qa()+20);this.wB.Ta(40+b.Sa());this.wB.Ua(this.xp.Qa()+20)};m.zhc=function(a,c,e){var f=b.uC(),h=b.gv(0,0);a=this.vhc(a,c);c=this.my.YIa(this.my.Hb(),this.my.vx().length)+10;h.Wb(Math.max(a.Sa(),c,e.Sa())+60);h.Ac(this.xp.Qa()+a.Qa()+e.Qa()+40);h.Wb(Math.min(f.$()-40,h.Sa()));h.Ac(Math.min(f.ba()-40,h.Qa()));return h};m.Yha=function(a,b){var c=a;
b.length>a.length&&(c=b);return c};m.Zwc=function(){var a="",a=this.Yha(this.SF.Hb(),a),a=this.Yha(this.hL.Hb(),a),a=this.Yha(this.OI.Hb(),a),a=this.Yha(this.LL.Hb(),a),a=this.Yha(this.VL.Hb(),a),a=this.Yha(this.xI.Hb(),a);return" "+a+" "};m.rhc=function(){var a=this.Zwc(),c=b.gv(0,0),c=this.SF.Od();return c=this.h5b(a,c)};m.sy=function(){var a=this.GF.$wc(),c=b.gv(0,0),c=this.wB.Od();return c=this.h5b(a,c)};m.xhc=function(){var a=b.gv(0,0);a.Wb(this.og.Sa());a.Ac(this.og.Qa());return a};m.thc=function(a){var c=
b.gv(0,0),e=a.Sa()+4;a=this.GF.wc()*(a.Qa()+4);e+=20;a+=20;e=170>e?170:e;a=70>a?70:a;a=630<a?630:a;c.Wb(630<e?630:e);c.Ac(a);return c};m.whc=function(a){var c=b.gv(0,0);c.Ac(a.Qa()+16);c.Wb(a.Sa()+8);return c};m.vhc=function(a,c){var e=b.gv(0,0);e.Ac(Math.max(a.Qa(),c.Qa()));e.Wb(2+a.Sa()+2+c.Sa()+2);return e};m.shc=function(a){var c=b.gv(0,0),e=25>a.Qa()?25:a.Qa();a.Wb(66>a.Sa()?66:a.Sa());a.Ac(e);c.Ac(a.Qa()+24);c.Wb(3*a.Sa()+8);return c};m.XUc=function(b){b=b.Sa()+20;var c=1;this.nz&a.Gn.UEa&&
(this.VL.Ta(this.Sa()-c*b),++c);this.nz&a.Gn.REa&&(this.xI.Ta(this.Sa()-c*b),++c);this.nz&a.Gn.QEa&&(this.hL.Ta(this.Sa()-c*b),++c);this.nz&a.Gn.TEa&&(this.SF.Ta(this.Sa()-c*b),++c);this.nz&a.Gn.SEa&&(this.LL.Ta(this.Sa()-c*b),++c);this.nz&a.Gn.VEa&&this.OI.Ta(this.Sa()-c*b)};m.iMc=function(a){for(var b=0,c=a.Qa(),e=0;e<this.GF.wc();e++)this.JSa.push(this.rjc(this.GF.we(e),b,a)),b+=c};m.WVc=function(){switch(this.nz){case a.RE.zdb:case a.RE.PYb:this.SF.Ge(!0,!0);break;case a.RE.QYb:case a.RE.RYb:this.OI.Ge(!0,
!0);break;case a.RE.OYb:this.xI.Ge(!0,!0)}};m.Dia=function(a){this.Ee=a;this.Em();b.Dw(this.Efa);this.Efa=null};m.lyb=function(){for(var a=0;a<this.JSa.length;++a)this.JSa[a].Ia(null);this.JSa=[]};m.Czb=function(){this.NRa()};m.Tmc=function(){this.Dia(a.Gn.TEa)};m.flc=function(){this.Dia(a.Gn.QEa)};m.Goc=function(){this.Dia(a.Gn.VEa)};m.Rmc=function(){this.Dia(a.Gn.SEa)};m.wnc=function(){this.Dia(a.Gn.UEa)};m.tmc=function(){this.Dia(a.Gn.REa)};m.Qzb=function(b,c){switch(c.Ya){case a.a.rb:case a.a.Pb:this.$2b(null);
break;case a.a.h:this.m(a.a.h)}};e.ub(c.aXb,"PRIM_WEB","MessageBox",{Va:{Title:{f:m.WR,i:function(a){this.pza(e.ma(a))}},Caption:{f:m.yHb,i:function(a){this.oXc(e.ma(a))}},Text:{f:m.Jp,i:function(a){this.TK(e.ma(a))}},Captions:{f:m.Tsc},Image:{f:function(){return e.Ga(this.XCa,a.tX.G)},i:function(b){this.pXc(e.Aa(b,a.tX.G))}},CustomImage:{f:m.Ntc,i:function(a){this.$2b(a)}},Result:{f:function(){return e.Ga(this.Ee,a.Gn.G)}},Buttons:{f:function(){return e.Ga(this.nz,a.RE.G)},i:function(b){this.K2b(e.Aa(b,
a.RE.G))}},CaptionStyle:{f:m.Qsc,i:function(a){this.ZUc(a)}},CaptionStyles:{f:m.Rsc},ButtonStyle:{f:m.tha,i:function(a){this.bF(a)}},ButtonStyles:{f:m.Ksc}},yc:{Show:m.nma}});c.Gbb=function(b){k.v.call(this);this.gVa=[];this.pB=[];this.Xa=b;this.Pc=new c.sw;this.Pc.Da(this,a.K.Ry,this.O7);this.Pc.Da(this,a.K.hga,this.A0a);this.Pea=new c.Ul;this.Pea.hb(new c.ha(0,0,100,25));this.Pea.Ia(this.Pc);this.Pea.Ve(!1);this.Pea.ic(a.IOb)};var k=c.u(c.Gbb,c.aj);k.tq=function(){return this.Pc};k.cg=function(){return 0==
this.pB.length};k.RI=function(a){this.pB.push(a)};k.uK=function(a){this.pB.splice(this.pB.indexOf(a),1);this.cg()&&this.Pc.Em()};k.O7=function(){e.yb("PRIM_LABL");for(var b=0,f=6,k=100;b<this.pB.length;b++){var g=this.gVa[b],h=this.pB[b];g||(g=new c.lr,g.Ta(5),g.Ve(!1),g.Ua(f),g.Lm(a.Wg.aq),g.Wb(320),g.Ac(20),g.lh(!1),this.gVa.push(g));g.Ia(this.Pea);g.Vb(h.Jp());g.Phc();k<g.Sa()+15&&(k=g.Sa()+15);f+=25}for(;b<this.gVa.length;b++)g=this.gVa[b],g.Ia(null);this.Pea.Ac(f+6);this.Pea.Wb(k);this.Pc.Ac(f+
6);this.Pc.Wb(k)};k.A0a=function(){this.Xa.Hk(!0)}},{rp:["PRIM_PPNL"]});
