window.LANSA.addSrc("http",function(e,c,a,b,l){c.Vcb=function(){u.v.call(this);this.$a=this.isb=""};var u=c.u(c.Vcb,c.ld);u.R=function(){u.j.R.call(this)};u.Vha=function(){return this.isb};u.s3b=function(a){this.isb=a};u.La=function(){return this.$a};u.Wa=function(a){this.$a=a};e.ub(c.Vcb,"PRIM_WEB","HttpHeader",{Va:{Key:{f:u.Vha,i:function(a){this.s3b(e.ma(a))}},Value:{f:u.La,i:function(a){this.Wa(e.ma(a))}}}});c.ILa=function(){p.v.call(this);this.bb=[]};var p=c.u(c.ILa,c.ld);p.wc=function(){return this.bb.length};
p.we=function(a){for(var c=0;c<this.wc();c++){var d=this.Hp(c);if(b.YG(d.Vha(),a))return d}return null};p.Hp=function(a){if(0>a||a>=this.bb.length)throw e.AC(a,this.bb.length);return this.bb[a]};p.Sg=function(a,b){var d=new c.Vcb;d.s3b(a);d.Wa(b);this.bb.push(d)};p.Uj=function(){this.bb=[]};p.nr=function(a){for(var b=!1,c=0;c<this.wc()&&!(b=this.Hp(c).Vha()==a);c++);b&&this.bb.splice(c,1)};e.ub(c.ILa,"PRIM_WEB","HttpHeaders",{Va:{Item:{f:function(a){return this.we(a)}},ItemCount:{f:p.wc}},yc:{Add:p.Sg,
Remove:p.nr,RemoveAll:p.Uj},dg:{bg:"Item"},Mp:{Zo:function(a){return this.Hp(e.aa(a-1))},kw:p.wc}});a.HE={f:1,WBc:2,BMc:3,kOc:4,Bp:5,E7c:6,zLc:7,vic:8,OLc:9};a.HE.G={GET:a.HE.f,HEAD:a.HE.WBc,POST:a.HE.BMc,PUT:a.HE.kOc,DELETE:a.HE.Bp,TRACE:a.HE.E7c,OPTIONS:a.HE.zLc,CONNECT:a.HE.vic,PATCH:a.HE.OLc};a.oH={kZb:1,w0b:2,A0:3,tR:4,uwb:5};a.oH.G={NOTEXECUTED:a.oH.kZb,PROCESSING:a.oH.w0b,COMPLETED:a.oH.A0,FAILED:a.oH.tR,CANCELLED:a.oH.uwb};c.KXb=function(){r.v.call(this);this.lXa="";this.s_=null;this.vVa=
a.HE.f;this.oqa=null;this.vI=new c.ILa;this.ifa=a.oH.kZb;this.nub=0;this.Dbc=!1;this.fh=null};var r=c.u(c.KXb,c.ld);r.R=function(){this.s_=null;this.Oib(null);this.fh&&(this.fh.xb(),this.fh=null);r.j.R.call(this)};r.jb=function(){null==this.fh&&(this.fh=e.$r(new c.QLa("")),this.fh.va());return this.fh};r.Hy=function(){return this.lXa};r.wZc=function(a){this.lXa=a};r.Yod=function(){return this.vVa};r.qXc=function(a){this.vVa=a};r.b4a=function(){return this.vI};r.tyc=function(){return this.oqa};r.Oib=
function(a){null!=this.oqa&&this.oqa.xb();this.oqa=a;null!=this.oqa&&this.oqa.va()};r.Crd=function(){return this.ifa};r.Izc=function(){return this.nub};r.gZc=function(a){this.nub=a};r.Ynd=function(){return this.Dbc};r.bGd=function(a){this.Dbc=a};r.r5b=function(f,k){var d=this;d.Oib(null);var g=d.s_=new XMLHttpRequest,l=e.Ga(d.vVa,a.HE.G),p=d.Hy();g.onreadystatechange=function(){4==g.readyState?(d.Oib(e.$r(new c.Wcb(g))),0!==g.status&&(d.ifa=a.oH.A0,d.za(a.K.A0),b.Dw(k))):d.ifa=a.oH.w0b};g.onerror=
function(){d.ifa=a.oH.tR;d.za(a.K.tR);b.Dw(k)};g.ontimeout=function(){d.ifa=a.oH.tR;d.za(a.K.tR);b.Dw(k)};g.open(l,p,f);f&&(g.timeout=this.nub);this.hec(g);l="";null!=this.fh&&(l=this.fh.Jp());g.send(l)};r.xra=function(){this.s_!==l&&(this.s_.abort(),this.ifa=a.oH.uwb)};r.oR=function(){this.r5b(!1,null)};r.f8=function(){this.r5b(!0,b.LO())};r.hec=function(a){var b=this.vI.wc();if(0!=b)for(var c=0;c<b;c++){var e=this.vI.Hp(c);a.setRequestHeader(e.Vha(),e.La())}};e.ub(c.KXb,"PRIM_WEB","HttpRequest",
{Va:{Url:{f:r.Hy,i:function(a){this.wZc(e.ma(a))}},Method:{f:function(){return e.Ga(this.vVa,a.HE.G)},i:function(b){this.qXc(e.Aa(b,a.HE.G))}},Content:{f:r.jb},Response:{f:r.tyc},Headers:{f:r.b4a},Status:{f:function(){return e.Ga(this.ifa,a.oH.G)}},Timeout:{f:r.Izc,i:function(a){this.gZc(e.aa(a))}}},yc:{Cancel:r.xra,Execute:r.oR,ExecuteAsync:r.f8}});c.Wcb=function(a){f.v.call(this);this.s_=a;this.vI=new c.ILa;this.fh=null;this.KIc(a.getAllResponseHeaders())};var f=c.u(c.Wcb,c.ld);f.R=function(){this.s_=
null;this.fh&&(this.fh.xb(),this.fh=null);f.j.R.call(this)};f.jb=function(){null==this.fh&&(this.fh=e.$r(new c.QLa(this.s_.responseText)),this.fh.va());return this.fh};f.hzc=function(){return this.s_.status};f.izc=function(){return this.s_.statusText};f.b4a=function(){return this.vI};f.KIc=function(a){for(var b=0,c="",e="";""!=a;){b=a.indexOf(":");if(-1==b)break;c=a.substring(0,b);a=a.slice(b+2);b=a.indexOf("\r\n");e=a.substring(0,b);a=a.slice(b+2);this.vI.Sg(c,e)}};e.ub(c.Wcb,"PRIM_WEB","HttpResponse",
{Va:{Content:{f:f.jb},StatusCode:{f:f.hzc},StatusText:{f:f.izc},Headers:{f:f.b4a}}});c.QLa=function(a){g.v.call(this);this.pg=a};var g=c.u(c.QLa,c.ld);g.Jp=function(){return this.pg};g.TK=function(a){this.pg=a};e.ub(c.QLa,"PRIM_WEB","HttpContent",{Va:{Text:{f:g.Jp,i:function(a){this.TK(e.ma(a))}}},dg:{bg:"Text"}})});
