window.LANSA.addSrc("drag",function(e,c,a,b){a.Pr={xGa:0,yGa:1,S7:2,vpc:3,zsa:4};a.Pr.G={ENTER:a.Pr.xGa,MOVE:a.Pr.yGa,EXIT:a.Pr.S7,DROP:a.Pr.vpc,HOVER:a.Pr.zsa};a.bN={I0a:0,QBb:1,RBb:2};a.bN.G={ENDED:a.bN.I0a,ACCEPTED:a.bN.QBb,CANCELLED:a.bN.RBb};a.$M={Oyb:0,Qyb:1,Nyb:2,Pyb:4};a.$M.G={NONE:a.$M.Oyb,SELECTION:a.$M.Qyb,IMAGE:a.$M.Nyb,POPUP:a.$M.Pyb};a.LG={i2:0,BJa:1,dCc:2};a.bi={BGa:16,N0a:1,zGa:2,P0a:16,Q0a:32,Asa:256,iCb:512,xpc:1024,hCb:2048,CGa:4096,ypc:8192,jCb:16384,lCb:32768,O0a:65536,kCb:131072,
AGa:262144};e.ad(function(){},"PRIM_DRAG",{});c.mUb=function(){l.v.call(this);this.RUa=0;this.zm=a.bi.BGa;this.wL=a.LG.i2;this.vda=this.$T=this.hrb=this.d_=this.Mea=this.dL=this.AF=this.hm=this.lq=this.sp=this.Br=null;this.Nda=new c.lUb};var l=c.u(c.mUb,c.ld);l.QW=function(){return!1};l.e4a=function(){return this.RUa};l.o3b=function(a){this.RUa=a};l.$gb=function(b){this.Bga(a.bi.zGa,b)};l.R2a=function(){return this.bva()?!0:!1};l.m4b=function(b){this.Bga(a.bi.P0a,b)};l.sIb=function(){return this.yCc()?
!0:!1};l.Wib=function(b){this.Bga(a.bi.Q0a,b)};l.RIa=function(){return this.zCc()?!0:!1};l.Hjd=function(){return this.sAc()?!0:!1};l.AFd=function(b){this.Bga(a.bi.jCb,b);b&&this.KM()};l.Bpd=function(){return!1};l.K4a=function(){return this.sp?this.sp.zh(this.hB):new c.sd(0,0)};l.RHb=function(){return this.Br?this.lea:new c.sd(0,0)};l.mOa=function(b){if(this.Br!=b)if(null!=this.Br&&this.Br.wa(this,this.r0a),this.Br=b){b=b=null;this.Br.ya(this,this.r0a);for(b=this.Br;b.nl();)b=b.W();this.lq!=b&&(null!=
this.lq&&this.lq.wa(this,this.sGa),(this.lq=b)&&this.lq.ya(this,this.sGa));for(b=this.lq;b.g9()==a.gr.jE;)b=b.W();this.AF!=b&&(null!=this.AF&&this.AF.wa(this,this.aGa),(this.AF=b)&&this.AF.ya(this,this.aGa))}else null!=this.Br&&(this.Br.wa(this,this.r0a),this.Br=null),null!=this.lq&&(this.lq.wa(this,this.sGa),this.lq=null),null!=this.AF&&(this.AF.wa(this,this.aGa),this.AF=null)};l.D4a=function(){return this.sp};l.cIb=function(){var b=[];(b[0]=this.sp)&&this.sp.W()&&this.mr(this.sp.W(),a.U.Iva,b,null);
return b[0]};l.bza=function(a){if(this.sp!=a)if(null!=this.sp&&this.sp.wa(this,this.y0a),this.sp=a){a=a=null;this.sp.ya(this,this.y0a);for(a=this.sp;a.nl();)a=a.W();this.hm!=a&&(null!=this.hm&&this.hm.wa(this,this.uGa),(this.hm=a)&&this.hm.ya(this,this.uGa));for(a=this.hm;a.nl();)a=a.W();this.dL!=a&&(null!=this.dL&&this.dL.wa(this,this.bGa),(this.dL=a)&&this.dL.ya(this,this.bGa))}else null!=this.sp&&(this.sp.wa(this,this.y0a),this.sp=null),null!=this.hm&&(this.hm.wa(this,this.uGa),this.hm=null),null!=
this.dL&&(this.dL.wa(this,this.bGa),this.dL=null)};l.M3a=function(){return this.Br};l.sia=function(){return this.lq};l.ryc=function(){var b=[];(b[0]=this.lq)&&this.lq.W()&&this.mr(this.lq.W(),a.U.Iva,b,null);return b[0]};l.m5a=function(){return this.hm};l.eIb=function(){var b=[];(b[0]=this.hm)&&this.hm.W()&&this.mr(this.hm.W(),a.U.Iva,b,null);return b[0]};l.U8=function(){return this.AF};l.lha=function(){return this.dL};l.TOa=function(a){this.Mea!=a&&(null!=this.Mea&&this.Mea.xb(),this.Mea=a,null!=
this.Mea&&this.Mea.va())};l.eia=function(){return this.Mea};l.nOa=function(a){this.d_!=a&&(null!=this.d_&&this.d_.xb(),this.d_=a,null!=this.d_&&this.d_.va())};l.Iha=function(){null==this.d_&&(this.d_=new c.Mbb);return this.d_};l.Yaa=function(a){this.hrb!=a&&(this.hrb=a)};l.R3a=function(){return this.hrb};l.Vaa=function(a){this.$T!=a&&(null!=this.$T&&(this.$T.wa(this,this.$zb),this.$T.xb()),this.$T=a,null!=this.$T&&(this.$T.va(),this.$T.ya(this,this.$zb)))};l.N3a=function(){return this.$T};l.QW=function(){return this.Z9()};
l.rEc=function(){return this.sCc()};l.Bud=function(){return this.bva()};l.Fud=function(){return this.DJa()};l.wvd=function(){return this.h7a()};l.Aed=function(){return this.rCc()};l.sMb=function(){return this.xCc()};l.GLb=function(){return this.oCc()};l.jBc=function(){return this.lJb()};l.Z9=function(){return 0!=(this.zm&a.bi.N0a)};l.bva=function(){return 0!=(this.zm&a.bi.zGa)};l.yCc=function(){return 0!=(this.zm&a.bi.P0a)};l.zCc=function(){return 0!=(this.zm&a.bi.Q0a)};l.DJa=function(){return 0!=
(this.zm&a.bi.Asa)};l.h7a=function(){return 0!=(this.zm&a.bi.CGa)};l.rCc=function(){return 0!=(this.zm&a.bi.ypc)};l.sCc=function(){return 0!=(this.zm&a.bi.kCb)};l.xCc=function(){return 0!=(this.zm&a.bi.lCb)};l.oCc=function(){return 0!=(this.zm&a.bi.AGa)};l.gud=function(){return!1};l.lJb=function(){return 0!=(this.zm&a.bi.O0a)};l.sAc=function(){return 0!=(this.zm&a.bi.jCb)};l.nV=function(a){this.zm|=a};l.N0=function(a){this.zm&=~a};l.Bga=function(a,b){this.zm=this.zm&~a|(b?a:0)};l.Vyb=function(){if(this.Br){if(this.Z9())this.axb();
else{var a=b.rl();this.Fbc.Wd(a)||this.Wvb()}return!0}return!1};l.d0a=function(){this.Br&&(this.bva()?this.eN():this.KM(!0))};l.Wvb=function(){this.vda=null;this.nV(a.bi.N0a);if(this.ENc()){var c=this.Iha().iCa;c!=a.$M.Qyb&&(c==a.$M.Nyb?this.Iha():c==a.$M.Pyb&&(c=this.Iha().Au,null!=c&&this.Nda.m_c(c)));this.axb()}b.ja(null);this.vda=null};l.axb=function(){if(!this.DJa()){this.hB=b.rl();var c=b.sLa(this.hB),e=null;if(e=c)for(;e.nl();)e=e.W();if(e!=this.hm){if(null!=this.hm&&!this.ala(a.Pr.S7,this.hm))return;
this.N0(a.bi.zGa);this.N0(a.bi.Q0a);this.nV(a.bi.P0a);this.Yaa(null);this.Vaa(null);this.bza(c);if(this.hm&&!this.ala(a.Pr.xGa,this.hm))return}else if(null!=this.hm&&(this.bza(c),!this.ala(a.Pr.yGa,this.hm)))return;this.Nda.spc();this.Onb()}};l.KM=function(d){var e=this.GLb();if(this.DJa())this.nV(d?a.bN.I0a:a.bi.hCb);else{if(this.h7a())this.zm=a.bi.BGa;else if(this.Z9()&&(this.nV(a.bi.CGa),this.sp&&(this.hB=b.rl(),this.hm&&this.ala(a.Pr.S7,this.hm),this.Yaa(null),this.Vaa(null)),this.lq&&(d=new c.Pbb(this,
this.lq,d?a.bN.I0a:a.bN.RBb),this.lq.Bd(a.U.y$a,null,d))),this.zm=a.bi.BGa,this.Br){if(e||!b.uo(a.Sb.Gva,this.Br.Lc))this.Br.Rn(),this.N0(a.bi.AGa);this.bza(null);this.mOa(null)}this.v1b()}};l.eN=function(){var b=!1;if(this.DJa())return this.nV(a.bi.iCb),b;if(this.h7a())return b;if(this.Br||this.rEc())this.Br&&(this.GLb()||0==(this.Br.Lc&a.Sb.Gva))&&(this.Br.Rn(),this.N0(a.bi.AGa)),this.Z9()&&(b=this.SLc()),this.zm=a.bi.BGa,this.v1b();return b};l.aNc=function(){this.jBc()||this.KM()};l.SLc=function(){var d=
!1,e=this.M3a(),f=this.D4a(),k=this.m5a(),h=this.sia(),g=a.bN.QBb;this.N0(a.bi.N0a);this.N0(a.bi.kCb);this.nV(a.bi.CGa);this.Nda.eN();f&&(this.Vaa(null),this.hB=b.rl(),f=new c.kUb(this,k,g),k.Bd(a.U.x$a,null,f),g=f.Oda,k&&this.ala(a.Pr.S7,k),d=!0,this.Yaa(null));e&&h&&(f=new c.Pbb(this,h,g),h.Bd(a.U.y$a,null,f));return d};l.v1b=function(){this.TOa(null);this.nOa(null);this.bza(null);this.mOa(null);this.Nda.eN();a.pSa=null;a.bL&&(a.bL.JS(),a.bL=null)};l.mUc=function(d,e,f,k){this.KM();this.mOa(d);
this.Bga(a.bi.lCb,0>b.Ih(a.Ha.aoa));f?(this.lea=e,d=d.MM(this.lea),this.Fbc=new c.ha(d.zb(),d.Ab(),0,0)):(this.lea=b.rl(),e=new c.XG(15,15),this.Fbc=new c.ha(this.lea.zb()-e.$()/2,this.lea.Ab()-e.ba()/2,e.$(),e.ba()),this.lea=d.zh(this.lea));if(k||!b.uo(a.Sb.Gva,this.Br.Lc))this.Br.BB(),this.nV(a.bi.AGa);f&&this.Wvb()};l.a8c=function(b){this.Z9()&&(this.Bga(a.bi.zGa,b),this.bva()?this.eN():this.KM(!0))};l.Onb=function(){var b;this.Z9()&&(b=null,this.hm&&(b=this.$T),null==b&&(b=this.bva()?e.tia().o1().get("APPSTARTING"):
e.tia().o1().get("NO")),a.pSa=b)};l.R_b=function(){if(0==(this.zm&a.bi.CGa)){if(0!=(this.zm&a.bi.iCb))return this.KM(!0),!1;if(0!=(this.zm&a.bi.hCb))return this.KM(),!1;if(0!=(this.zm&a.bi.xpc))return this.eN(),!1}return!0};l.ENc=function(){this.nV(a.bi.Asa);var b=new c.KVb(this,this.lq);this.lq.Bd(a.U.fOb,null,b);this.N0(a.bi.Asa);return this.R_b()?b.bTa?!0:(this.KM(),!1):!1};l.ala=function(d,e){this.nV(a.bi.Asa);null!=this.Br&&null!=this.sp||this.wL==a.LG.i2||(b.bH().Aia().Da(this,a.K.SY,null),
this.wL=a.LG.i2);switch(d){case a.Pr.S7:this.wL!=a.LG.i2&&(b.bH().Aia().Da(this,a.K.SY,null),this.wL=a.LG.i2);if(e){var f=new c.Cwa(this,e,a.Pr.S7);e.Bd(a.U.Eja,null,f)}break;case a.Pr.xGa:e&&(f=new c.Cwa(this,e,a.Pr.xGa),e.Bd(a.U.Eja,null,f));this.wL==a.LG.i2&&b.bH().Aia().Da(this,a.K.SY,this.Q7);this.wL=a.LG.BJa;this.UT=this.hB;break;case a.Pr.yGa:this.wL!=a.LG.i2&&(f=new c.XG(15,15),this.hB.zb()<this.UT.zb()-f.$()||this.hB.zb()>this.UT.zb()+f.$()||this.hB.Ab()<this.UT.Ab()-f.ba()||this.hB.Ab()>
this.UT.Ab()+f.ba())&&(this.wL=a.LG.BJa,this.UT=this.hB);e&&(f=new c.Cwa(this,e,a.Pr.yGa),e.Bd(a.U.Eja,null,f));break;case a.Pr.zsa:this.wL!=a.LG.i2&&(this.hB=b.rl(),f=new c.XG(15,15),this.hB.zb()<this.UT.zb()-f.$()||this.hB.zb()>this.UT.zb()+f.$()||this.hB.Ab()<this.UT.Ab()-f.ba()||this.hB.Ab()>this.UT.Ab()+f.ba()?(this.wL=a.LG.BJa,this.UT=this.hB):this.wL==a.LG.BJa?(this.wL=a.LG.dCc,this.RUa=0):(this.RUa++,e&&(f=new c.Cwa(this,e,a.Pr.zsa),e.Bd(a.U.Eja,null,f))))}this.N0(a.bi.Asa);return this.R_b()};
l.Ebd=function(b){var c=this.lJb();this.zm=this.zm&~a.bi.O0a|(b?a.bi.O0a:0);return c};l.Q7=function(){this.Z9()&&this.hm&&this.ala(a.Pr.zsa,this.hm)&&this.Onb()};l.$zb=function(b,c){switch(c.Ya){case a.a.rb:case a.a.Pb:this.Vaa(null);break;case a.a.h:this.Onb()}};l.r0a=function(b,c){switch(c.Ya){case a.a.rb:case a.a.Pb:this.mOa(null)}};l.y0a=function(b,c){switch(c.Ya){case a.a.rb:case a.a.Pb:this.bza(null)}};l.sGa=function(b,c){switch(c.Ya){case a.a.rb:case a.a.Pb:this.lq.wa(this,this.sGa),this.lq=
null,this.KM(!1)}};l.uGa=function(b,c){switch(c.Ya){case a.a.rb:case a.a.Pb:this.hm.wa(this,this.uGa),this.hm=null}};l.aGa=function(b,c){switch(c.Ya){case a.a.rb:case a.a.Pb:this.AF.wa(this,this.aGa),this.AF=null}};l.bGa=function(b,c){switch(c.Ya){case a.a.rb:case a.a.Pb:this.dL.wa(this,this.bGa),this.dL=null}};c.lUb=function(){u.v.call(this);this.P5=null;this.JTa=!1;this.l6=new c.sd(0,0);this.wqa=new c.sd(0,0)};var u=c.u(c.lUb,c.ld);u.tb=function(){b.Q().Waa(null)};u.Imd=function(){return this.P5};
u.m_c=function(a){this.JTa=!1;null!=a&&a.jb()&&(this.wqa.al(a.jb().Sa()),this.wqa.jk(a.jb().Qa()),this.l6.al(-(this.wqa.zb()+1)),this.l6.jk(-(this.wqa.Ab()+1)),b.Q().Waa(a),this.JTa=!0)};u.eN=function(){var a=b.Q().Au;null!=this.P5?(this.P5.Wra(),delete this.P5,this.P5=null):a&&(a.Em(),b.Q().Waa(null));this.JTa=!1};u.spc=function(){if(this.JTa){var d=b.Q().Au,e=b.rl(),e=new c.ha(e.zb()+this.l6.zb(),e.Ab()+this.l6.Ab(),this.wqa.zb(),this.wqa.Ab());if(this.P5)this.P5.Xzd(e),this.P5.Gyd(e);else if(d){var f=
d.yh();d.Px(a.bj.ww,null,e.Lna(),null);f||(this.l6.al(this.l6.zb()-(e.O()-d.gf.zb())),this.l6.jk(this.l6.Ab()-(e.M()-d.gf.Ab())))}}};c.Mbb=function(){p.v.call(this);this.iCa=a.$M.Oyb;this.Au=this.Mda=null};var p=c.u(c.Mbb,c.ld);p.R=function(){p.j.R.call(this);this.Waa(null)};p.GGb=function(){return this.Au};p.Waa=function(b){this.Au!=b&&(this.Au&&this.Au.wa(this,this.fGa),(this.Au=b)&&this.Au.ya(this,this.fGa),this.m(a.a.h))};p.jWc=function(b){this.iCa!=b&&(this.iCa=b,this.m(a.a.h))};p.Emd=function(){return this.iCa};
p.iWc=function(b){this.Mda!=b&&(this.Mda&&this.Mda.xb(),(this.Mda=b)&&this.Mda.va(),this.m(a.a.h))};p.Ouc=function(){return this.Mda};p.fGa=function(b,c){switch(c.Ya){case a.a.rb:case a.a.Pb:this.Waa(null)}};e.ad(c.Mbb,"PRIM_DGLT",{Va:{DragPopup:{f:p.GGb,i:p.Waa},DragImage:{f:p.Ouc,i:p.iWc},DragListStyle:{f:function(){return e.Ga(this.iCa,a.$M.G)},i:function(b){this.jWc(e.Aa(b,a.$M.G))}}}});c.Bwa=function(b,c,e){r.v.call(this,c);this.GI=a.TS.N1b;this.ym=b;this.AF=e;this.Tea=this.Sea=0};var r=c.u(c.Bwa,
c.LTb);r.M3a=function(){return this.ym.M3a()};r.sia=function(){return this.ym.ryc()};r.U8=function(){return this.ym.U8()};r.Iha=function(){return this.ym.Iha()};r.eia=function(){return this.ym.eia()};r.w9=function(){return this.ym.K4a()};r.RHb=function(){return this.ym.RHb()};r.L4a=function(){return this.ym.K4a().zb()+this.Sea};r.M4a=function(){return this.ym.K4a().Ab()+this.Tea};r.nqd=function(){return this.Sea};r.XOa=function(a){this.Sea=a};r.oqd=function(){return this.Tea};r.YOa=function(a){this.Tea=
a};r.vG=function(){return this.ym.vG()};r.sMb=function(){return this.ym.sMb()};r.A1b=function(){var a=this.AF;null==a&&(a=this.ym.U8());return a};c.KVb=function(a,b){f.v.call(this,a,b,null);this.bTa=!0};var f=c.u(c.KVb,c.Bwa);f.ykd=function(){return this.bTa};f.RVc=function(a){this.bTa=a};f.TOa=function(a){this.ym.TOa(a)};f.nOa=function(a){this.ym.nOa(a)};c.Pbb=function(a,b,c){g.v.call(this,a,b,null);this.Oda=c};var g=c.u(c.Pbb,c.Bwa);g.Puc=function(){return this.Oda};c.Cwa=function(a,b,c){m.v.call(this,
a,b,null);this.zm=c};var m=c.u(c.Cwa,c.Bwa);m.e4a=function(){return this.ym.e4a()};m.o3b=function(a){this.ym.o3b(a)};m.$gb=function(a){this.ym.$gb(a)};m.R2a=function(){return this.ym.R2a()};m.m4b=function(a){this.ym.m4b(a)};m.sIb=function(){return this.ym.sIb()};m.Wib=function(a){this.ym.Wib(a)};m.RIa=function(){return this.ym.RIa()};m.Gmd=function(){return this.zm};m.Yaa=function(a){this.ym.Yaa(a)};m.R3a=function(){return this.ym.R3a()};m.Vaa=function(a){this.ym.Vaa(a)};m.N3a=function(){return this.ym.N3a()};
m.D4a=function(){return this.ym.cIb()};m.m5a=function(){return this.ym.eIb()};m.lha=function(){return this.ym.lha()};c.kUb=function(a,b,c){k.v.call(this,a,b,null);this.Oda=c};var k=c.u(c.kUb,c.Bwa);k.D4a=function(){return this.ym.cIb()};k.m5a=function(){return this.ym.eIb()};k.lha=function(){return this.ym.lha()};k.Puc=function(){return this.Oda};k.kWc=function(a){this.Oda=a}});
